//! Tabelas do ps (output.c): `format_array`, `macro_array`, `aix_array` e `shortsort_array`.
//!
//! O `FORMAT_ARRAY` e o `MACRO_ARRAY` foram gerados do `output.c` do procps-ng 4.0.4 por um awk (são
//! 275 linhas de dados); a ordem é a do upstream, que a busca binária dele exige ordenada por
//! `strcmp`. Aqui a busca é linear sobre a mesma tabela.

use super::output::*;
use super::{Fmt, Item};
use super::{AIX, BSD, DEC, HPU, LNX, SCO, SGI, SOE, SUN, TST, U98, XXX};

const USER: u32 = super::CF_USER;
const LEFT: u32 = super::CF_LEFT;
const RIGHT: u32 = super::CF_RIGHT;
const UNLIMITED: u32 = super::CF_UNLIMITED;
const WCHAN: u32 = super::CF_WCHAN;
const SIGNAL: u32 = super::CF_SIGNAL;
const PIDMAX: u32 = super::CF_PIDMAX;
const TO: u32 = super::CF_PRINT_THREAD_ONLY;
const PO: u32 = super::CF_PRINT_PROCESS_ONLY;
const ET: u32 = super::CF_PRINT_EVERY_TIME;
const AN: u32 = super::CF_PRINT_AS_NEEDED;

/// Procura um especificador de formato (`search_format_array`).
pub fn search_format_array(spec: &[u8]) -> Option<&'static Fmt> {
    FORMAT_ARRAY.iter().find(|f| f.spec.as_bytes() == spec)
}

/// Procura uma macro de formato (`search_macro_array`).
pub fn search_macro_array(spec: &[u8]) -> Option<&'static str> {
    MACRO_ARRAY.iter().find(|m| m.0.as_bytes() == spec).map(|m| m.1)
}

/// Código AIX (`%a`) para o especificador e o cabeçalho (`search_aix_array`).
pub fn search_aix_array(code: u8) -> Option<(&'static str, &'static str)> {
    AIX_ARRAY.iter().find(|a| a.0 == code).map(|a| (a.1, a.2))
}

/// Código de ordenação curto (`O`, `k`) para o especificador (`search_shortsort_array`).
pub fn search_shortsort_array(code: u8) -> Option<&'static str> {
    SHORTSORT_ARRAY.iter().find(|a| a.0 == code).map(|a| a.1)
}

const AIX_ARRAY: &[(u8, &str, &str)] = &[
    (b'C', "pcpu", "%CPU"),
    (b'G', "group", "GROUP"),
    (b'P', "ppid", "PPID"),
    (b'U', "user", "USER"),
    (b'a', "args", "COMMAND"),
    (b'c', "comm", "COMMAND"),
    (b'g', "rgroup", "RGROUP"),
    (b'n', "nice", "NI"),
    (b'p', "pid", "PID"),
    (b'r', "pgid", "PGID"),
    (b't', "etime", "ELAPSED"),
    (b'u', "ruser", "RUSER"),
    (b'x', "time", "TIME"),
    (b'y', "tty", "TTY"),
    (b'z', "vsz", "VSZ"),
];

const SHORTSORT_ARRAY: &[(u8, &str)] = &[
    (b'C', "pcpu"),
    (b'G', "tpgid"),
    (b'J', "cstime"),
    (b'M', "maj_flt"),
    (b'N', "cmaj_flt"),
    (b'P', "ppid"),
    (b'R', "resident"),
    (b'S', "share"),
    (b'T', "start_time"),
    (b'U', "uid"),
    (b'c', "cmd"),
    (b'f', "flags"),
    (b'g', "pgrp"),
    (b'j', "cutime"),
    (b'k', "utime"),
    (b'm', "min_flt"),
    (b'n', "cmin_flt"),
    (b'o', "session"),
    (b'p', "pid"),
    (b'r', "rss"),
    (b's', "size"),
    (b't', "tty"),
    (b'u', "user"),
    (b'v', "vsize"),
    (b'y', "priority"),
];

/// `format_array` do output.c, na ordem do upstream.
pub static FORMAT_ARRAY: &[Fmt] = &[
    Fmt { spec: "%cpu", head: "%CPU", pr: pr_pcpu, nop: false, sr: Item::Utilization, width: 4, vendor: BSD, flags: ET | RIGHT },
    Fmt { spec: "%mem", head: "%MEM", pr: pr_pmem, nop: false, sr: Item::VmRss, width: 4, vendor: BSD, flags: PO | RIGHT },
    Fmt { spec: "_left", head: "LLLLLLLL", pr: pr_t_left, nop: false, sr: Item::Noop, width: 8, vendor: TST, flags: ET | LEFT },
    Fmt { spec: "_left2", head: "L2L2L2L2", pr: pr_t_left2, nop: false, sr: Item::Noop, width: 8, vendor: TST, flags: ET | LEFT },
    Fmt { spec: "_right", head: "RRRRRRRRRRR", pr: pr_t_right, nop: false, sr: Item::Noop, width: 11, vendor: TST, flags: ET | RIGHT },
    Fmt { spec: "_right2", head: "R2R2R2R2R2R", pr: pr_t_right2, nop: false, sr: Item::Noop, width: 11, vendor: TST, flags: ET | RIGHT },
    Fmt { spec: "_unlimited", head: "U", pr: pr_t_unlimited, nop: false, sr: Item::Noop, width: 16, vendor: TST, flags: ET | UNLIMITED },
    Fmt { spec: "_unlimited2", head: "U2", pr: pr_t_unlimited2, nop: false, sr: Item::Noop, width: 16, vendor: TST, flags: ET | UNLIMITED },
    Fmt { spec: "acflag", head: "ACFLG", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "acflg", head: "ACFLG", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "addr", head: "ADDR", pr: pr_nop, nop: true, sr: Item::Noop, width: 4, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "addr_1", head: "ADDR", pr: pr_nop, nop: true, sr: Item::Noop, width: 1, vendor: LNX, flags: AN | LEFT },
    Fmt { spec: "ag_id", head: "AGID", pr: pr_agid, nop: false, sr: Item::AutogrpId, width: 5, vendor: LNX, flags: AN | RIGHT },
    Fmt { spec: "ag_nice", head: "AGNI", pr: pr_agnice, nop: false, sr: Item::AutogrpNice, width: 4, vendor: LNX, flags: AN | RIGHT },
    Fmt { spec: "alarm", head: "ALARM", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: LNX, flags: AN | RIGHT },
    Fmt { spec: "argc", head: "ARGC", pr: pr_nop, nop: true, sr: Item::Noop, width: 4, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "args", head: "COMMAND", pr: pr_args, nop: false, sr: Item::Cmdline, width: 27, vendor: U98, flags: PO | UNLIMITED },
    Fmt { spec: "atime", head: "TIME", pr: pr_time, nop: false, sr: Item::TimeAll, width: 8, vendor: SOE, flags: ET | RIGHT },
    Fmt { spec: "blocked", head: "BLOCKED", pr: pr_sigmask, nop: false, sr: Item::Sigblocked, width: 9, vendor: BSD, flags: TO | SIGNAL },
    Fmt { spec: "bnd", head: "BND", pr: pr_nop, nop: true, sr: Item::Noop, width: 1, vendor: AIX, flags: TO | RIGHT },
    Fmt { spec: "bsdstart", head: "START", pr: pr_bsdstart, nop: false, sr: Item::TicsBegan, width: 6, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "bsdtime", head: "TIME", pr: pr_bsdtime, nop: false, sr: Item::TicsAll, width: 6, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "c", head: "C", pr: pr_c, nop: false, sr: Item::Utilization, width: 2, vendor: SUN, flags: ET | RIGHT },
    Fmt { spec: "caught", head: "CAUGHT", pr: pr_sigcatch, nop: false, sr: Item::Sigcatch, width: 9, vendor: BSD, flags: TO | SIGNAL },
    Fmt { spec: "cgname", head: "CGNAME", pr: pr_cgname, nop: false, sr: Item::Cgname, width: 27, vendor: LNX, flags: PO | UNLIMITED },
    Fmt { spec: "cgroup", head: "CGROUP", pr: pr_cgroup, nop: false, sr: Item::Cgroup, width: 27, vendor: LNX, flags: PO | UNLIMITED },
    Fmt { spec: "cgroupns", head: "CGROUPNS", pr: pr_cgroupns, nop: false, sr: Item::NsCgroup, width: 10, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "class", head: "CLS", pr: pr_class, nop: false, sr: Item::SchedClass, width: 3, vendor: XXX, flags: TO | LEFT },
    Fmt { spec: "cls", head: "CLS", pr: pr_class, nop: false, sr: Item::SchedClass, width: 3, vendor: HPU, flags: TO | RIGHT },
    Fmt { spec: "cmaj_flt", head: "-", pr: pr_nop, nop: true, sr: Item::Noop, width: 1, vendor: LNX, flags: AN | RIGHT },
    Fmt { spec: "cmd", head: "CMD", pr: pr_args, nop: false, sr: Item::Cmdline, width: 27, vendor: DEC, flags: PO | UNLIMITED },
    Fmt { spec: "cmin_flt", head: "-", pr: pr_nop, nop: true, sr: Item::Noop, width: 1, vendor: LNX, flags: AN | RIGHT },
    Fmt { spec: "cnswap", head: "-", pr: pr_nop, nop: true, sr: Item::Noop, width: 1, vendor: LNX, flags: AN | RIGHT },
    Fmt { spec: "comm", head: "COMMAND", pr: pr_comm, nop: false, sr: Item::Cmd, width: 15, vendor: U98, flags: PO | UNLIMITED },
    Fmt { spec: "command", head: "COMMAND", pr: pr_args, nop: false, sr: Item::Cmdline, width: 27, vendor: XXX, flags: PO | UNLIMITED },
    Fmt { spec: "context", head: "CONTEXT", pr: pr_context, nop: false, sr: Item::IdTgid, width: 31, vendor: LNX, flags: ET | LEFT },
    Fmt { spec: "cp", head: "CP", pr: pr_cp, nop: false, sr: Item::Utilization, width: 3, vendor: DEC, flags: ET | RIGHT },
    Fmt { spec: "cpu", head: "CPU", pr: pr_nop, nop: true, sr: Item::Noop, width: 3, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "cpuid", head: "CPUID", pr: pr_psr, nop: false, sr: Item::Processor, width: 5, vendor: BSD, flags: TO | RIGHT} },
    Fmt { spec: "cputime", head: "TIME", pr: pr_time, nop: false, sr: Item::TimeAll, width: 8, vendor: DEC, flags: ET | RIGHT },
    Fmt { spec: "cputimes", head: "TIME", pr: pr_times, nop: false, sr: Item::TimeAll, width: 8, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "ctid", head: "CTID", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: SUN, flags: ET | RIGHT} },
    Fmt { spec: "cuc", head: "%CUC", pr: pr_utilization_c, nop: false, sr: Item::UtilizationC, width: 7, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "cursig", head: "CURSIG", pr: pr_nop, nop: true, sr: Item::Noop, width: 6, vendor: DEC, flags: AN | RIGHT },
    Fmt { spec: "cutime", head: "-", pr: pr_nop, nop: true, sr: Item::TicsUserC, width: 1, vendor: LNX, flags: AN | RIGHT },
    Fmt { spec: "cuu", head: "%CUU", pr: pr_utilization, nop: false, sr: Item::Utilization, width: 6, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "cwd", head: "CWD", pr: pr_nop, nop: true, sr: Item::Noop, width: 3, vendor: LNX, flags: AN | LEFT },
    Fmt { spec: "drs", head: "DRS", pr: pr_drs, nop: false, sr: Item::VsizeBytes, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "dsiz", head: "DSIZ", pr: pr_dsiz, nop: false, sr: Item::VsizeBytes, width: 4, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "egid", head: "EGID", pr: pr_egid, nop: false, sr: Item::IdEgid, width: 5, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "egroup", head: "EGROUP", pr: pr_egroup, nop: false, sr: Item::IdEgroup, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "eip", head: "EIP", pr: pr_eip, nop: false, sr: Item::AddrCurrEip, width: 16, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "emul", head: "EMUL", pr: pr_nop, nop: true, sr: Item::Noop, width: 13, vendor: BSD, flags: PO | LEFT },
    Fmt { spec: "end_code", head: "E_CODE", pr: pr_nop, nop: true, sr: Item::AddrCodeEnd, width: 16, vendor: LNX, flags: PO | RIGHT} },
    Fmt { spec: "environ", head: "ENVIRONMENT", pr: pr_nop, nop: true, sr: Item::Noop, width: 11, vendor: LNX, flags: PO | UNLIMITED },
    Fmt { spec: "esp", head: "ESP", pr: pr_esp, nop: false, sr: Item::AddrCurrEsp, width: 16, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "etime", head: "ELAPSED", pr: pr_etime, nop: false, sr: Item::TimeElapsed, width: 11, vendor: U98, flags: ET | RIGHT },
    Fmt { spec: "etimes", head: "ELAPSED", pr: pr_etimes, nop: false, sr: Item::TimeElapsed, width: 7, vendor: BSD, flags: ET | RIGHT },
    Fmt { spec: "euid", head: "EUID", pr: pr_euid, nop: false, sr: Item::IdEuid, width: 5, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "euser", head: "EUSER", pr: pr_euser, nop: false, sr: Item::IdEuser, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "exe", head: "EXE", pr: pr_exe, nop: false, sr: Item::Exe, width: 27, vendor: LNX, flags: PO | UNLIMITED },
    Fmt { spec: "f", head: "F", pr: pr_flag, nop: false, sr: Item::Flags, width: 1, vendor: XXX, flags: ET | RIGHT },
    Fmt { spec: "fgid", head: "FGID", pr: pr_fgid, nop: false, sr: Item::Flags, width: 5, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "fgroup", head: "FGROUP", pr: pr_fgroup, nop: false, sr: Item::IdFgroup, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "flag", head: "F", pr: pr_flag, nop: false, sr: Item::Flags, width: 1, vendor: DEC, flags: ET | RIGHT },
    Fmt { spec: "flags", head: "F", pr: pr_flag, nop: false, sr: Item::Flags, width: 1, vendor: BSD, flags: ET | RIGHT },
    Fmt { spec: "fname", head: "COMMAND", pr: pr_fname, nop: false, sr: Item::Cmd, width: 8, vendor: SUN, flags: PO | LEFT },
    Fmt { spec: "fsgid", head: "FSGID", pr: pr_fgid, nop: false, sr: Item::IdFgid, width: 5, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "fsgroup", head: "FSGROUP", pr: pr_fgroup, nop: false, sr: Item::IdFgroup, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "fsuid", head: "FSUID", pr: pr_fuid, nop: false, sr: Item::IdFuid, width: 5, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "fsuser", head: "FSUSER", pr: pr_fuser, nop: false, sr: Item::IdFuser, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "fuid", head: "FUID", pr: pr_fuid, nop: false, sr: Item::IdFuid, width: 5, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "fuser", head: "FUSER", pr: pr_fuser, nop: false, sr: Item::IdFuser, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "gid", head: "GID", pr: pr_egid, nop: false, sr: Item::IdEgid, width: 5, vendor: SUN, flags: ET | RIGHT },
    Fmt { spec: "group", head: "GROUP", pr: pr_egroup, nop: false, sr: Item::IdEgroup, width: 8, vendor: U98, flags: ET | USER },
    Fmt { spec: "ignored", head: "IGNORED", pr: pr_sigignore, nop: false, sr: Item::Sigignore, width: 9, vendor: BSD, flags: TO | SIGNAL },
    Fmt { spec: "inblk", head: "INBLK", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "inblock", head: "INBLK", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: DEC, flags: AN | RIGHT },
    Fmt { spec: "intpri", head: "PRI", pr: pr_opri, nop: false, sr: Item::Priority, width: 3, vendor: HPU, flags: TO | RIGHT },
    Fmt { spec: "ipcns", head: "IPCNS", pr: pr_ipcns, nop: false, sr: Item::NsIpc, width: 10, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "jid", head: "JID", pr: pr_nop, nop: true, sr: Item::Noop, width: 1, vendor: SGI, flags: PO | RIGHT },
    Fmt { spec: "jobc", head: "JOBC", pr: pr_nop, nop: true, sr: Item::Noop, width: 4, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "ktrace", head: "KTRACE", pr: pr_nop, nop: true, sr: Item::Noop, width: 8, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "ktracep", head: "KTRACEP", pr: pr_nop, nop: true, sr: Item::Noop, width: 8, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "label", head: "LABEL", pr: pr_context, nop: false, sr: Item::IdTgid, width: 31, vendor: SGI, flags: ET | LEFT },
    Fmt { spec: "lastcpu", head: "C", pr: pr_psr, nop: false, sr: Item::Processor, width: 3, vendor: BSD, flags: TO | RIGHT} },
    Fmt { spec: "lim", head: "LIM", pr: pr_lim, nop: false, sr: Item::RssRlim, width: 5, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "login", head: "LOGNAME", pr: pr_nop, nop: true, sr: Item::Noop, width: 8, vendor: BSD, flags: AN | LEFT },
    Fmt { spec: "logname", head: "LOGNAME", pr: pr_nop, nop: true, sr: Item::Noop, width: 8, vendor: XXX, flags: AN | LEFT },
    Fmt { spec: "longtname", head: "TTY", pr: pr_tty8, nop: false, sr: Item::TtyName, width: 8, vendor: DEC, flags: PO | LEFT },
    Fmt { spec: "lsession", head: "SESSION", pr: pr_sd_session, nop: false, sr: Item::SdSess, width: 11, vendor: LNX, flags: ET | LEFT },
    Fmt { spec: "lstart", head: "STARTED", pr: pr_lstart, nop: false, sr: Item::TicsBegan, width: 24, vendor: XXX, flags: ET | RIGHT },
    Fmt { spec: "luid", head: "LUID", pr: pr_luid, nop: false, sr: Item::IdLogin, width: 5, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "luser", head: "LUSER", pr: pr_nop, nop: true, sr: Item::Noop, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "lwp", head: "LWP", pr: pr_tasks, nop: false, sr: Item::IdPid, width: 5, vendor: SUN, flags: TO | PIDMAX | RIGHT },
    Fmt { spec: "lxc", head: "LXC", pr: pr_lxcname, nop: false, sr: Item::Lxcname, width: 8, vendor: LNX, flags: ET | LEFT },
    Fmt { spec: "m_drs", head: "DRS", pr: pr_drs, nop: false, sr: Item::VsizeBytes, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "m_dt", head: "DT", pr: pr_nop, nop: true, sr: Item::Noop, width: 4, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "m_lrs", head: "LRS", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "m_resident", head: "RES", pr: pr_nop, nop: true, sr: Item::MemResPgs, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "m_share", head: "SHRD", pr: pr_nop, nop: true, sr: Item::MemShrPgs, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "m_size", head: "SIZE", pr: pr_size, nop: false, sr: Item::VsizeBytes, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "m_swap", head: "SWAP", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "m_trs", head: "TRS", pr: pr_trs, nop: false, sr: Item::VsizeBytes, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "machine", head: "MACHINE", pr: pr_sd_machine, nop: false, sr: Item::SdMach, width: 31, vendor: LNX, flags: ET | LEFT },
    Fmt { spec: "maj_flt", head: "MAJFL", pr: pr_majflt, nop: false, sr: Item::FltMaj, width: 6, vendor: LNX, flags: AN | RIGHT },
    Fmt { spec: "majflt", head: "MAJFLT", pr: pr_majflt, nop: false, sr: Item::FltMaj, width: 6, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "min_flt", head: "MINFL", pr: pr_minflt, nop: false, sr: Item::FltMin, width: 6, vendor: LNX, flags: AN | RIGHT },
    Fmt { spec: "minflt", head: "MINFLT", pr: pr_minflt, nop: false, sr: Item::FltMin, width: 6, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "mntns", head: "MNTNS", pr: pr_mntns, nop: false, sr: Item::NsMnt, width: 10, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "msgrcv", head: "MSGRCV", pr: pr_nop, nop: true, sr: Item::Noop, width: 6, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "msgsnd", head: "MSGSND", pr: pr_nop, nop: true, sr: Item::Noop, width: 6, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "mwchan", head: "MWCHAN", pr: pr_nop, nop: true, sr: Item::Noop, width: 6, vendor: BSD, flags: TO | WCHAN },
    Fmt { spec: "netns", head: "NETNS", pr: pr_netns, nop: false, sr: Item::NsNet, width: 10, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "ni", head: "NI", pr: pr_nice, nop: false, sr: Item::Nice, width: 3, vendor: BSD, flags: TO | RIGHT },
    Fmt { spec: "nice", head: "NI", pr: pr_nice, nop: false, sr: Item::Nice, width: 3, vendor: U98, flags: TO | RIGHT },
    Fmt { spec: "nivcsw", head: "IVCSW", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "nlwp", head: "NLWP", pr: pr_nlwp, nop: false, sr: Item::Nlwp, width: 4, vendor: SUN, flags: PO | RIGHT },
    Fmt { spec: "nsignals", head: "NSIGS", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: DEC, flags: AN | RIGHT },
    Fmt { spec: "nsigs", head: "NSIGS", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "nswap", head: "NSWAP", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "numa", head: "NUMA", pr: pr_numa, nop: false, sr: Item::ProcessorNode, width: 4, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "nvcsw", head: "VCSW", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "nwchan", head: "WCHAN", pr: pr_nop, nop: true, sr: Item::Noop, width: 6, vendor: XXX, flags: TO | RIGHT },
    Fmt { spec: "oom", head: "OOM", pr: pr_oom, nop: false, sr: Item::OomScore, width: 4, vendor: XXX, flags: TO | RIGHT },
    Fmt { spec: "oomadj", head: "OOMADJ", pr: pr_oom_adj, nop: false, sr: Item::OomAdj, width: 5, vendor: XXX, flags: TO | RIGHT },
    Fmt { spec: "opri", head: "PRI", pr: pr_opri, nop: false, sr: Item::Priority, width: 3, vendor: SUN, flags: TO | RIGHT },
    Fmt { spec: "osz", head: "SZ", pr: pr_nop, nop: true, sr: Item::Noop, width: 2, vendor: SUN, flags: PO | RIGHT },
    Fmt { spec: "oublk", head: "OUBLK", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "oublock", head: "OUBLK", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: DEC, flags: AN | RIGHT },
    Fmt { spec: "ouid", head: "OWNER", pr: pr_sd_ouid, nop: false, sr: Item::SdOuid, width: 5, vendor: LNX, flags: ET | LEFT },
    Fmt { spec: "p_ru", head: "P_RU", pr: pr_nop, nop: true, sr: Item::Noop, width: 6, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "paddr", head: "PADDR", pr: pr_nop, nop: true, sr: Item::Noop, width: 6, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "pagein", head: "PAGEIN", pr: pr_majflt, nop: false, sr: Item::FltMaj, width: 6, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "pcpu", head: "%CPU", pr: pr_pcpu, nop: false, sr: Item::Utilization, width: 4, vendor: U98, flags: ET | RIGHT },
    Fmt { spec: "pending", head: "PENDING", pr: pr_sig, nop: false, sr: Item::Signals, width: 9, vendor: BSD, flags: ET | SIGNAL },
    Fmt { spec: "pgid", head: "PGID", pr: pr_pgid, nop: false, sr: Item::IdPgrp, width: 5, vendor: U98, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "pgrp", head: "PGRP", pr: pr_pgid, nop: false, sr: Item::IdPgrp, width: 5, vendor: LNX, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "pid", head: "PID", pr: pr_procs, nop: false, sr: Item::IdTgid, width: 5, vendor: U98, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "pidns", head: "PIDNS", pr: pr_pidns, nop: false, sr: Item::NsPid, width: 10, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "pmem", head: "%MEM", pr: pr_pmem, nop: false, sr: Item::VmRss, width: 4, vendor: XXX, flags: PO | RIGHT },
    Fmt { spec: "poip", head: "-", pr: pr_nop, nop: true, sr: Item::Noop, width: 1, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "policy", head: "POL", pr: pr_class, nop: false, sr: Item::SchedClass, width: 3, vendor: DEC, flags: TO | LEFT },
    Fmt { spec: "ppid", head: "PPID", pr: pr_ppid, nop: false, sr: Item::IdPpid, width: 5, vendor: U98, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "pri", head: "PRI", pr: pr_pri, nop: false, sr: Item::Priority, width: 3, vendor: XXX, flags: TO | RIGHT },
    Fmt { spec: "pri_api", head: "API", pr: pr_pri_api, nop: false, sr: Item::Priority, width: 3, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "pri_bar", head: "BAR", pr: pr_pri_bar, nop: false, sr: Item::Priority, width: 3, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "pri_baz", head: "BAZ", pr: pr_pri_baz, nop: false, sr: Item::Priority, width: 3, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "pri_foo", head: "FOO", pr: pr_pri_foo, nop: false, sr: Item::Priority, width: 3, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "priority", head: "PRI", pr: pr_priority, nop: false, sr: Item::Priority, width: 3, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "prmgrp", head: "PRMGRP", pr: pr_nop, nop: true, sr: Item::Noop, width: 12, vendor: HPU, flags: PO | RIGHT },
    Fmt { spec: "prmid", head: "PRMID", pr: pr_nop, nop: true, sr: Item::Noop, width: 12, vendor: HPU, flags: PO | RIGHT },
    Fmt { spec: "project", head: "PROJECT", pr: pr_nop, nop: true, sr: Item::Noop, width: 12, vendor: SUN, flags: PO | LEFT} },
    Fmt { spec: "projid", head: "PROJID", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: SUN, flags: PO | RIGHT },
    Fmt { spec: "pset", head: "PSET", pr: pr_nop, nop: true, sr: Item::Noop, width: 4, vendor: DEC, flags: TO | RIGHT },
    Fmt { spec: "psr", head: "PSR", pr: pr_psr, nop: false, sr: Item::Processor, width: 3, vendor: DEC, flags: TO | RIGHT },
    Fmt { spec: "pss", head: "PSS", pr: pr_pss, nop: false, sr: Item::SmapPss, width: 5, vendor: XXX, flags: PO | RIGHT },
    Fmt { spec: "psxpri", head: "PPR", pr: pr_nop, nop: true, sr: Item::Noop, width: 3, vendor: DEC, flags: TO | RIGHT },
    Fmt { spec: "rbytes", head: "RBYTES", pr: pr_rbytes, nop: false, sr: Item::IoReadBytes, width: 5, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "rchars", head: "RCHARS", pr: pr_rchars, nop: false, sr: Item::IoReadChars, width: 5, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "re", head: "RE", pr: pr_nop, nop: true, sr: Item::Noop, width: 3, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "resident", head: "RES", pr: pr_nop, nop: true, sr: Item::MemResPgs, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "rgid", head: "RGID", pr: pr_rgid, nop: false, sr: Item::IdRgid, width: 5, vendor: XXX, flags: ET | RIGHT },
    Fmt { spec: "rgroup", head: "RGROUP", pr: pr_rgroup, nop: false, sr: Item::IdRgroup, width: 8, vendor: U98, flags: ET | USER },
    Fmt { spec: "rlink", head: "RLINK", pr: pr_nop, nop: true, sr: Item::Noop, width: 8, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "rops", head: "ROPS", pr: pr_rops, nop: false, sr: Item::IoReadOps, width: 5, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "rss", head: "RSS", pr: pr_rss, nop: false, sr: Item::VmRss, width: 5, vendor: XXX, flags: PO | RIGHT },
    Fmt { spec: "rssize", head: "RSS", pr: pr_rss, nop: false, sr: Item::VmRss, width: 5, vendor: DEC, flags: PO | RIGHT },
    Fmt { spec: "rsz", head: "RSZ", pr: pr_rss, nop: false, sr: Item::VmRss, width: 5, vendor: BSD, flags: PO | RIGHT },
    Fmt { spec: "rtprio", head: "RTPRIO", pr: pr_rtprio, nop: false, sr: Item::PriorityRt, width: 6, vendor: BSD, flags: TO | RIGHT },
    Fmt { spec: "ruid", head: "RUID", pr: pr_ruid, nop: false, sr: Item::IdRuid, width: 5, vendor: XXX, flags: ET | RIGHT },
    Fmt { spec: "ruser", head: "RUSER", pr: pr_ruser, nop: false, sr: Item::IdRuser, width: 8, vendor: U98, flags: ET | USER },
    Fmt { spec: "s", head: "S", pr: pr_s, nop: false, sr: Item::State, width: 1, vendor: SUN, flags: TO | LEFT },
    Fmt { spec: "sched", head: "SCH", pr: pr_sched, nop: false, sr: Item::SchedClass, width: 3, vendor: AIX, flags: TO | RIGHT },
    Fmt { spec: "scnt", head: "SCNT", pr: pr_nop, nop: true, sr: Item::Noop, width: 4, vendor: DEC, flags: AN | RIGHT },
    Fmt { spec: "scount", head: "SC", pr: pr_nop, nop: true, sr: Item::Noop, width: 4, vendor: AIX, flags: AN | RIGHT },
    Fmt { spec: "seat", head: "SEAT", pr: pr_sd_seat, nop: false, sr: Item::SdSeat, width: 11, vendor: LNX, flags: ET | LEFT },
    Fmt { spec: "sess", head: "SESS", pr: pr_sess, nop: false, sr: Item::IdSession, width: 5, vendor: XXX, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "session", head: "SESS", pr: pr_sess, nop: false, sr: Item::IdSession, width: 5, vendor: LNX, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "sgi_p", head: "P", pr: pr_sgi_p, nop: false, sr: Item::State, width: 1, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "sgi_rss", head: "RSS", pr: pr_rss, nop: false, sr: Item::VmRss, width: 4, vendor: LNX, flags: PO | LEFT },
    Fmt { spec: "sgid", head: "SGID", pr: pr_sgid, nop: false, sr: Item::IdSgid, width: 5, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "sgroup", head: "SGROUP", pr: pr_sgroup, nop: false, sr: Item::IdSgroup, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "share", head: "-", pr: pr_nop, nop: true, sr: Item::Noop, width: 1, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "sid", head: "SID", pr: pr_sess, nop: false, sr: Item::IdSession, width: 5, vendor: XXX, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "sig", head: "PENDING", pr: pr_sig, nop: false, sr: Item::Signals, width: 9, vendor: XXX, flags: ET | SIGNAL },
    Fmt { spec: "sig_block", head: "BLOCKED", pr: pr_sigmask, nop: false, sr: Item::Sigblocked, width: 9, vendor: LNX, flags: TO | SIGNAL },
    Fmt { spec: "sig_catch", head: "CATCHED", pr: pr_sigcatch, nop: false, sr: Item::Sigcatch, width: 9, vendor: LNX, flags: TO | SIGNAL },
    Fmt { spec: "sig_ignore", head: "IGNORED", pr: pr_sigignore, nop: false, sr: Item::Sigignore, width: 9, vendor: LNX, flags: TO | SIGNAL },
    Fmt { spec: "sig_pend", head: "SIGNAL", pr: pr_sig, nop: false, sr: Item::Signals, width: 9, vendor: LNX, flags: ET | SIGNAL },
    Fmt { spec: "sigcatch", head: "CAUGHT", pr: pr_sigcatch, nop: false, sr: Item::Sigcatch, width: 9, vendor: XXX, flags: TO | SIGNAL },
    Fmt { spec: "sigignore", head: "IGNORED", pr: pr_sigignore, nop: false, sr: Item::Sigignore, width: 9, vendor: XXX, flags: TO | SIGNAL },
    Fmt { spec: "sigmask", head: "BLOCKED", pr: pr_sigmask, nop: false, sr: Item::Sigblocked, width: 9, vendor: XXX, flags: TO | SIGNAL },
    Fmt { spec: "size", head: "SIZE", pr: pr_swapable, nop: false, sr: Item::VsizeBytes, width: 5, vendor: SCO, flags: PO | RIGHT },
    Fmt { spec: "sl", head: "SL", pr: pr_nop, nop: true, sr: Item::Noop, width: 3, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "slice", head: "SLICE", pr: pr_sd_slice, nop: false, sr: Item::SdSlice, width: 31, vendor: LNX, flags: ET | LEFT },
    Fmt { spec: "spid", head: "SPID", pr: pr_tasks, nop: false, sr: Item::IdPid, width: 5, vendor: SGI, flags: TO | PIDMAX | RIGHT },
    Fmt { spec: "stackp", head: "STACKP", pr: pr_stackp, nop: false, sr: Item::AddrStackStart, width: 16, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "start", head: "STARTED", pr: pr_start, nop: false, sr: Item::TicsBegan, width: 8, vendor: XXX, flags: ET | RIGHT },
    Fmt { spec: "start_code", head: "S_CODE", pr: pr_nop, nop: true, sr: Item::AddrCodeStart, width: 16, vendor: LNX, flags: PO | RIGHT} },
    Fmt { spec: "start_stack", head: "STACKP", pr: pr_stackp, nop: false, sr: Item::AddrStackStart, width: 16, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "start_time", head: "START", pr: pr_stime, nop: false, sr: Item::TicsBegan, width: 5, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "stat", head: "STAT", pr: pr_stat, nop: false, sr: Item::State, width: 4, vendor: BSD, flags: TO | LEFT },
    Fmt { spec: "state", head: "S", pr: pr_s, nop: false, sr: Item::State, width: 1, vendor: XXX, flags: TO | LEFT },
    Fmt { spec: "status", head: "STATUS", pr: pr_nop, nop: true, sr: Item::Noop, width: 6, vendor: DEC, flags: AN | RIGHT },
    Fmt { spec: "stime", head: "STIME", pr: pr_stime, nop: false, sr: Item::TicsBegan, width: 5, vendor: XXX, flags: ET | RIGHT },
    Fmt { spec: "suid", head: "SUID", pr: pr_suid, nop: false, sr: Item::IdSuid, width: 5, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "supgid", head: "SUPGID", pr: pr_supgid, nop: false, sr: Item::Supgids, width: 20, vendor: LNX, flags: PO | UNLIMITED },
    Fmt { spec: "supgrp", head: "SUPGRP", pr: pr_supgrp, nop: false, sr: Item::Supgroups, width: 40, vendor: LNX, flags: PO | UNLIMITED },
    Fmt { spec: "suser", head: "SUSER", pr: pr_suser, nop: false, sr: Item::IdSuser, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "svgid", head: "SVGID", pr: pr_sgid, nop: false, sr: Item::IdSgid, width: 5, vendor: XXX, flags: ET | RIGHT },
    Fmt { spec: "svgroup", head: "SVGROUP", pr: pr_sgroup, nop: false, sr: Item::IdSgroup, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "svuid", head: "SVUID", pr: pr_suid, nop: false, sr: Item::IdSuid, width: 5, vendor: XXX, flags: ET | RIGHT },
    Fmt { spec: "svuser", head: "SVUSER", pr: pr_suser, nop: false, sr: Item::IdSuser, width: 8, vendor: LNX, flags: ET | USER },
    Fmt { spec: "systime", head: "SYSTEM", pr: pr_nop, nop: true, sr: Item::Noop, width: 6, vendor: DEC, flags: ET | RIGHT },
    Fmt { spec: "sz", head: "SZ", pr: pr_sz, nop: false, sr: Item::VmSize, width: 5, vendor: HPU, flags: PO | RIGHT },
    Fmt { spec: "taskid", head: "TASKID", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: SUN, flags: TO | PIDMAX | RIGHT} },
    Fmt { spec: "tdev", head: "TDEV", pr: pr_nop, nop: true, sr: Item::Noop, width: 4, vendor: XXX, flags: AN | RIGHT },
    Fmt { spec: "tgid", head: "TGID", pr: pr_procs, nop: false, sr: Item::IdTgid, width: 5, vendor: LNX, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "thcount", head: "THCNT", pr: pr_nlwp, nop: false, sr: Item::Nlwp, width: 5, vendor: AIX, flags: PO | RIGHT },
    Fmt { spec: "tid", head: "TID", pr: pr_tasks, nop: false, sr: Item::IdPid, width: 5, vendor: AIX, flags: TO | PIDMAX | RIGHT },
    Fmt { spec: "time", head: "TIME", pr: pr_time, nop: false, sr: Item::TimeAll, width: 8, vendor: U98, flags: ET | RIGHT },
    Fmt { spec: "timens", head: "TIMENS", pr: pr_timens, nop: false, sr: Item::NsTime, width: 10, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "timeout", head: "TMOUT", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: LNX, flags: AN | RIGHT} },
    Fmt { spec: "times", head: "TIME", pr: pr_times, nop: false, sr: Item::TimeAll, width: 8, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "tmout", head: "TMOUT", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: LNX, flags: AN | RIGHT} },
    Fmt { spec: "tname", head: "TTY", pr: pr_tty8, nop: false, sr: Item::TtyName, width: 8, vendor: DEC, flags: PO | LEFT },
    Fmt { spec: "tpgid", head: "TPGID", pr: pr_tpgid, nop: false, sr: Item::IdTpgid, width: 5, vendor: XXX, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "trs", head: "TRS", pr: pr_trs, nop: false, sr: Item::VsizeBytes, width: 4, vendor: AIX, flags: PO | RIGHT },
    Fmt { spec: "trss", head: "TRSS", pr: pr_trs, nop: false, sr: Item::VsizeBytes, width: 4, vendor: BSD, flags: PO | RIGHT },
    Fmt { spec: "tsess", head: "TSESS", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: BSD, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "tsession", head: "TSESS", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: DEC, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "tsid", head: "TSID", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: BSD, flags: PO | PIDMAX | RIGHT },
    Fmt { spec: "tsig", head: "PENDING", pr: pr_tsig, nop: false, sr: Item::Sigpending, width: 9, vendor: BSD, flags: ET | SIGNAL },
    Fmt { spec: "tsiz", head: "TSIZ", pr: pr_tsiz, nop: false, sr: Item::VsizeBytes, width: 4, vendor: BSD, flags: PO | RIGHT },
    Fmt { spec: "tt", head: "TT", pr: pr_tty8, nop: false, sr: Item::TtyName, width: 8, vendor: BSD, flags: PO | LEFT },
    Fmt { spec: "tty", head: "TT", pr: pr_tty8, nop: false, sr: Item::TtyName, width: 8, vendor: U98, flags: PO | LEFT },
    Fmt { spec: "tty4", head: "TTY", pr: pr_tty4, nop: false, sr: Item::TtyName, width: 4, vendor: LNX, flags: PO | LEFT },
    Fmt { spec: "tty8", head: "TTY", pr: pr_tty8, nop: false, sr: Item::TtyName, width: 8, vendor: LNX, flags: PO | LEFT },
    Fmt { spec: "u_procp", head: "UPROCP", pr: pr_nop, nop: true, sr: Item::Noop, width: 6, vendor: DEC, flags: AN | RIGHT },
    Fmt { spec: "ucmd", head: "CMD", pr: pr_comm, nop: false, sr: Item::Cmd, width: 15, vendor: DEC, flags: PO | UNLIMITED },
    Fmt { spec: "ucomm", head: "COMMAND", pr: pr_comm, nop: false, sr: Item::Cmd, width: 15, vendor: XXX, flags: PO | UNLIMITED },
    Fmt { spec: "uid", head: "UID", pr: pr_euid, nop: false, sr: Item::IdEuid, width: 5, vendor: XXX, flags: ET | RIGHT },
    Fmt { spec: "uid_hack", head: "UID", pr: pr_euser, nop: false, sr: Item::IdEuser, width: 8, vendor: XXX, flags: ET | USER },
    Fmt { spec: "umask", head: "UMASK", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: DEC, flags: AN | RIGHT },
    Fmt { spec: "uname", head: "USER", pr: pr_euser, nop: false, sr: Item::IdEuser, width: 8, vendor: DEC, flags: ET | USER },
    Fmt { spec: "unit", head: "UNIT", pr: pr_sd_unit, nop: false, sr: Item::SdUnit, width: 31, vendor: LNX, flags: ET | LEFT },
    Fmt { spec: "upr", head: "UPR", pr: pr_nop, nop: true, sr: Item::Noop, width: 3, vendor: BSD, flags: TO | RIGHT },
    Fmt { spec: "uprocp", head: "UPROCP", pr: pr_nop, nop: true, sr: Item::Noop, width: 8, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "user", head: "USER", pr: pr_euser, nop: false, sr: Item::IdEuser, width: 8, vendor: U98, flags: ET | USER },
    Fmt { spec: "userns", head: "USERNS", pr: pr_userns, nop: false, sr: Item::NsUser, width: 10, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "usertime", head: "USER", pr: pr_nop, nop: true, sr: Item::Noop, width: 4, vendor: DEC, flags: ET | RIGHT },
    Fmt { spec: "usrpri", head: "UPR", pr: pr_nop, nop: true, sr: Item::Noop, width: 3, vendor: DEC, flags: TO | RIGHT },
    Fmt { spec: "uss", head: "USS", pr: pr_uss, nop: false, sr: Item::SmapPrvTotal, width: 5, vendor: XXX, flags: PO | RIGHT },
    Fmt { spec: "util", head: "C", pr: pr_c, nop: false, sr: Item::Utilization, width: 2, vendor: SGI, flags: ET | RIGHT} },
    Fmt { spec: "utime", head: "UTIME", pr: pr_nop, nop: true, sr: Item::TicsUser, width: 6, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "utsns", head: "UTSNS", pr: pr_utsns, nop: false, sr: Item::NsUts, width: 10, vendor: LNX, flags: ET | RIGHT },
    Fmt { spec: "uunit", head: "UUNIT", pr: pr_sd_uunit, nop: false, sr: Item::SdUunit, width: 31, vendor: LNX, flags: ET | LEFT },
    Fmt { spec: "vm_data", head: "DATA", pr: pr_nop, nop: true, sr: Item::VmData, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "vm_exe", head: "EXE", pr: pr_nop, nop: true, sr: Item::VmExe, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "vm_lib", head: "LIB", pr: pr_nop, nop: true, sr: Item::VmLib, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "vm_lock", head: "LCK", pr: pr_nop, nop: true, sr: Item::VmRssLocked, width: 3, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "vm_stack", head: "STACK", pr: pr_nop, nop: true, sr: Item::VmStack, width: 5, vendor: LNX, flags: PO | RIGHT },
    Fmt { spec: "vsize", head: "VSZ", pr: pr_vsz, nop: false, sr: Item::VsizeBytes, width: 6, vendor: DEC, flags: PO | RIGHT },
    Fmt { spec: "vsz", head: "VSZ", pr: pr_vsz, nop: false, sr: Item::VmSize, width: 6, vendor: U98, flags: PO | RIGHT },
    Fmt { spec: "wbytes", head: "WBYTES", pr: pr_wbytes, nop: false, sr: Item::IoWriteBytes, width: 5, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "wcbytes", head: "WCBYTES", pr: pr_wcbytes, nop: false, sr: Item::IoWriteCbytes, width: 5, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "wchan", head: "WCHAN", pr: pr_wchan, nop: false, sr: Item::WchanName, width: 6, vendor: XXX, flags: TO | WCHAN },
    Fmt { spec: "wchars", head: "WCHARS", pr: pr_wchars, nop: false, sr: Item::IoWriteChars, width: 5, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "wname", head: "WCHAN", pr: pr_wchan, nop: false, sr: Item::WchanName, width: 6, vendor: SGI, flags: TO | WCHAN },
    Fmt { spec: "wops", head: "WOPS", pr: pr_wops, nop: false, sr: Item::IoWriteOps, width: 5, vendor: LNX, flags: TO | RIGHT },
    Fmt { spec: "xstat", head: "XSTAT", pr: pr_nop, nop: true, sr: Item::Noop, width: 5, vendor: BSD, flags: AN | RIGHT },
    Fmt { spec: "zone", head: "ZONE", pr: pr_context, nop: false, sr: Item::IdTgid, width: 31, vendor: SUN, flags: ET | LEFT} },
    Fmt { spec: "zoneid", head: "ZONEID", pr: pr_nop, nop: true, sr: Item::Noop, width: 31, vendor: SUN, flags: ET | RIGHT} },
    Fmt { spec: "~", head: "-", pr: pr_nop, nop: true, sr: Item::Noop, width: 1, vendor: LNX, flags: AN | RIGHT} },
];

/// `macro_array` do output.c (macros de formato que expandem em várias colunas).
pub static MACRO_ARRAY: &[(&str, &str)] = &[
    ("DFMT", "pid,tname,state,cputime,cmd"),
    ("DefBSD", "pid,tname,stat,bsdtime,args"),
    ("DefSysV", "pid,tname,time,cmd"),
    ("END_BSD", "state,tname,cputime,comm"),
    ("END_SYS5", "state,tname,time,command"),
    ("F5FMT", "uname,pid,ppid,c,start,tname,time,cmd"),
    ("FB_", "pid,tt,stat,time,command"),
    ("FB_j", "user,pid,ppid,pgid,sess,jobc,stat,tt,time,command"),
    ("FB_l", "uid,pid,ppid,cpu,pri,nice,vsz,rss,wchan,stat,tt,time,command"),
    ("FB_u", "user,pid,pcpu,pmem,vsz,rss,tt,stat,start,time,command"),
    ("FB_v", "pid,stat,time,sl,re,pagein,vsz,rss,lim,tsiz,pcpu,pmem,command"),
    ("FD_", "pid,tty,time,comm"),
    ("FD_f", "user,pid,ppid,start_time,tty,time,comm"),
    ("FD_fj", "user,pid,ppid,start_time,tty,time,pgid,sid,comm"),
    ("FD_j", "pid,tty,time,pgid,sid,comm"),
    ("FD_l", "flags,state,uid,pid,ppid,priority,nice,vsz,wchan,tty,time,comm"),
    ("FD_lj", "flags,state,uid,pid,ppid,priority,nice,vsz,wchan,tty,time,pgid,sid,comm"),
    ("FL5FMT", "f,state,uid,pid,ppid,pcpu,pri,nice,rss,wchan,start,time,command"),
    ("FLASK_context", "pid,context,command"),
    ("HP_", "pid,tty,time,comm"),
    ("HP_f", "user,pid,ppid,cpu,stime,tty,time,args"),
    ("HP_fl", "flags,state,user,pid,ppid,cpu,intpri,nice,addr,sz,wchan,stime,tty,time,args"),
    ("HP_l", "flags,state,uid,pid,ppid,cpu,intpri,nice,addr,sz,wchan,tty,time,comm"),
    ("J390", "pid,sid,pgrp,tname,atime,args"),
    ("JFMT", "user,pid,ppid,pgid,sess,jobc,state,tname,cputime,command"),
    ("L5FMT", "f,state,uid,pid,ppid,c,pri,nice,addr,sz,wchan,tt,time,ucmd"),
    ("LFMT", "uid,pid,ppid,cp,pri,nice,vsz,rss,wchan,state,tname,cputime,command"),
    ("OL_X", "pid,start_stack,esp,eip,timeout,alarm,stat,tname,bsdtime,args"),
    ("OL_j", "ppid,pid,pgid,sid,tname,tpgid,stat,uid,bsdtime,args"),
    ("OL_l", "flags,uid,pid,ppid,priority,nice,vsz,rss,wchan,stat,tname,bsdtime,args"),
    ("OL_m", "pid,tname,majflt,minflt,m_trs,m_drs,m_size,m_swap,rss,m_share,vm_lib,m_dt,args"),
    ("OL_s", "uid,pid,pending,sig_block,sig_ignore,caught,stat,tname,bsdtime,args"),
    ("OL_u", "user,pid,pcpu,pmem,vsz,rss,tname,stat,start_time,bsdtime,args"),
    ("OL_v", "pid,tname,stat,bsdtime,maj_flt,m_trs,m_drs,rss,pmem,args"),
    ("RD_", "pid,tname,state,bsdtime,comm"),
    ("RD_f", "uid,pid,ppid,start_time,tname,bsdtime,args"),
    ("RD_fj", "uid,pid,ppid,start_time,tname,bsdtime,pgid,sid,args"),
    ("RD_j", "pid,tname,state,bsdtime,pgid,sid,comm"),
    ("RD_l", "flags,state,uid,pid,ppid,priority,nice,wchan,tname,bsdtime,comm"),
    ("RD_lj", "flags,state,uid,pid,ppid,priority,nice,wchan,tname,bsdtime,pgid,sid,comm"),
    ("RUSAGE", "minflt,majflt,nswap,inblock,oublock,msgsnd,msgrcv,nsigs,nvcsw,nivcsw"),
    ("SCHED", "user,pcpu,pri,usrpri,nice,psxpri,psr,policy,pset"),
    ("SFMT", "uid,pid,cursig,sig,sigmask,sigignore,sigcatch,stat,tname,command"),
    ("Std_f", "uid_hack,pid,ppid,c,stime,tname,time,cmd"),
    ("Std_fl", "f,s,uid_hack,pid,ppid,c,opri,ni,addr,sz,wchan,stime,tname,time,cmd"),
    ("Std_l", "f,s,uid,pid,ppid,c,opri,ni,addr,sz,wchan,tname,time,ucmd"),
    ("THREAD", "user,pcpu,pri,scnt,wchan,usertime,systime"),
    ("UFMT", "uname,pid,pcpu,pmem,vsz,rss,tt,state,start,time,command"),
    ("VFMT", "pid,tt,state,time,sl,pagein,vsz,rss,pcpu,pmem,command"),
    ("~", "~"),
];
