//! Constantes extraídas de pragma_h (codegen do material de consulta em legacy/).
#![allow(unused_imports)]
use super::*;
pub const PRAG_TYP_ACTIVATE_EXTENSIONS: u8 = 0;
pub const PRAG_TYP_ANALYSIS_LIMIT: u8 = 1;
pub const PRAG_TYP_HEADER_VALUE: u8 = 2;
pub const PRAG_TYP_AUTO_VACUUM: u8 = 3;
pub const PRAG_TYP_FLAG: u8 = 4;
pub const PRAG_TYP_BUSY_TIMEOUT: u8 = 5;
pub const PRAG_TYP_CACHE_SIZE: u8 = 6;
pub const PRAG_TYP_CACHE_SPILL: u8 = 7;
pub const PRAG_TYP_CASE_SENSITIVE_LIKE: u8 = 8;
pub const PRAG_TYP_COLLATION_LIST: u8 = 9;
pub const PRAG_TYP_COMPILE_OPTIONS: u8 = 10;
pub const PRAG_TYP_DATA_STORE_DIRECTORY: u8 = 11;
pub const PRAG_TYP_DATABASE_LIST: u8 = 12;
pub const PRAG_TYP_DEFAULT_CACHE_SIZE: u8 = 13;
pub const PRAG_TYP_ENCODING: u8 = 14;
pub const PRAG_TYP_FOREIGN_KEY_CHECK: u8 = 15;
pub const PRAG_TYP_FOREIGN_KEY_LIST: u8 = 16;
pub const PRAG_TYP_FUNCTION_LIST: u8 = 17;
pub const PRAG_TYP_HARD_HEAP_LIMIT: u8 = 18;
pub const PRAG_TYP_INCREMENTAL_VACUUM: u8 = 19;
pub const PRAG_TYP_INDEX_INFO: u8 = 20;
pub const PRAG_TYP_INDEX_LIST: u8 = 21;
pub const PRAG_TYP_INTEGRITY_CHECK: u8 = 22;
pub const PRAG_TYP_JOURNAL_MODE: u8 = 23;
pub const PRAG_TYP_JOURNAL_SIZE_LIMIT: u8 = 24;
pub const PRAG_TYP_LOCK_PROXY_FILE: u8 = 25;
pub const PRAG_TYP_LOCKING_MODE: u8 = 26;
pub const PRAG_TYP_PAGE_COUNT: u8 = 27;
pub const PRAG_TYP_MMAP_SIZE: u8 = 28;
pub const PRAG_TYP_MODULE_LIST: u8 = 29;
pub const PRAG_TYP_OPTIMIZE: u8 = 30;
pub const PRAG_TYP_PAGE_SIZE: u8 = 31;
pub const PRAG_TYP_PRAGMA_LIST: u8 = 32;
pub const PRAG_TYP_SECURE_DELETE: u8 = 33;
pub const PRAG_TYP_SHRINK_MEMORY: u8 = 34;
pub const PRAG_TYP_SOFT_HEAP_LIMIT: u8 = 35;
pub const PRAG_TYP_SYNCHRONOUS: u8 = 36;
pub const PRAG_TYP_TABLE_INFO: u8 = 37;
pub const PRAG_TYP_TABLE_LIST: u8 = 38;
pub const PRAG_TYP_TEMP_STORE: u8 = 39;
pub const PRAG_TYP_TEMP_STORE_DIRECTORY: u8 = 40;
pub const PRAG_TYP_THREADS: u8 = 41;
pub const PRAG_TYP_WAL_AUTOCHECKPOINT: u8 = 42;
pub const PRAG_TYP_WAL_CHECKPOINT: u8 = 43;
pub const PRAG_TYP_LOCK_STATUS: u8 = 44;
pub const PRAG_TYP_STATS: u8 = 45;
pub const PRAG_FLG_NEED_SCHEMA: u8 = 0x01; // Força carregamento de esquema antes de executar
pub const PRAG_FLG_NO_COLUMNS: u8 = 0x02; // OP_ResultRow chamado com zero colunas
pub const PRAG_FLG_NO_COLUMNS1: u8 = 0x04; // Zero colunas se o argumento do lado direito estiver presente
pub const PRAG_FLG_READ_ONLY: u8 = 0x08; // HEADER_VALUE somente leitura
pub const PRAG_FLG_RESULT0: u8 = 0x10; // Atua como consulta quando não há argumento
pub const PRAG_FLG_RESULT1: u8 = 0x20; // Atua como consulta quando há um argumento
pub const PRAG_FLG_SCHEMA_OPT: u8 = 0x40; // Esquema restringe a busca de nome se presente
pub const PRAG_FLG_SCHEMA_REQ: u8 = 0x80; // Esquema obrigatório; "main" é o padrão
