[package]
name = "shell"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
description = "O bash do pseudo-linus (programas bash e sh): interpretador nosso sobre um fork do brush-parser"

[dependencies]
sysabi = { workspace = true }
ul-common = { workspace = true }
brush-parser = { path = "vendor/brush-parser" }
regex-posix = { workspace = true }
stacker = "0.1.17"

[dev-dependencies]
sysabi = { workspace = true, features = ["testkit"] }
pl-testing = { path = "../pl-testing" }

[lints]
workspace = true
