//! Gerado por `scripts/gen-plural-range-end.js` (bun 1.4.2, ICU completo). Não editar à mão.
//!
//! Por locale, os pares de categorias (início e fim) do `selectRange` cujo resultado é a categoria final: linhas
//! do CLDR que o icu4x omite. Só há entrada para a língua com pares e para a variante de região ou escrita que
//! se comporta diferente da língua (lista possivelmente vazia, que encobre a da língua). Ordenado por locale,
//! para busca binária.

pub const CARDINAL: &[(&str, &[&str])] = &[
    ("ak", &["other-one"]),
    ("aka", &["other-one"]),
    ("am", &["one-one"]),
    ("amh", &["one-one"]),
    ("ar", &["zero-few", "zero-many", "one-few", "one-many", "two-few", "two-many", "few-few", "few-many", "many-few", "many-many", "other-few", "other-many"]),
    ("ara", &["zero-few", "zero-many", "one-few", "one-many", "two-few", "two-many", "few-few", "few-many", "many-few", "many-many", "other-few", "other-many"]),
    ("as", &["one-one"]),
    ("asm", &["one-one"]),
    ("az", &["other-one"]),
    ("aze", &["other-one"]),
    ("be", &["many-many", "many-one", "many-few", "one-many", "one-one", "one-few", "few-many", "few-one", "few-few", "other-many", "other-one", "other-few"]),
    ("bel", &["many-many", "many-one", "many-few", "one-many", "one-one", "one-few", "few-many", "few-one", "few-few", "other-many", "other-one", "other-few"]),
    ("ben", &["one-one"]),
    ("bn", &["one-one"]),
    ("bos", &["other-one", "other-few", "one-one", "one-few", "few-one", "few-few"]),
    ("bs", &["other-one", "other-few", "one-one", "one-few", "few-one", "few-few"]),
    ("ces", &["other-one", "other-few", "other-many", "one-few", "one-many", "few-few", "few-many", "many-one", "many-few", "many-many"]),
    ("cs", &["other-one", "other-few", "other-many", "one-few", "one-many", "few-few", "few-many", "many-one", "many-few", "many-many"]),
    ("cy", &["zero-one", "zero-two", "zero-few", "zero-many", "one-two", "one-few", "one-many", "two-few", "two-many", "few-many", "other-one", "other-two", "other-few", "other-many"]),
    ("cym", &["zero-one", "zero-two", "zero-few", "zero-many", "one-two", "one-few", "one-many", "two-few", "two-many", "few-many", "other-one", "other-two", "other-few", "other-many"]),
    ("da", &["other-one", "one-one"]),
    ("dan", &["other-one", "one-one"]),
    ("de", &["other-one"]),
    ("deu", &["other-one"]),
    ("el", &["other-one"]),
    ("ell", &["other-one"]),
    ("fa", &["other-one"]),
    ("fas", &["other-one"]),
    ("fil", &["one-one", "other-one"]),
    ("fr", &["one-one"]),
    ("fra", &["one-one"]),
    ("ga", &["other-one", "other-two", "other-few", "other-many", "one-two", "one-few", "one-many", "two-few", "two-many", "few-few", "few-many", "many-many"]),
    ("gl", &["other-one"]),
    ("gle", &["other-one", "other-two", "other-few", "other-many", "one-two", "one-few", "one-many", "two-few", "two-many", "few-few", "few-many", "many-many"]),
    ("glg", &["other-one"]),
    ("gsw", &["other-one"]),
    ("gu", &["one-one"]),
    ("guj", &["one-one"]),
    ("hi", &["one-one"]),
    ("hin", &["one-one"]),
    ("hr", &["other-one", "other-few", "one-one", "one-few", "few-one", "few-few"]),
    ("hrv", &["other-one", "other-few", "one-one", "one-few", "few-one", "few-few"]),
    ("hu", &["other-one"]),
    ("hun", &["other-one"]),
    ("hy", &["one-one"]),
    ("hye", &["one-one"]),
    ("is", &["other-one", "one-one"]),
    ("isl", &["other-one", "one-one"]),
    ("it", &["other-one"]),
    ("ita", &["other-one"]),
    ("kan", &["one-one"]),
    ("kaz", &["other-one"]),
    ("kir", &["other-one"]),
    ("kk", &["other-one"]),
    ("kn", &["one-one"]),
    ("ky", &["other-one"]),
    ("lav", &["zero-one", "one-one", "other-one"]),
    ("lij", &["other-one"]),
    ("lit", &["other-one", "other-few", "other-many", "one-one", "one-few", "one-many", "few-one", "few-few", "few-many", "many-one", "many-few", "many-many"]),
    ("lt", &["other-one", "other-few", "other-many", "one-one", "one-few", "one-many", "few-one", "few-few", "few-many", "many-one", "many-few", "many-many"]),
    ("lv", &["zero-one", "one-one", "other-one"]),
    ("mal", &["other-one"]),
    ("mar", &["one-one"]),
    ("ml", &["other-one"]),
    ("mn", &["other-one"]),
    ("mo", &["few-few", "one-few", "other-few"]),
    ("mol", &["few-few", "one-few", "other-few"]),
    ("mon", &["other-one"]),
    ("mr", &["one-one"]),
    ("ne", &["other-one"]),
    ("nep", &["other-one"]),
    ("nl", &["other-one"]),
    ("nld", &["other-one"]),
    ("or", &["other-one"]),
    ("ori", &["other-one"]),
    ("pa", &["one-one", "other-one"]),
    ("pan", &["one-one", "other-one"]),
    ("pl", &["many-many", "many-one", "many-few", "one-many", "one-few", "few-many", "few-few", "other-many", "other-one", "other-few"]),
    ("pol", &["many-many", "many-one", "many-few", "one-many", "one-few", "few-many", "few-few", "other-many", "other-one", "other-few"]),
    ("por", &["one-one"]),
    ("por-PT", &["one-one"]),
    ("ps", &["one-one"]),
    ("pt", &["one-one"]),
    ("pt-PT", &["one-one"]),
    ("pus", &["one-one"]),
    ("ro", &["few-few", "one-few", "other-few"]),
    ("ron", &["few-few", "one-few", "other-few"]),
    ("ru", &["many-many", "many-one", "many-few", "one-many", "one-one", "one-few", "few-many", "few-one", "few-few", "other-many", "other-one", "other-few"]),
    ("rus", &["many-many", "many-one", "many-few", "one-many", "one-one", "one-few", "few-many", "few-one", "few-few", "other-many", "other-one", "other-few"]),
    ("sc", &["other-one"]),
    ("scn", &["other-one"]),
    ("sd", &["other-one"]),
    ("si", &["one-one"]),
    ("sin", &["one-one"]),
    ("sk", &["other-one", "other-few", "other-many", "one-few", "one-many", "few-few", "few-many", "many-one", "many-few", "many-many"]),
    ("sl", &["other-two", "other-few", "one-two", "one-few", "two-two", "two-few", "few-two", "few-few"]),
    ("slk", &["other-one", "other-few", "other-many", "one-few", "one-many", "few-few", "few-many", "many-one", "many-few", "many-many"]),
    ("slv", &["other-two", "other-few", "one-two", "one-few", "two-two", "two-few", "few-two", "few-few"]),
    ("snd", &["other-one"]),
    ("sq", &["other-one"]),
    ("sqi", &["other-one"]),
    ("sr", &["other-one", "other-few", "one-one", "one-few", "few-one", "few-few"]),
    ("srd", &["other-one"]),
    ("srp", &["other-one", "other-few", "one-one", "one-few", "few-one", "few-few"]),
    ("sw", &["other-one"]),
    ("swa", &["other-one"]),
    ("ta", &["other-one"]),
    ("tam", &["other-one"]),
    ("te", &["other-one"]),
    ("tel", &["other-one"]),
    ("tk", &["other-one"]),
    ("tr", &["other-one"]),
    ("tuk", &["other-one"]),
    ("tur", &["other-one"]),
    ("ug", &["other-one"]),
    ("uig", &["other-one"]),
    ("uk", &["many-many", "many-one", "many-few", "one-many", "one-one", "one-few", "few-many", "few-one", "few-few", "other-many", "other-one", "other-few"]),
    ("ukr", &["many-many", "many-one", "many-few", "one-many", "one-one", "one-few", "few-many", "few-one", "few-few", "other-many", "other-one", "other-few"]),
    ("uz", &["other-one"]),
    ("uzb", &["other-one"]),
    ("zu", &["one-one"]),
    ("zul", &["one-one"]),
];

pub const ORDINAL: &[(&str, &[&str])] = &[
    ("as", &["one-one"]),
    ("asm", &["one-one"]),
    ("az", &["other-one"]),
    ("aze", &["other-one"]),
    ("be", &["other-few", "few-few"]),
    ("bel", &["other-few", "few-few"]),
    ("ben", &["one-one"]),
    ("bn", &["one-one"]),
    ("cy", &["zero-one", "zero-two", "zero-few", "zero-many", "one-two", "one-few", "one-many", "two-few", "two-many", "few-many", "other-one", "other-two", "other-few", "other-many"]),
    ("cym", &["zero-one", "zero-two", "zero-few", "zero-many", "one-two", "one-few", "one-many", "two-few", "two-many", "few-many", "other-one", "other-two", "other-few", "other-many"]),
    ("fil", &["other-one", "one-one"]),
    ("fr", &["one-one"]),
    ("fra", &["one-one"]),
    ("ga", &["other-one"]),
    ("gle", &["other-one"]),
    ("gu", &["one-one"]),
    ("guj", &["one-one"]),
    ("hi", &["one-one"]),
    ("hin", &["one-one"]),
    ("hu", &["other-one"]),
    ("hun", &["other-one"]),
    ("hy", &["one-one"]),
    ("hye", &["one-one"]),
    ("mar", &["one-one"]),
    ("mr", &["one-one"]),
    ("ne", &["other-one"]),
    ("nep", &["other-one"]),
    ("or", &["other-one"]),
    ("ori", &["other-one"]),
    ("sq", &["other-one"]),
    ("sqi", &["other-one"]),
    ("uk", &["other-few", "few-few"]),
    ("ukr", &["other-few", "few-few"]),
];
