// Sétima fatia do porte de `JSBigInt.cpp`: as linhas 6143 a 6660 (`calculateMaximumCharactersRequired`,
// `toStringBasePowerOfTwo`, o `ToStringFormatter` de divisão e conquista e `toStringGeneric`).
// `maxBitsPerCharTable`, `bitsPerCharTableShift` e `bitsPerCharTableMultiplier` já vêm da fatia 6.
//
// Esta fatia é incluída por `include!` em `js_big_int.rs` e compartilha o escopo dele.
//
// Dependências de trechos ainda não portados (linhas 2893 a 3800 do C++), assumidas com as
// assinaturas abaixo, todas como funções associadas de `JSBigInt` salvo indicação:
// - `divide_single(q: &mut [Digit], remainder: &mut Digit, a: &[Digit], b: Digit) -> &mut [Digit]`
// - `divide_schoolbook(q: &mut [Digit], r: &mut [Digit], a: &[Digit], b: &[Digit],
//   interrupt: Option<&mut InterruptCheck>) -> (&mut [Digit], &mut [Digit])`
// - `left_shift(z: &mut [Digit], x: &[Digit], shift: u32) -> &mut [Digit]` e `right_shift` idem
// - `right_shift_zero_padded(z: &mut [Digit], x: &[Digit], shift: u32)`
// - `invert(interrupt: &mut InterruptCheck, z: &mut [Digit], v: &[Digit], scratch: &mut [Digit])`
// - `divide_barrett(interrupt, q, r, a, b, inverse, scratch)` (a sobrecarga de sete argumentos)
// - funções livres `invert_scratch_space(n: usize) -> usize` e `divide_barrett_scratch_space(n)`.
//
// Desvios mecânicos de Rust seguro, sem efeito observável:
// - Os ponteiros `Latin1Character*` do `ToStringFormatter` viram índices no buffer de saída.
// - O `notFound` de `levelIndex` vira `None`.
// - Onde o C++ chama `leftShift`/`rightShift`/`rightShiftZeroPadded` com origem e destino
//   sobrepostos (em lugar), a origem é copiada antes, pois o empréstimo seguro não admite o alias.
// - Em `toStringGeneric` o `rest` que o C++ divide em lugar vira dois buffers que se alternam.
// - `JSString::MaxLength` é `StringImpl::MaxLength`.

/// `radixDigits`
const RADIX_DIGITS: &[u8; 36] = b"0123456789abcdefghijklmnopqrstuvwxyz";

/// `toStringFastThreshold` com `CPU(REGISTER64)`.
const TO_STRING_FAST_THRESHOLD: usize = 14;

/// `JSBigInt::ToStringFormatter::Level`
#[derive(Default)]
struct ToStringLevel {
    leading_zero_shift: u32,
    /// The number of characters generated by *each half* of this level.
    char_count: usize,
    divisor: Vec<Digit>,
    inverse: Vec<Digit>,
}

/// `JSBigInt::ToStringFormatter`
struct ToStringFormatter<'a, 'b> {
    interrupt: &'b mut InterruptCheck<'a>,
    digits: &'b [Digit],
    radix: u32,
    chunk_chars: u32,
    chunk_divisor: Digit,
    out: &'b mut [u8],
    out_pos: usize,
    /// Level i's divisor is the square of level i - 1's; the last one is the top level.
    levels: Vec<ToStringLevel>,
}

impl<'a, 'b> ToStringFormatter<'a, 'b> {
    fn new(interrupt: &'b mut InterruptCheck<'a>, digits: &'b [Digit], radix: u32, out: &'b mut [u8]) -> Self {
        assert!(!digits.is_empty() && *digits.last().unwrap() != 0);
        let max_bits_per_char = MAX_BITS_PER_CHAR_TABLE[radix as usize] as u32;
        let chunk_chars = DIGIT_BITS * BITS_PER_CHAR_TABLE_MULTIPLIER as u32 / max_bits_per_char;
        let chunk_divisor = digit_pow(radix as Digit, chunk_chars as Digit);
        // By construction of chunkChars, there can't have been overflow.
        assert!(chunk_divisor != 0);
        let out_pos = out.len();
        ToStringFormatter { interrupt, digits, radix, chunk_chars, chunk_divisor, out, out_pos, levels: Vec::new() }
    }

    /// `ToStringFormatter::result`: o índice onde começam os caracteres formatados (terminam no fim
    /// do buffer de saída).
    fn result_start(&self) -> usize {
        self.out_pos
    }

    fn create_levels(&mut self, target_bit_length: usize) {
        let mut base = ToStringLevel::default();
        base.char_count = self.chunk_chars as usize;
        base.divisor.push(self.chunk_divisor);
        self.levels.push(base);
        // We can stop creating levels when the next level's divisor, which is the square of the
        // current level's divisor, would be strictly bigger (in terms of its numeric value) than the
        // input we're formatting. Bit lengths are an imperfect predictor of numeric value, so we have
        // to be careful: aim for a strictly bigger bit length, and remember that squaring sometimes
        // doubles the bit length.
        let bit_length = |x: &[Digit]| x.len() * DIGIT_BITS as usize - x.last().unwrap().leading_zeros() as usize;
        while bit_length(&self.levels.last().unwrap().divisor) * 2 - 1 <= target_bit_length {
            let previous_index = self.levels.len() - 1;
            let mut next = ToStringLevel::default();
            next.char_count = self.levels[previous_index].char_count * 2;
            assert!(next.char_count < usize::MAX / 2);
            next.divisor = vec![0; self.levels[previous_index].divisor.len() * 2];
            {
                let previous = &self.levels[previous_index];
                JSBigInt::multiply_zero_padded(&mut *self.interrupt, &mut next.divisor, &previous.divisor, &previous.divisor);
            }
            if self.interrupt.interrupted() {
                return;
            }
            let normalized_len = normalize(&next.divisor).len();
            next.divisor.truncate(normalized_len);
            // Left-shifting the divisor must only happen after it's been used to compute the next
            // divisor.
            {
                let previous = &mut self.levels[previous_index];
                previous.leading_zero_shift = previous.divisor.last().unwrap().leading_zeros();
                let original = previous.divisor.clone();
                JSBigInt::left_shift(&mut previous.divisor, &original, previous.leading_zero_shift);
            }
            self.compute_inverse(previous_index, 0);
            if self.interrupt.interrupted() {
                return;
            }
            self.levels.push(next);
        }
        let top = self.levels.last_mut().unwrap();
        top.leading_zero_shift = top.divisor.last().unwrap().leading_zeros();
        let original = top.divisor.clone();
        JSBigInt::left_shift(&mut top.divisor, &original, top.leading_zero_shift);
        // Not computing the top level's inverse here so that it can take the input's length into
        // account to save some effort on inverse generation.
    }

    /// The top level might get by with a smaller inverse than we could maximally compute, so the
    /// caller should provide the dividend length.
    fn compute_inverse(&mut self, level_index: usize, dividend_length: usize) {
        let level = &mut self.levels[level_index];
        let mut inverse_length = level.divisor.len();
        if dividend_length != 0 {
            inverse_length = dividend_length - level.divisor.len();
            assert!(inverse_length <= level.divisor.len());
        }
        let mut scratch: Vec<Digit> = vec![0; invert_scratch_space(inverse_length)];
        level.inverse = vec![0; inverse_length + 1];
        let input = &level.divisor[level.divisor.len() - inverse_length..];
        JSBigInt::invert(&mut *self.interrupt, &mut level.inverse, input, &mut scratch);
        if self.interrupt.interrupted() {
            return;
        }
        assert!(*level.inverse.last().unwrap() == 0);
        level.inverse.truncate(inverse_length);
    }

    /// `ToStringFormatter::inverse`
    fn inverse(level: &ToStringLevel, dividend_length: usize) -> &[Digit] {
        assert!(!level.inverse.is_empty());
        let inverse_length = dividend_length - level.divisor.len();
        assert!(inverse_length <= level.inverse.len());
        &level.inverse[level.inverse.len() - inverse_length..]
    }

    fn run(&mut self) {
        let digits = self.digits;
        self.create_levels(digits.len() * DIGIT_BITS as usize - digits.last().unwrap().leading_zeros() as usize);
        if self.interrupt.interrupted() {
            return;
        }
        // The input is read-only, so the top level works on a copy it may shift in place.
        let mut input: Vec<Digit> = digits.to_vec();
        let top = Some(self.levels.len() - 1);
        self.out_pos = self.process_level(top, &mut input, self.out_pos, true, true);
    }

    /// When processing the last (most significant) digit, don't write leading zeros.
    fn basecase_last(&mut self, mut digit: Digit, mut out: usize) -> usize {
        loop {
            assert!(out > 0);
            out -= 1;
            self.out[out] = RADIX_DIGITS[(digit % self.radix as Digit) as usize];
            digit /= self.radix as Digit;
            if digit == 0 {
                break;
            }
        }
        out
    }

    /// Writes '0' characters right-to-left, starting at {out}-1, until the distance from
    /// {rightBoundary} to {out} equals the number of characters that the level is supposed to
    /// produce.
    fn fill_with_zeros(&mut self, level_index: Option<usize>, right_boundary: usize, mut out: usize, is_last_on_level: bool) -> usize {
        // Fill up with zeros up to the character count expected to be generated on this level;
        // unless this is the left edge of the result.
        if is_last_on_level {
            return out;
        }
        let chunk_chars = match level_index {
            None => self.chunk_chars as usize,
            Some(index) => self.levels[index].char_count * 2,
        };
        let end = right_boundary - chunk_chars;
        assert!(out >= end);
        while out > end {
            out -= 1;
            self.out[out] = b'0';
        }
        out
    }

    /// Formats {chunk} into the characters below {out}. {chunk} may be overwritten when
    /// {allow_in_place_shift} is set.
    fn process_level(&mut self, level_index: Option<usize>, chunk: &mut [Digit], mut out: usize, is_last_on_level: bool, allow_in_place_shift: bool) -> usize {
        // Step 0: if only one digit is left, bail out to the base case.
        let normalized_len = normalize(&*chunk).len();
        if normalized_len <= 1 {
            let right_boundary = out;
            if normalized_len == 1 {
                out = self.basecase_last(chunk[0], out);
            }
            return self.fill_with_zeros(level_index, right_boundary, out, is_last_on_level);
        }

        let index = level_index.expect("process_level sem nível com mais de um dígito");
        let next_level_index = if index != 0 { Some(index - 1) } else { None };
        let divisor_len = self.levels[index].divisor.len();

        // Step 1: If the chunk is guaranteed to remain smaller than the divisor even after
        // left-shifting, fall through to the next level immediately.
        if normalized_len < divisor_len {
            let right_boundary = out;
            out = self.process_level(next_level_index, chunk, out, is_last_on_level, allow_in_place_shift);
            return self.fill_with_zeros(level_index, right_boundary, out, is_last_on_level);
        }

        // Step 2: Prepare the chunk: shift it left to match the normalized divisor. This is done in
        // place when the caller allows it and the top digit has room, since both halves below are
        // allocated one digit longer than they need for that purpose.
        let shift = self.levels[index].leading_zero_shift;
        let mut shifted_storage: Vec<Digit> = Vec::new();
        let mut use_storage = false;
        let mut shifted_in_place = false;
        let shifted_len;
        if shift == 0 {
            shifted_len = normalized_len;
        } else if allow_in_place_shift && chunk[normalized_len - 1].leading_zeros() >= shift {
            shifted_len = normalized_len;
            let original = chunk[..normalized_len].to_vec();
            JSBigInt::left_shift(&mut chunk[..normalized_len], &original, shift);
            shifted_in_place = true;
        } else {
            shifted_storage = vec![0; normalized_len + 1];
            shifted_len = JSBigInt::left_shift(&mut shifted_storage, &chunk[..normalized_len], shift).len();
            use_storage = true;
        }
        let dividend_len = if use_storage { normalize(&shifted_storage[..shifted_len]).len() } else { normalize(&chunk[..shifted_len]).len() };
        // Check (now precisely) if the chunk is smaller than the divisor.
        let comparison = {
            let dividend = if use_storage { &shifted_storage[..dividend_len] } else { &chunk[..dividend_len] };
            JSBigInt::compare_digits(dividend, &self.levels[index].divisor)
        };
        if comparison != ComparisonResult::GreaterThan {
            let right_boundary = out;
            if comparison == ComparisonResult::LessThan {
                // If the chunk is strictly smaller than the divisor, we can process it directly on
                // the next level as the right half, and know that the left half is all '0'.
                // In case we shifted {chunk} in-place, we must undo that before the call.
                if shifted_in_place {
                    let original = chunk[..shifted_len].to_vec();
                    JSBigInt::right_shift(&mut chunk[..shifted_len], &original, shift);
                }
                out = self.process_level(next_level_index, chunk, out, is_last_on_level, allow_in_place_shift);
            } else {
                // If the chunk is equal to the divisor, we know that the right half is all '0', and
                // the left half is '...0001'.
                out = self.fill_with_zeros(next_level_index, right_boundary, out, false);
                assert!(out > 0);
                out -= 1;
                self.out[out] = b'1';
            }
            // In both cases, make sure the left half is fully written.
            return self.fill_with_zeros(level_index, right_boundary, out, is_last_on_level);
        }

        // Step 3: Allocate space for the results.
        // Allocate one extra digit so the next level can left-shift in-place.
        let mut right: Vec<Digit> = vec![0; divisor_len + 1];
        // Allocate one extra digit because divideBarrett requires it.
        let mut left: Vec<Digit> = vec![0; dividend_len - divisor_len + 1];

        // Step 4: Divide to split {dividend} into {left} and {right}.
        let inverse_length = dividend_len - divisor_len;
        if inverse_length == 0 {
            let dividend = if use_storage { &shifted_storage[..dividend_len] } else { &chunk[..dividend_len] };
            let (quotient_len, remainder_len) = {
                let (quotient, remainder) = JSBigInt::divide_schoolbook(&mut left, &mut right, dividend, &self.levels[index].divisor, Some(&mut *self.interrupt));
                (quotient.len(), remainder.len())
            };
            left[quotient_len..].fill(0);
            right[remainder_len..].fill(0);
        } else if divisor_len == 1 {
            let dividend = if use_storage { &shifted_storage[..dividend_len] } else { &chunk[..dividend_len] };
            let mut remainder: Digit = 0;
            let quotient_len = JSBigInt::divide_single(&mut left, &mut remainder, dividend, self.levels[index].divisor[0]).len();
            left[quotient_len..].fill(0);
            right[0] = remainder;
            right[1..].fill(0);
            self.interrupt.add_work(dividend_len);
        } else {
            let mut scratch: Vec<Digit> = vec![0; divide_barrett_scratch_space(dividend_len)];
            // The top level only computes its inverse when the dividend's length is known. Other
            // levels have precomputed theirs.
            if self.levels[index].inverse.is_empty() {
                self.compute_inverse(index, dividend_len);
            }
            if self.interrupt.interrupted() {
                return out;
            }
            let dividend = if use_storage { &shifted_storage[..dividend_len] } else { &chunk[..dividend_len] };
            let level = &self.levels[index];
            JSBigInt::divide_barrett(&mut *self.interrupt, &mut left, &mut right, dividend, &level.divisor, Self::inverse(level, dividend_len), &mut scratch);
        }
        if self.interrupt.interrupted() {
            return out;
        }
        let right_copy = right.clone();
        JSBigInt::right_shift_zero_padded(&mut right, &right_copy, shift);
        assert!(normalize(&left).len() <= divisor_len);

        // Step 5: Recurse.
        let char_count = self.levels[index].char_count;
        let end_of_right_part = self.process_level(next_level_index, &mut right, out, false, true);
        if self.interrupt.interrupted() {
            return out;
        }
        // The recursive calls are required and hence designed to write exactly as many characters as
        // their level is responsible for.
        assert!(end_of_right_part == out - char_count);
        self.process_level(next_level_index, &mut left, out - char_count, is_last_on_level, true)
    }
}

impl JSBigInt {
    /// `JSBigInt::calculateMaximumCharactersRequired`: compute (an overapproximation of) the length
    /// of the resulting string: divide bit length of the BigInt by bits representable per character.
    pub fn calculate_maximum_characters_required(length: u32, radix: u32, last_digit: Digit, sign: bool) -> u64 {
        let leading_zeros = last_digit.leading_zeros();

        let bit_length = length as usize * DIGIT_BITS as usize - leading_zeros as usize;

        // Maximum number of bits we can represent with one character. We'll use this to find an
        // appropriate chunk size below.
        let max_bits_per_char = MAX_BITS_PER_CHAR_TABLE[radix as usize];

        // For estimating result length, we have to be pessimistic and work with the minimum number
        // of bits one character can represent.
        let min_bits_per_char = max_bits_per_char - 1;

        // Perform the following computation with uint64_t to avoid overflows.
        let mut maximum_characters_required = bit_length as u64;
        maximum_characters_required *= BITS_PER_CHAR_TABLE_MULTIPLIER as u64;

        // Round up.
        maximum_characters_required += (min_bits_per_char - 1) as u64;
        maximum_characters_required /= min_bits_per_char as u64;
        maximum_characters_required += sign as u64;

        maximum_characters_required
    }

    /// `JSBigInt::toStringBasePowerOfTwo`
    pub fn to_string_base_power_of_two(vm: &crate::runtime::vm::VM, null_or_global_object_for_oom: Option<&dyn BigIntGlobalObject>, x: &JSBigInt, radix: u32) -> crate::wtf::text::wtf_string::String {
        assert!(crate::wtf::math_extras::has_one_bit_set(radix));
        assert!(radix >= 2 && radix <= 32);
        assert!(!x.is_zero());

        let length = x.length();
        let sign = x.sign();
        let bits_per_char = radix.trailing_zeros();
        let char_mask = (radix - 1) as Digit;
        // Compute the length of the resulting string: divide the bit length of the BigInt by the
        // number of bits representable per character (rounding up).
        let msd = x.digit(length - 1);
        let msd_leading_zeros = msd.leading_zeros();

        let bit_length = length as usize * DIGIT_BITS as usize - msd_leading_zeros as usize;
        let chars_required = (bit_length + bits_per_char as usize - 1) / bits_per_char as usize + sign as usize;

        if chars_required > crate::wtf::text::string_impl::MAX_LENGTH as usize {
            if let Some(global_object) = null_or_global_object_for_oom {
                global_object.throw_out_of_memory_error(vm, None);
            }
            return crate::wtf::text::wtf_string::null_string();
        }

        let mut result_string: Vec<u8> = vec![0; chars_required];
        let mut digit: Digit = 0;
        // Keeps track of how many unprocessed bits there are in {digit}.
        let mut available_bits: u32 = 0;
        let mut pos = chars_required as isize - 1;
        for i in 0..length - 1 {
            let new_digit = x.digit(i);
            // Take any leftover bits from the last iteration into account.
            let current = ((digit | (new_digit << available_bits)) & char_mask) as usize;
            result_string[pos as usize] = RADIX_DIGITS[current];
            pos -= 1;
            let consumed_bits = bits_per_char - available_bits;
            digit = new_digit >> consumed_bits;
            available_bits = DIGIT_BITS - consumed_bits;
            while available_bits >= bits_per_char {
                result_string[pos as usize] = RADIX_DIGITS[(digit & char_mask) as usize];
                pos -= 1;
                digit >>= bits_per_char;
                available_bits -= bits_per_char;
            }
        }
        // Take any leftover bits from the last iteration into account.
        let current = ((digit | (msd << available_bits)) & char_mask) as usize;
        result_string[pos as usize] = RADIX_DIGITS[current];
        pos -= 1;
        digit = msd >> (bits_per_char - available_bits);
        while digit != 0 {
            result_string[pos as usize] = RADIX_DIGITS[(digit & char_mask) as usize];
            pos -= 1;
            digit >>= bits_per_char;
        }

        if sign {
            result_string[pos as usize] = b'-';
            pos -= 1;
        }

        assert!(pos == -1);
        crate::wtf::text::wtf_string::String::adopt(result_string)
    }

    /// `JSBigInt::toStringGeneric`
    pub fn to_string_generic(vm: &crate::runtime::vm::VM, null_or_global_object_for_oom: Option<&dyn BigIntGlobalObject>, x: &JSBigInt, radix: u32) -> crate::wtf::text::wtf_string::String {
        let mut result_string: Vec<u8> = Vec::new();

        assert!(radix >= 2 && radix <= 36);
        assert!(!x.is_zero());

        let length = x.length();
        let sign = x.sign();

        let max_bits_per_char = MAX_BITS_PER_CHAR_TABLE[radix as usize] as u32;
        let maximum_characters_required = Self::calculate_maximum_characters_required(length, radix, x.digit(length - 1), sign);

        if maximum_characters_required > crate::wtf::text::string_impl::MAX_LENGTH as u64 {
            if let Some(global_object) = null_or_global_object_for_oom {
                global_object.throw_out_of_memory_error(vm, None);
            }
            return crate::wtf::text::wtf_string::null_string();
        }

        if length as usize >= TO_STRING_FAST_THRESHOLD {
            let mut buffer: Vec<u8> = vec![0; maximum_characters_required as usize];
            let mut vm_check = || vm.exception().is_some();
            let mut interrupt = InterruptCheck::new(if null_or_global_object_for_oom.is_some() {
                Some(&mut vm_check as &mut dyn FnMut() -> bool)
            } else {
                None
            });
            let start = {
                let mut formatter = ToStringFormatter::new(&mut interrupt, x.digits(), radix, &mut buffer);
                formatter.run();
                formatter.result_start()
            };
            if interrupt.interrupted() {
                return crate::wtf::text::wtf_string::null_string();
            }
            let end = buffer.len();
            assert!(start < end);
            // Remove leading zeroes.
            let mut leading_zeroes = 0;
            while start + leading_zeroes + 1 < end && buffer[start + leading_zeroes] == b'0' {
                leading_zeroes += 1;
            }
            let characters_start = start + leading_zeroes;
            let result_length = end - characters_start + sign as usize;
            buffer.copy_within(characters_start..end, sign as usize);
            if sign {
                buffer[0] = b'-';
            }
            buffer.truncate(result_length);
            return crate::wtf::text::wtf_string::String::adopt(buffer);
        }

        let mut last_digit: Digit;
        if length == 1 {
            last_digit = x.digit(0);
        } else {
            let chunk_chars = DIGIT_BITS * BITS_PER_CHAR_TABLE_MULTIPLIER as u32 / max_bits_per_char;
            let chunk_divisor = digit_pow(radix as Digit, chunk_chars as Digit);

            // By construction of chunkChars, there can't have been overflow.
            assert!(chunk_divisor != 0);

            // {rest} holds the part of the BigInt that we haven't looked at yet. Not to be confused
            // with "remainder"! In the first round, divide the input; from then on divide the rest.
            // O C++ divide o resto em lugar; aqui dois buffers se alternam.
            let mut rest: Vec<Digit> = vec![0; length as usize];
            let mut next_rest: Vec<Digit> = vec![0; length as usize];
            let mut dividend_len = 0;
            let mut first_round = true;
            loop {
                let mut chunk: Digit = 0;
                let quotient_len = if first_round {
                    JSBigInt::divide_single(&mut rest, &mut chunk, x.digits(), chunk_divisor).len()
                } else {
                    let quotient_len = JSBigInt::divide_single(&mut next_rest, &mut chunk, &rest[..dividend_len], chunk_divisor).len();
                    core::mem::swap(&mut rest, &mut next_rest);
                    quotient_len
                };
                first_round = false;

                for _ in 0..chunk_chars {
                    result_string.push(RADIX_DIGITS[(chunk % radix as Digit) as usize]);
                    chunk /= radix as Digit;
                }
                assert!(chunk == 0);

                // Update dividend to point to the quotient for next iteration. The quotient.size()
                // tells us how many digits are non-zero.
                dividend_len = normalize(&rest[..quotient_len]).len();
                if dividend_len <= 1 {
                    break;
                }
            }

            last_digit = if dividend_len == 0 { 0 } else { rest[0] };
        }

        loop {
            result_string.push(RADIX_DIGITS[(last_digit % radix as Digit) as usize]);
            last_digit /= radix as Digit;
            if last_digit == 0 {
                break;
            }
        }
        assert!(!result_string.is_empty());
        assert!(result_string.len() <= maximum_characters_required as usize);

        // Remove leading zeroes.
        let mut new_size_no_leading_zeroes = result_string.len();
        while new_size_no_leading_zeroes > 1 && result_string[new_size_no_leading_zeroes - 1] == b'0' {
            new_size_no_leading_zeroes -= 1;
        }

        result_string.truncate(new_size_no_leading_zeroes);

        if sign {
            result_string.push(b'-');
        }

        result_string.reverse();

        crate::wtf::text::wtf_string::String::adopt(result_string)
    }
}
