//! Tradução parcial de `runtime/Structure.h`: os campos de bits de `m_bitField`.
//!
//! O objeto `Structure` em si depende do heap e das tabelas de propriedade e fica para a camada do
//! heap; aqui entra só o que o bytecompiler consulta (as máscaras de `DEFINE_BITFIELD`).

/// `Structure`: no momento, só as constantes de `DEFINE_BITFIELD`. `Structure::HAS_..._BITS` e afins.
pub struct Structure;

/// `DEFINE_BITFIELD(type, lowerName, upperName, width, offset)`: `s_xShift`, `s_xMask`, `s_xBits` e
/// `s_bitWidthOfX`. A máscara do C++ é `(1 << (width - 1)) | ((1 << (width - 1)) - 1)`.
macro_rules! define_bitfield {
    ($($shift:ident, $mask:ident, $bits:ident, $width:ident, $w:expr, $offset:expr;)*) => {
        impl Structure {
            $(
                pub const $shift: u32 = $offset;
                pub const $mask: u32 = (1u32 << ($w - 1)) | ((1u32 << ($w - 1)) - 1);
                pub const $bits: u32 = Self::$mask << Self::$shift;
                pub const $width: u32 = $w;
            )*
        }
    };
}

define_bitfield! {
    DICTIONARY_KIND_SHIFT, DICTIONARY_KIND_MASK, DICTIONARY_KIND_BITS, BIT_WIDTH_OF_DICTIONARY_KIND, 2, 0;
    IS_PINNED_PROPERTY_TABLE_SHIFT, IS_PINNED_PROPERTY_TABLE_MASK, IS_PINNED_PROPERTY_TABLE_BITS, BIT_WIDTH_OF_IS_PINNED_PROPERTY_TABLE, 1, 2;
    HAS_ANY_KIND_OF_GETTER_SETTER_PROPERTIES_SHIFT, HAS_ANY_KIND_OF_GETTER_SETTER_PROPERTIES_MASK, HAS_ANY_KIND_OF_GETTER_SETTER_PROPERTIES_BITS, BIT_WIDTH_OF_HAS_ANY_KIND_OF_GETTER_SETTER_PROPERTIES, 1, 3;
    HAS_READ_ONLY_OR_GETTER_SETTER_PROPERTIES_EXCLUDING_PROTO_SHIFT, HAS_READ_ONLY_OR_GETTER_SETTER_PROPERTIES_EXCLUDING_PROTO_MASK, HAS_READ_ONLY_OR_GETTER_SETTER_PROPERTIES_EXCLUDING_PROTO_BITS, BIT_WIDTH_OF_HAS_READ_ONLY_OR_GETTER_SETTER_PROPERTIES_EXCLUDING_PROTO, 1, 4;
    IS_QUICK_PROPERTY_ACCESS_ALLOWED_FOR_ENUMERATION_SHIFT, IS_QUICK_PROPERTY_ACCESS_ALLOWED_FOR_ENUMERATION_MASK, IS_QUICK_PROPERTY_ACCESS_ALLOWED_FOR_ENUMERATION_BITS, BIT_WIDTH_OF_IS_QUICK_PROPERTY_ACCESS_ALLOWED_FOR_ENUMERATION, 1, 5;
    HAS_NON_ENUMERABLE_PROPERTIES_SHIFT, HAS_NON_ENUMERABLE_PROPERTIES_MASK, HAS_NON_ENUMERABLE_PROPERTIES_BITS, BIT_WIDTH_OF_HAS_NON_ENUMERABLE_PROPERTIES, 1, 6;
    HAS_SPECIAL_PROPERTIES_SHIFT, HAS_SPECIAL_PROPERTIES_MASK, HAS_SPECIAL_PROPERTIES_BITS, BIT_WIDTH_OF_HAS_SPECIAL_PROPERTIES, 1, 7;
    DEFINITELY_NON_THENABLE_STATE_SHIFT, DEFINITELY_NON_THENABLE_STATE_MASK, DEFINITELY_NON_THENABLE_STATE_BITS, BIT_WIDTH_OF_DEFINITELY_NON_THENABLE_STATE, 2, 8;
    TRANSITION_KIND_SHIFT, TRANSITION_KIND_MASK, TRANSITION_KIND_BITS, BIT_WIDTH_OF_TRANSITION_KIND, 5, 13;
    IS_WATCHING_REPLACEMENT_SHIFT, IS_WATCHING_REPLACEMENT_MASK, IS_WATCHING_REPLACEMENT_BITS, BIT_WIDTH_OF_IS_WATCHING_REPLACEMENT, 1, 18;
    MAY_BE_PROTOTYPE_SHIFT, MAY_BE_PROTOTYPE_MASK, MAY_BE_PROTOTYPE_BITS, BIT_WIDTH_OF_MAY_BE_PROTOTYPE, 1, 19;
    DID_PREVENT_EXTENSIONS_SHIFT, DID_PREVENT_EXTENSIONS_MASK, DID_PREVENT_EXTENSIONS_BITS, BIT_WIDTH_OF_DID_PREVENT_EXTENSIONS, 1, 20;
    DID_TRANSITION_SHIFT, DID_TRANSITION_MASK, DID_TRANSITION_BITS, BIT_WIDTH_OF_DID_TRANSITION, 1, 21;
    STATIC_PROPERTIES_REIFIED_SHIFT, STATIC_PROPERTIES_REIFIED_MASK, STATIC_PROPERTIES_REIFIED_BITS, BIT_WIDTH_OF_STATIC_PROPERTIES_REIFIED, 1, 22;
    HAS_BEEN_FLATTENED_BEFORE_SHIFT, HAS_BEEN_FLATTENED_BEFORE_MASK, HAS_BEEN_FLATTENED_BEFORE_BITS, BIT_WIDTH_OF_HAS_BEEN_FLATTENED_BEFORE, 1, 23;
    DID_WATCH_INTERNAL_PROPERTIES_SHIFT, DID_WATCH_INTERNAL_PROPERTIES_MASK, DID_WATCH_INTERNAL_PROPERTIES_BITS, BIT_WIDTH_OF_DID_WATCH_INTERNAL_PROPERTIES, 1, 24;
    TRANSITION_WATCHPOINT_IS_LIKELY_TO_BE_FIRED_SHIFT, TRANSITION_WATCHPOINT_IS_LIKELY_TO_BE_FIRED_MASK, TRANSITION_WATCHPOINT_IS_LIKELY_TO_BE_FIRED_BITS, BIT_WIDTH_OF_TRANSITION_WATCHPOINT_IS_LIKELY_TO_BE_FIRED, 1, 25;
    HAS_BEEN_DICTIONARY_SHIFT, HAS_BEEN_DICTIONARY_MASK, HAS_BEEN_DICTIONARY_BITS, BIT_WIDTH_OF_HAS_BEEN_DICTIONARY, 1, 26;
    PROTECT_PROPERTY_TABLE_WHILE_TRANSITIONING_SHIFT, PROTECT_PROPERTY_TABLE_WHILE_TRANSITIONING_MASK, PROTECT_PROPERTY_TABLE_WHILE_TRANSITIONING_BITS, BIT_WIDTH_OF_PROTECT_PROPERTY_TABLE_WHILE_TRANSITIONING, 1, 27;
    HAS_UNDERSCORE_PROTO_PROPERTY_EXCLUDING_ORIGINAL_PROTO_SHIFT, HAS_UNDERSCORE_PROTO_PROPERTY_EXCLUDING_ORIGINAL_PROTO_MASK, HAS_UNDERSCORE_PROTO_PROPERTY_EXCLUDING_ORIGINAL_PROTO_BITS, BIT_WIDTH_OF_HAS_UNDERSCORE_PROTO_PROPERTY_EXCLUDING_ORIGINAL_PROTO, 1, 28;
    HAS_NON_CONFIGURABLE_PROPERTIES_SHIFT, HAS_NON_CONFIGURABLE_PROPERTIES_MASK, HAS_NON_CONFIGURABLE_PROPERTIES_BITS, BIT_WIDTH_OF_HAS_NON_CONFIGURABLE_PROPERTIES, 1, 29;
    HAS_NON_CONFIGURABLE_READ_ONLY_OR_GETTER_SETTER_PROPERTIES_SHIFT, HAS_NON_CONFIGURABLE_READ_ONLY_OR_GETTER_SETTER_PROPERTIES_MASK, HAS_NON_CONFIGURABLE_READ_ONLY_OR_GETTER_SETTER_PROPERTIES_BITS, BIT_WIDTH_OF_HAS_NON_CONFIGURABLE_READ_ONLY_OR_GETTER_SETTER_PROPERTIES, 1, 30;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn masks() {
        assert_eq!(Structure::DICTIONARY_KIND_MASK, 0b11);
        assert_eq!(Structure::TRANSITION_KIND_MASK, 0b11111);
        assert_eq!(Structure::DID_PREVENT_EXTENSIONS_BITS, 1 << 20);
        assert_eq!(Structure::HAS_NON_CONFIGURABLE_PROPERTIES_BITS, 1 << 29);
        assert_eq!(Structure::HAS_NON_CONFIGURABLE_READ_ONLY_OR_GETTER_SETTER_PROPERTIES_BITS, 1 << 30);
    }
}
