//! Gerado por `scripts/gen-timezone-names.js` a partir do bun 1.4.2 (nome longo do fuso no
//! `Date.prototype.toString()`); NÃO editar à mão. `(zona IANA, nome padrão, nome de verão)`, ordenado por zona
//! para busca binária. Nome padrão vazio: o fuso não tem nome no ICU (o bun imprime `GMT+12:45`). Nome de verão
//! vazio: nenhuma amostra de 1900 a 2100 o mostrou (fuso sem horário de verão).

pub const ZONE_NAMES: &[(&str, &str, &str)] = &[
    ("Africa/Abidjan", "Greenwich Mean Time", ""),
    ("Africa/Accra", "Greenwich Mean Time", ""),
    ("Africa/Addis_Ababa", "East Africa Time", ""),
    ("Africa/Algiers", "Central European Standard Time", "Central European Summer Time"),
    ("Africa/Asmara", "East Africa Time", ""),
    ("Africa/Bamako", "Greenwich Mean Time", ""),
    ("Africa/Bangui", "West Africa Time", ""),
    ("Africa/Banjul", "Greenwich Mean Time", ""),
    ("Africa/Bissau", "Greenwich Mean Time", ""),
    ("Africa/Blantyre", "Central Africa Time", ""),
    ("Africa/Brazzaville", "West Africa Time", ""),
    ("Africa/Bujumbura", "Central Africa Time", ""),
    ("Africa/Cairo", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Africa/Casablanca", "", ""),
    ("Africa/Ceuta", "Central European Standard Time", "Central European Summer Time"),
    ("Africa/Conakry", "Greenwich Mean Time", ""),
    ("Africa/Dakar", "Greenwich Mean Time", ""),
    ("Africa/Dar_es_Salaam", "East Africa Time", ""),
    ("Africa/Djibouti", "East Africa Time", ""),
    ("Africa/Douala", "West Africa Time", ""),
    ("Africa/El_Aaiun", "", ""),
    ("Africa/Freetown", "Greenwich Mean Time", ""),
    ("Africa/Gaborone", "Central Africa Time", ""),
    ("Africa/Harare", "Central Africa Time", ""),
    ("Africa/Johannesburg", "South Africa Standard Time", ""),
    ("Africa/Juba", "Central Africa Time", ""),
    ("Africa/Kampala", "East Africa Time", ""),
    ("Africa/Khartoum", "Central Africa Time", ""),
    ("Africa/Kigali", "Central Africa Time", ""),
    ("Africa/Kinshasa", "West Africa Time", ""),
    ("Africa/Lagos", "West Africa Time", ""),
    ("Africa/Libreville", "West Africa Time", ""),
    ("Africa/Lome", "Greenwich Mean Time", ""),
    ("Africa/Luanda", "West Africa Time", ""),
    ("Africa/Lubumbashi", "Central Africa Time", ""),
    ("Africa/Lusaka", "Central Africa Time", ""),
    ("Africa/Malabo", "West Africa Time", ""),
    ("Africa/Maputo", "Central Africa Time", ""),
    ("Africa/Maseru", "South Africa Standard Time", ""),
    ("Africa/Mbabane", "South Africa Standard Time", ""),
    ("Africa/Mogadishu", "East Africa Time", ""),
    ("Africa/Monrovia", "Greenwich Mean Time", ""),
    ("Africa/Nairobi", "East Africa Time", ""),
    ("Africa/Ndjamena", "West Africa Time", ""),
    ("Africa/Niamey", "West Africa Time", ""),
    ("Africa/Nouakchott", "Greenwich Mean Time", ""),
    ("Africa/Ouagadougou", "Greenwich Mean Time", ""),
    ("Africa/Porto-Novo", "West Africa Time", ""),
    ("Africa/Sao_Tome", "Greenwich Mean Time", ""),
    ("Africa/Tripoli", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Africa/Tunis", "Central European Standard Time", "Central European Summer Time"),
    ("Africa/Windhoek", "Central Africa Time", ""),
    ("America/Adak", "Hawaii-Aleutian Standard Time", "Hawaii-Aleutian Daylight Time"),
    ("America/Anchorage", "Alaska Standard Time", "Alaska Daylight Time"),
    ("America/Anguilla", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Antigua", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Araguaina", "Brasilia Standard Time", "Brasilia Summer Time"),
    ("America/Argentina/Buenos_Aires", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/Catamarca", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/ComodRivadavia", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/Cordoba", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/Jujuy", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/La_Rioja", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/Mendoza", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/Rio_Gallegos", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/Salta", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/San_Juan", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/San_Luis", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/Tucuman", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Argentina/Ushuaia", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Aruba", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Asuncion", "Paraguay Standard Time", "Paraguay Summer Time"),
    ("America/Atikokan", "Eastern Standard Time", ""),
    ("America/Bahia", "Brasilia Standard Time", "Brasilia Summer Time"),
    ("America/Bahia_Banderas", "Central Standard Time", "Central Daylight Time"),
    ("America/Barbados", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Belem", "Brasilia Standard Time", "Brasilia Summer Time"),
    ("America/Belize", "Central Standard Time", "Central Daylight Time"),
    ("America/Blanc-Sablon", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Boa_Vista", "Amazon Standard Time", "Amazon Summer Time"),
    ("America/Bogota", "Colombia Standard Time", "Colombia Summer Time"),
    ("America/Boise", "Mountain Standard Time", "Mountain Daylight Time"),
    ("America/Buenos_Aires", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Cambridge_Bay", "Mountain Standard Time", "Mountain Daylight Time"),
    ("America/Campo_Grande", "Amazon Standard Time", "Amazon Summer Time"),
    ("America/Cancun", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Caracas", "Venezuela Time", ""),
    ("America/Catamarca", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Cayenne", "French Guiana Time", ""),
    ("America/Cayman", "Eastern Standard Time", ""),
    ("America/Chicago", "Central Standard Time", "Central Daylight Time"),
    ("America/Chihuahua", "Central Standard Time", "Central Daylight Time"),
    ("America/Ciudad_Juarez", "Mountain Standard Time", "Mountain Daylight Time"),
    ("America/Coral_Harbour", "Eastern Standard Time", ""),
    ("America/Cordoba", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Costa_Rica", "Central Standard Time", "Central Daylight Time"),
    ("America/Coyhaique", "", ""),
    ("America/Creston", "Mountain Standard Time", ""),
    ("America/Cuiaba", "Amazon Standard Time", "Amazon Summer Time"),
    ("America/Curacao", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Danmarkshavn", "Greenwich Mean Time", ""),
    ("America/Dawson", "Yukon Time", ""),
    ("America/Dawson_Creek", "Mountain Standard Time", "Mountain Daylight Time"),
    ("America/Denver", "Mountain Standard Time", "Mountain Daylight Time"),
    ("America/Detroit", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Dominica", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Edmonton", "Mountain Standard Time", "Mountain Daylight Time"),
    ("America/Eirunepe", "Acre Standard Time", "Acre Summer Time"),
    ("America/El_Salvador", "Central Standard Time", "Central Daylight Time"),
    ("America/Ensenada", "Pacific Standard Time", "Pacific Daylight Time"),
    ("America/Fort_Nelson", "Mountain Standard Time", "Mountain Daylight Time"),
    ("America/Fort_Wayne", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Fortaleza", "Brasilia Standard Time", "Brasilia Summer Time"),
    ("America/Glace_Bay", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Goose_Bay", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Grand_Turk", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Grenada", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Guadeloupe", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Guatemala", "Central Standard Time", "Central Daylight Time"),
    ("America/Guayaquil", "Ecuador Time", ""),
    ("America/Guyana", "Guyana Time", ""),
    ("America/Halifax", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Havana", "Cuba Standard Time", "Cuba Daylight Time"),
    ("America/Hermosillo", "Mexican Pacific Standard Time", "Mexican Pacific Daylight Time"),
    ("America/Indiana/Indianapolis", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Indiana/Knox", "Central Standard Time", "Central Daylight Time"),
    ("America/Indiana/Marengo", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Indiana/Petersburg", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Indiana/Tell_City", "Central Standard Time", "Central Daylight Time"),
    ("America/Indiana/Vevay", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Indiana/Vincennes", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Indiana/Winamac", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Indianapolis", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Inuvik", "Mountain Standard Time", "Mountain Daylight Time"),
    ("America/Iqaluit", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Jamaica", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Jujuy", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Juneau", "Alaska Standard Time", "Alaska Daylight Time"),
    ("America/Kentucky/Louisville", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Kentucky/Monticello", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Kralendijk", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/La_Paz", "Bolivia Time", ""),
    ("America/Lima", "Peru Standard Time", "Peru Summer Time"),
    ("America/Los_Angeles", "Pacific Standard Time", "Pacific Daylight Time"),
    ("America/Louisville", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Lower_Princes", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Maceio", "Brasilia Standard Time", "Brasilia Summer Time"),
    ("America/Managua", "Central Standard Time", ""),
    ("America/Manaus", "Amazon Standard Time", "Amazon Summer Time"),
    ("America/Marigot", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Martinique", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Matamoros", "Central Standard Time", "Central Daylight Time"),
    ("America/Mazatlan", "Mexican Pacific Standard Time", "Mexican Pacific Daylight Time"),
    ("America/Mendoza", "Argentina Standard Time", "Argentina Summer Time"),
    ("America/Menominee", "Central Standard Time", "Central Daylight Time"),
    ("America/Merida", "Central Standard Time", "Central Daylight Time"),
    ("America/Metlakatla", "Alaska Standard Time", "Alaska Daylight Time"),
    ("America/Mexico_City", "Central Standard Time", "Central Daylight Time"),
    ("America/Miquelon", "St. Pierre & Miquelon Standard Time", "St. Pierre & Miquelon Daylight Time"),
    ("America/Moncton", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Monterrey", "Central Standard Time", "Central Daylight Time"),
    ("America/Montevideo", "Uruguay Standard Time", "Uruguay Summer Time"),
    ("America/Montreal", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Montserrat", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Nassau", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/New_York", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Nome", "Alaska Standard Time", "Alaska Daylight Time"),
    ("America/Noronha", "Fernando de Noronha Standard Time", "Fernando de Noronha Summer Time"),
    ("America/North_Dakota/Beulah", "Central Standard Time", "Central Daylight Time"),
    ("America/North_Dakota/Center", "Central Standard Time", "Central Daylight Time"),
    ("America/North_Dakota/New_Salem", "Central Standard Time", "Central Daylight Time"),
    ("America/Nuuk", "Greenland Standard Time", "Greenland Summer Time"),
    ("America/Ojinaga", "Central Standard Time", "Central Daylight Time"),
    ("America/Panama", "Eastern Standard Time", ""),
    ("America/Paramaribo", "Suriname Time", ""),
    ("America/Phoenix", "Mountain Standard Time", ""),
    ("America/Port-au-Prince", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Port_of_Spain", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Porto_Velho", "Amazon Standard Time", "Amazon Summer Time"),
    ("America/Puerto_Rico", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Punta_Arenas", "", ""),
    ("America/Rainy_River", "Central Standard Time", "Central Daylight Time"),
    ("America/Rankin_Inlet", "Central Standard Time", "Central Daylight Time"),
    ("America/Recife", "Brasilia Standard Time", "Brasilia Summer Time"),
    ("America/Regina", "Central Standard Time", "Central Daylight Time"),
    ("America/Resolute", "Central Standard Time", "Central Daylight Time"),
    ("America/Rio_Branco", "Acre Standard Time", "Acre Summer Time"),
    ("America/Santarem", "Brasilia Standard Time", "Brasilia Summer Time"),
    ("America/Santiago", "Chile Standard Time", "Chile Summer Time"),
    ("America/Santo_Domingo", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Sao_Paulo", "Brasilia Standard Time", "Brasilia Summer Time"),
    ("America/Scoresbysund", "Greenland Standard Time", "Greenland Summer Time"),
    ("America/Sitka", "Alaska Standard Time", "Alaska Daylight Time"),
    ("America/St_Barthelemy", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/St_Johns", "Newfoundland Standard Time", "Newfoundland Daylight Time"),
    ("America/St_Kitts", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/St_Lucia", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/St_Thomas", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/St_Vincent", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Swift_Current", "Central Standard Time", "Central Daylight Time"),
    ("America/Tegucigalpa", "Central Standard Time", "Central Daylight Time"),
    ("America/Thule", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Tijuana", "Pacific Standard Time", "Pacific Daylight Time"),
    ("America/Toronto", "Eastern Standard Time", "Eastern Daylight Time"),
    ("America/Tortola", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("America/Vancouver", "Pacific Standard Time", "Pacific Daylight Time"),
    ("America/Whitehorse", "Yukon Time", ""),
    ("America/Winnipeg", "Central Standard Time", "Central Daylight Time"),
    ("America/Yakutat", "Alaska Standard Time", "Alaska Daylight Time"),
    ("America/Yellowknife", "Mountain Standard Time", "Mountain Daylight Time"),
    ("Antarctica/Casey", "Australian Western Standard Time", ""),
    ("Antarctica/Davis", "Davis Time", ""),
    ("Antarctica/DumontDUrville", "Dumont d’Urville Time", ""),
    ("Antarctica/Macquarie", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Antarctica/Mawson", "Mawson Time", ""),
    ("Antarctica/McMurdo", "New Zealand Standard Time", "New Zealand Daylight Time"),
    ("Antarctica/Palmer", "", ""),
    ("Antarctica/Rothera", "Rothera Time", ""),
    ("Antarctica/Syowa", "Syowa Time", ""),
    ("Antarctica/Troll", "Greenwich Mean Time", ""),
    ("Antarctica/Vostok", "Vostok Time", ""),
    ("Arctic/Longyearbyen", "Central European Standard Time", "Central European Summer Time"),
    ("Asia/Aden", "Arabian Standard Time", ""),
    ("Asia/Almaty", "Kazakhstan Time", ""),
    ("Asia/Amman", "", ""),
    ("Asia/Anadyr", "Kamchatka Standard Time", "Kamchatka Summer Time"),
    ("Asia/Aqtau", "Kazakhstan Time", ""),
    ("Asia/Aqtobe", "Kazakhstan Time", ""),
    ("Asia/Ashgabat", "Turkmenistan Standard Time", "Turkmenistan Summer Time"),
    ("Asia/Atyrau", "Kazakhstan Time", ""),
    ("Asia/Baghdad", "Arabian Standard Time", "Arabian Daylight Time"),
    ("Asia/Bahrain", "Arabian Standard Time", ""),
    ("Asia/Baku", "Azerbaijan Standard Time", "Azerbaijan Summer Time"),
    ("Asia/Bangkok", "Indochina Time", ""),
    ("Asia/Barnaul", "Krasnoyarsk Standard Time", "Krasnoyarsk Summer Time"),
    ("Asia/Beirut", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Asia/Bishkek", "Kyrgyzstan Time", ""),
    ("Asia/Brunei", "Brunei Time", ""),
    ("Asia/Calcutta", "India Standard Time", ""),
    ("Asia/Chita", "Yakutsk Standard Time", "Yakutsk Summer Time"),
    ("Asia/Chongqing", "China Standard Time", "China Daylight Time"),
    ("Asia/Colombo", "India Standard Time", ""),
    ("Asia/Dacca", "Bangladesh Standard Time", "Bangladesh Summer Time"),
    ("Asia/Damascus", "", ""),
    ("Asia/Dhaka", "Bangladesh Standard Time", "Bangladesh Summer Time"),
    ("Asia/Dili", "Timor-Leste Time", ""),
    ("Asia/Dubai", "Gulf Standard Time", ""),
    ("Asia/Dushanbe", "Tajikistan Time", ""),
    ("Asia/Famagusta", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Asia/Gaza", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Asia/Harbin", "China Standard Time", "China Daylight Time"),
    ("Asia/Hebron", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Asia/Ho_Chi_Minh", "Indochina Time", ""),
    ("Asia/Hong_Kong", "Hong Kong Standard Time", "Hong Kong Summer Time"),
    ("Asia/Hovd", "Khovd Standard Time", "Khovd Summer Time"),
    ("Asia/Irkutsk", "Irkutsk Standard Time", "Irkutsk Summer Time"),
    ("Asia/Jakarta", "Western Indonesia Time", ""),
    ("Asia/Jayapura", "Eastern Indonesia Time", ""),
    ("Asia/Jerusalem", "Israel Standard Time", "Israel Daylight Time"),
    ("Asia/Kabul", "Afghanistan Time", ""),
    ("Asia/Kamchatka", "Kamchatka Standard Time", "Kamchatka Summer Time"),
    ("Asia/Karachi", "Pakistan Standard Time", "Pakistan Summer Time"),
    ("Asia/Kathmandu", "Nepal Time", ""),
    ("Asia/Katmandu", "Nepal Time", ""),
    ("Asia/Khandyga", "Yakutsk Standard Time", "Yakutsk Summer Time"),
    ("Asia/Kolkata", "India Standard Time", ""),
    ("Asia/Krasnoyarsk", "Krasnoyarsk Standard Time", "Krasnoyarsk Summer Time"),
    ("Asia/Kuala_Lumpur", "Malaysia Time", ""),
    ("Asia/Kuching", "Malaysia Time", ""),
    ("Asia/Kuwait", "Arabian Standard Time", ""),
    ("Asia/Macau", "China Standard Time", "China Daylight Time"),
    ("Asia/Magadan", "Magadan Standard Time", "Magadan Summer Time"),
    ("Asia/Makassar", "Central Indonesia Time", ""),
    ("Asia/Manila", "Philippine Standard Time", "Philippine Summer Time"),
    ("Asia/Muscat", "Gulf Standard Time", ""),
    ("Asia/Nicosia", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Asia/Novokuznetsk", "Krasnoyarsk Standard Time", "Krasnoyarsk Summer Time"),
    ("Asia/Novosibirsk", "Krasnoyarsk Standard Time", "Krasnoyarsk Summer Time"),
    ("Asia/Omsk", "Omsk Standard Time", "Omsk Summer Time"),
    ("Asia/Oral", "Kazakhstan Time", ""),
    ("Asia/Phnom_Penh", "Indochina Time", ""),
    ("Asia/Pontianak", "Western Indonesia Time", ""),
    ("Asia/Pyongyang", "Korean Standard Time", ""),
    ("Asia/Qatar", "Arabian Standard Time", ""),
    ("Asia/Qostanay", "Kazakhstan Time", ""),
    ("Asia/Qyzylorda", "Kazakhstan Time", ""),
    ("Asia/Riyadh", "Arabian Standard Time", ""),
    ("Asia/Saigon", "Indochina Time", ""),
    ("Asia/Sakhalin", "Magadan Standard Time", "Magadan Summer Time"),
    ("Asia/Samarkand", "Uzbekistan Standard Time", "Uzbekistan Summer Time"),
    ("Asia/Seoul", "Korean Standard Time", "Korean Daylight Time"),
    ("Asia/Shanghai", "China Standard Time", "China Daylight Time"),
    ("Asia/Singapore", "Singapore Standard Time", ""),
    ("Asia/Srednekolymsk", "Magadan Standard Time", "Magadan Summer Time"),
    ("Asia/Taipei", "Taiwan Standard Time", "Taiwan Daylight Time"),
    ("Asia/Tashkent", "Uzbekistan Standard Time", "Uzbekistan Summer Time"),
    ("Asia/Tbilisi", "Georgia Standard Time", "Georgia Summer Time"),
    ("Asia/Tehran", "Iran Standard Time", "Iran Daylight Time"),
    ("Asia/Tel_Aviv", "Israel Standard Time", "Israel Daylight Time"),
    ("Asia/Thimphu", "Bhutan Time", ""),
    ("Asia/Tokyo", "Japan Standard Time", "Japan Daylight Time"),
    ("Asia/Tomsk", "Krasnoyarsk Standard Time", "Krasnoyarsk Summer Time"),
    ("Asia/Ulaanbaatar", "Ulaanbaatar Standard Time", "Ulaanbaatar Summer Time"),
    ("Asia/Urumqi", "", ""),
    ("Asia/Ust-Nera", "Vladivostok Standard Time", "Vladivostok Summer Time"),
    ("Asia/Vientiane", "Indochina Time", ""),
    ("Asia/Vladivostok", "Vladivostok Standard Time", "Vladivostok Summer Time"),
    ("Asia/Yakutsk", "Yakutsk Standard Time", "Yakutsk Summer Time"),
    ("Asia/Yangon", "Myanmar Time", ""),
    ("Asia/Yekaterinburg", "Yekaterinburg Standard Time", "Yekaterinburg Summer Time"),
    ("Asia/Yerevan", "Armenia Standard Time", "Armenia Summer Time"),
    ("Atlantic/Azores", "Azores Standard Time", "Azores Summer Time"),
    ("Atlantic/Bermuda", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("Atlantic/Canary", "Western European Standard Time", "Western European Summer Time"),
    ("Atlantic/Cape_Verde", "Cape Verde Standard Time", "Cape Verde Summer Time"),
    ("Atlantic/Faeroe", "Western European Standard Time", "Western European Summer Time"),
    ("Atlantic/Faroe", "Western European Standard Time", "Western European Summer Time"),
    ("Atlantic/Jan_Mayen", "Central European Standard Time", "Central European Summer Time"),
    ("Atlantic/Madeira", "Western European Standard Time", "Western European Summer Time"),
    ("Atlantic/Reykjavik", "Greenwich Mean Time", ""),
    ("Atlantic/South_Georgia", "South Georgia Time", ""),
    ("Atlantic/St_Helena", "Greenwich Mean Time", ""),
    ("Atlantic/Stanley", "Falkland Islands Standard Time", "Falkland Islands Summer Time"),
    ("Australia/ACT", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/Adelaide", "Australian Central Standard Time", "Australian Central Daylight Time"),
    ("Australia/Brisbane", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/Broken_Hill", "Australian Central Standard Time", "Australian Central Daylight Time"),
    ("Australia/Canberra", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/Currie", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/Darwin", "Australian Central Standard Time", ""),
    ("Australia/Eucla", "Australian Central Western Standard Time", "Australian Central Western Daylight Time"),
    ("Australia/Hobart", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/Lindeman", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/Lord_Howe", "Lord Howe Standard Time", "Lord Howe Daylight Time"),
    ("Australia/Melbourne", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/NSW", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/North", "Australian Central Standard Time", ""),
    ("Australia/Perth", "Australian Western Standard Time", "Australian Western Daylight Time"),
    ("Australia/Queensland", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/South", "Australian Central Standard Time", "Australian Central Daylight Time"),
    ("Australia/Sydney", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/Tasmania", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/Victoria", "Australian Eastern Standard Time", "Australian Eastern Daylight Time"),
    ("Australia/West", "Australian Western Standard Time", "Australian Western Daylight Time"),
    ("Australia/Yancowinna", "Australian Central Standard Time", "Australian Central Daylight Time"),
    ("Brazil/Acre", "Acre Standard Time", "Acre Summer Time"),
    ("Brazil/DeNoronha", "Fernando de Noronha Standard Time", "Fernando de Noronha Summer Time"),
    ("Brazil/East", "Brasilia Standard Time", "Brasilia Summer Time"),
    ("Brazil/West", "Amazon Standard Time", "Amazon Summer Time"),
    ("CET", "Central European Standard Time", "Central European Summer Time"),
    ("CST6CDT", "Central Standard Time", "Central Daylight Time"),
    ("Canada/Atlantic", "Atlantic Standard Time", "Atlantic Daylight Time"),
    ("Canada/Newfoundland", "Newfoundland Standard Time", "Newfoundland Daylight Time"),
    ("Chile/Continental", "Chile Standard Time", "Chile Summer Time"),
    ("Cuba", "Cuba Standard Time", "Cuba Daylight Time"),
    ("EET", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("EST", "Eastern Standard Time", ""),
    ("EST5EDT", "Eastern Standard Time", "Eastern Daylight Time"),
    ("Egypt", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Eire", "Greenwich Mean Time", "Irish Standard Time"),
    ("Etc/GMT", "Coordinated Universal Time", ""),
    ("Etc/GMT+0", "Coordinated Universal Time", ""),
    ("Etc/GMT+1", "", ""),
    ("Etc/GMT+10", "", ""),
    ("Etc/GMT+11", "", ""),
    ("Etc/GMT+12", "", ""),
    ("Etc/GMT+2", "", ""),
    ("Etc/GMT+3", "", ""),
    ("Etc/GMT+4", "", ""),
    ("Etc/GMT+5", "", ""),
    ("Etc/GMT+6", "", ""),
    ("Etc/GMT+7", "", ""),
    ("Etc/GMT+8", "", ""),
    ("Etc/GMT+9", "", ""),
    ("Etc/GMT-0", "Coordinated Universal Time", ""),
    ("Etc/GMT-1", "", ""),
    ("Etc/GMT-10", "", ""),
    ("Etc/GMT-11", "", ""),
    ("Etc/GMT-12", "", ""),
    ("Etc/GMT-13", "", ""),
    ("Etc/GMT-14", "", ""),
    ("Etc/GMT-2", "", ""),
    ("Etc/GMT-3", "", ""),
    ("Etc/GMT-4", "", ""),
    ("Etc/GMT-5", "", ""),
    ("Etc/GMT-6", "", ""),
    ("Etc/GMT-7", "", ""),
    ("Etc/GMT-8", "", ""),
    ("Etc/GMT-9", "", ""),
    ("Etc/GMT0", "Coordinated Universal Time", ""),
    ("Etc/Greenwich", "Coordinated Universal Time", ""),
    ("Etc/UCT", "Coordinated Universal Time", ""),
    ("Etc/UTC", "Coordinated Universal Time", ""),
    ("Etc/Universal", "Coordinated Universal Time", ""),
    ("Etc/Zulu", "Coordinated Universal Time", ""),
    ("Europe/Amsterdam", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Andorra", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Astrakhan", "Samara Standard Time", "Samara Summer Time"),
    ("Europe/Athens", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Belfast", "Greenwich Mean Time", "British Summer Time"),
    ("Europe/Belgrade", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Berlin", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Bratislava", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Brussels", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Bucharest", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Budapest", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Busingen", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Chisinau", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Copenhagen", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Dublin", "Greenwich Mean Time", "Irish Standard Time"),
    ("Europe/Gibraltar", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Guernsey", "Greenwich Mean Time", ""),
    ("Europe/Helsinki", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Isle_of_Man", "Greenwich Mean Time", ""),
    ("Europe/Istanbul", "Türkiye Standard Time", "Türkiye Summer Time"),
    ("Europe/Jersey", "Greenwich Mean Time", ""),
    ("Europe/Kaliningrad", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Kiev", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Kirov", "Moscow Standard Time", "Moscow Summer Time"),
    ("Europe/Kyiv", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Lisbon", "Western European Standard Time", "Western European Summer Time"),
    ("Europe/Ljubljana", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/London", "Greenwich Mean Time", "British Summer Time"),
    ("Europe/Luxembourg", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Madrid", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Malta", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Mariehamn", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Minsk", "Moscow Standard Time", "Moscow Summer Time"),
    ("Europe/Monaco", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Moscow", "Moscow Standard Time", "Moscow Summer Time"),
    ("Europe/Nicosia", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Oslo", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Paris", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Podgorica", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Prague", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Riga", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Rome", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Samara", "Samara Standard Time", "Samara Summer Time"),
    ("Europe/San_Marino", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Sarajevo", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Saratov", "Samara Standard Time", "Samara Summer Time"),
    ("Europe/Simferopol", "Moscow Standard Time", "Moscow Summer Time"),
    ("Europe/Skopje", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Sofia", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Stockholm", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Tallinn", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Tirane", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Ulyanovsk", "Samara Standard Time", "Samara Summer Time"),
    ("Europe/Uzhgorod", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Vaduz", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Vatican", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Vienna", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Vilnius", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Volgograd", "Moscow Standard Time", "Moscow Summer Time"),
    ("Europe/Warsaw", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Zagreb", "Central European Standard Time", "Central European Summer Time"),
    ("Europe/Zaporozhye", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("Europe/Zurich", "Central European Standard Time", "Central European Summer Time"),
    ("GB", "Greenwich Mean Time", "British Summer Time"),
    ("GMT", "Coordinated Universal Time", ""),
    ("GMT0", "Coordinated Universal Time", ""),
    ("Greenwich", "Coordinated Universal Time", ""),
    ("HST", "Hawaii-Aleutian Standard Time", ""),
    ("Hongkong", "Hong Kong Standard Time", "Hong Kong Summer Time"),
    ("Iceland", "Greenwich Mean Time", ""),
    ("Indian/Antananarivo", "East Africa Time", ""),
    ("Indian/Chagos", "Indian Ocean Time", ""),
    ("Indian/Christmas", "Christmas Island Time", ""),
    ("Indian/Cocos", "Cocos Islands Time", ""),
    ("Indian/Comoro", "East Africa Time", ""),
    ("Indian/Kerguelen", "French Southern & Antarctic Time", ""),
    ("Indian/Mahe", "Seychelles Time", ""),
    ("Indian/Maldives", "Maldives Time", ""),
    ("Indian/Mauritius", "Mauritius Standard Time", "Mauritius Summer Time"),
    ("Indian/Mayotte", "East Africa Time", ""),
    ("Indian/Reunion", "Réunion Time", ""),
    ("Iran", "Iran Standard Time", "Iran Daylight Time"),
    ("Israel", "Israel Standard Time", "Israel Daylight Time"),
    ("Japan", "Japan Standard Time", "Japan Daylight Time"),
    ("Libya", "Eastern European Standard Time", "Eastern European Summer Time"),
    ("MET", "Central European Standard Time", "Central European Summer Time"),
    ("MST", "Mountain Standard Time", ""),
    ("MST7MDT", "Mountain Standard Time", "Mountain Daylight Time"),
    ("Mexico/General", "Central Standard Time", "Central Daylight Time"),
    ("NZ", "New Zealand Standard Time", "New Zealand Daylight Time"),
    ("PRC", "China Standard Time", "China Daylight Time"),
    ("PST8PDT", "Pacific Standard Time", "Pacific Daylight Time"),
    ("Pacific/Apia", "Samoa Standard Time", "Samoa Daylight Time"),
    ("Pacific/Auckland", "New Zealand Standard Time", "New Zealand Daylight Time"),
    ("Pacific/Bougainville", "", ""),
    ("Pacific/Chatham", "Chatham Standard Time", "Chatham Daylight Time"),
    ("Pacific/Chuuk", "Chuuk Time", ""),
    ("Pacific/Easter", "Easter Island Standard Time", "Easter Island Summer Time"),
    ("Pacific/Efate", "Vanuatu Standard Time", "Vanuatu Summer Time"),
    ("Pacific/Fakaofo", "Tokelau Time", ""),
    ("Pacific/Fiji", "Fiji Standard Time", "Fiji Summer Time"),
    ("Pacific/Funafuti", "Tuvalu Time", ""),
    ("Pacific/Galapagos", "Galapagos Time", ""),
    ("Pacific/Gambier", "Gambier Time", ""),
    ("Pacific/Guadalcanal", "Solomon Islands Time", ""),
    ("Pacific/Guam", "Chamorro Standard Time", ""),
    ("Pacific/Honolulu", "Hawaii-Aleutian Standard Time", ""),
    ("Pacific/Kanton", "Phoenix Islands Time", ""),
    ("Pacific/Kiritimati", "Line Islands Time", ""),
    ("Pacific/Kosrae", "Kosrae Time", ""),
    ("Pacific/Kwajalein", "Marshall Islands Time", ""),
    ("Pacific/Majuro", "Marshall Islands Time", ""),
    ("Pacific/Marquesas", "Marquesas Time", ""),
    ("Pacific/Midway", "American Samoa Standard Time", ""),
    ("Pacific/Nauru", "Nauru Time", ""),
    ("Pacific/Niue", "Niue Time", ""),
    ("Pacific/Norfolk", "Norfolk Island Standard Time", "Norfolk Island Daylight Time"),
    ("Pacific/Noumea", "New Caledonia Standard Time", "New Caledonia Summer Time"),
    ("Pacific/Pago_Pago", "American Samoa Standard Time", ""),
    ("Pacific/Palau", "Palau Time", ""),
    ("Pacific/Pitcairn", "Pitcairn Time", ""),
    ("Pacific/Pohnpei", "Pohnpei Time", ""),
    ("Pacific/Port_Moresby", "Papua New Guinea Time", ""),
    ("Pacific/Rarotonga", "Cook Islands Standard Time", "Cook Islands Summer Time"),
    ("Pacific/Saipan", "Chamorro Standard Time", ""),
    ("Pacific/Tahiti", "Tahiti Time", ""),
    ("Pacific/Tarawa", "Gilbert Islands Time", ""),
    ("Pacific/Tongatapu", "Tonga Standard Time", "Tonga Summer Time"),
    ("Pacific/Wake", "Wake Island Time", ""),
    ("Pacific/Wallis", "Wallis & Futuna Time", ""),
    ("Poland", "Central European Standard Time", "Central European Summer Time"),
    ("Portugal", "Western European Standard Time", "Western European Summer Time"),
    ("ROC", "Taiwan Standard Time", "Taiwan Daylight Time"),
    ("ROK", "Korean Standard Time", "Korean Daylight Time"),
    ("Singapore", "Singapore Standard Time", ""),
    ("UCT", "Coordinated Universal Time", ""),
    ("US/Alaska", "Alaska Standard Time", "Alaska Daylight Time"),
    ("US/Aleutian", "Hawaii-Aleutian Standard Time", "Hawaii-Aleutian Daylight Time"),
    ("US/Arizona", "Mountain Standard Time", ""),
    ("US/Central", "Central Standard Time", "Central Daylight Time"),
    ("US/Eastern", "Eastern Standard Time", "Eastern Daylight Time"),
    ("US/Hawaii", "Hawaii-Aleutian Standard Time", ""),
    ("US/Mountain", "Mountain Standard Time", "Mountain Daylight Time"),
    ("US/Pacific", "Pacific Standard Time", "Pacific Daylight Time"),
    ("UTC", "Coordinated Universal Time", ""),
    ("Universal", "Coordinated Universal Time", ""),
    ("W-SU", "Moscow Standard Time", "Moscow Summer Time"),
    ("WET", "Western European Standard Time", "Western European Summer Time"),
    ("Zulu", "Coordinated Universal Time", ""),
];
