// Automatically generated from JSGlobalObject.cpp using create_hash_table. DO NOT EDIT!

#include "Lookup.h"

namespace JSC {

static constinit const struct CompactHashIndex globalObjectTableIndex[141] = {
    { -1, -1 },
    { 35, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 41, -1 },
    { -1, -1 },
    { -1, -1 },
    { 29, 132 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 36, -1 },
    { -1, -1 },
    { -1, -1 },
    { 20, 134 },
    { -1, -1 },
    { -1, -1 },
    { 9, -1 },
    { 44, -1 },
    { 50, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 23, -1 },
    { 18, -1 },
    { -1, -1 },
    { -1, -1 },
    { 42, -1 },
    { -1, -1 },
    { 17, -1 },
    { 21, -1 },
    { 5, 136 },
    { 3, 128 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 6, -1 },
    { 8, 131 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 39, -1 },
    { 16, -1 },
    { -1, -1 },
    { -1, -1 },
    { 28, -1 },
    { -1, -1 },
    { 27, -1 },
    { -1, -1 },
    { 13, 139 },
    { -1, -1 },
    { -1, -1 },
    { 2, 137 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 31, 135 },
    { -1, -1 },
    { 4, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 19, -1 },
    { -1, -1 },
    { -1, -1 },
    { 12, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 46, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 49, -1 },
    { 26, 133 },
    { -1, -1 },
    { 11, -1 },
    { -1, -1 },
    { -1, -1 },
    { 24, 138 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 0, -1 },
    { 1, 129 },
    { -1, -1 },
    { -1, -1 },
    { 7, -1 },
    { 33, -1 },
    { 38, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 14, -1 },
    { 10, -1 },
    { 15, 130 },
    { 22, -1 },
    { 25, -1 },
    { 30, -1 },
    { 32, -1 },
    { 34, -1 },
    { 37, -1 },
    { 40, -1 },
    { 43, -1 },
    { 45, 140 },
    { 47, -1 },
    { 48, -1 },
};

static constinit const struct HashTableValue globalObjectTableValues[51] = {
   { "isNaN"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), GlobalIsNaNIntrinsic, { HashTableValue::NativeFunctionType, globalFuncIsNaN, 1 } },
   { "isFinite"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), GlobalIsFiniteIntrinsic, { HashTableValue::NativeFunctionType, globalFuncIsFinite, 1 } },
   { "escape"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, globalFuncEscape, 1 } },
   { "unescape"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, globalFuncUnescape, 1 } },
   { "decodeURI"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, globalFuncDecodeURI, 1 } },
   { "decodeURIComponent"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, globalFuncDecodeURIComponent, 1 } },
   { "encodeURI"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, globalFuncEncodeURI, 1 } },
   { "encodeURIComponent"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, globalFuncEncodeURIComponent, 1 } },
   { "eval"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, initializeEvalFunction } },
   { "globalThis"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::CellProperty), NoIntrinsic, { HashTableValue::LazyCellPropertyType, OBJECT_OFFSETOF(JSGlobalObject, m_globalThis) } },
   { "parseInt"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::CellProperty), NoIntrinsic, { HashTableValue::LazyCellPropertyType, OBJECT_OFFSETOF(JSGlobalObject, m_parseIntFunction) } },
   { "parseFloat"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::CellProperty), NoIntrinsic, { HashTableValue::LazyCellPropertyType, OBJECT_OFFSETOF(JSGlobalObject, m_parseFloatFunction) } },
   { "ArrayBuffer"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_arrayBufferStructure) } },
   { "EvalError"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_evalErrorStructure) } },
   { "RangeError"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_rangeErrorStructure) } },
   { "ReferenceError"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_referenceErrorStructure) } },
   { "SyntaxError"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_syntaxErrorStructure) } },
   { "TypeError"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typeErrorStructure) } },
   { "URIError"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_URIErrorStructure) } },
   { "AggregateError"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_aggregateErrorStructure) } },
   { "SuppressedError"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_suppressedErrorStructure) } },
   { "Proxy"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, createProxyProperty } },
   { "Reflect"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, createReflectProperty } },
   { "JSON"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, createJSONProperty } },
   { "Math"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, createMathProperty } },
   { "Atomics"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, createAtomicsProperty } },
   { "WebAssembly"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, createWebAssemblyProperty } },
   { "console"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, createConsoleProperty } },
   { "Int8Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayInt8) } },
   { "Int16Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayInt16) } },
   { "Int32Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayInt32) } },
   { "Uint8Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayUint8) } },
   { "Uint8ClampedArray"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayUint8Clamped) } },
   { "Uint16Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayUint16) } },
   { "Uint32Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayUint32) } },
   { "Float16Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayFloat16) } },
   { "Float32Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayFloat32) } },
   { "Float64Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayFloat64) } },
   { "BigInt64Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayBigInt64) } },
   { "BigUint64Array"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayBigUint64) } },
   { "DataView"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_typedArrayDataView) } },
   { "Date"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_dateStructure) } },
   { "Error"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_errorStructure) } },
   { "Boolean"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_booleanObjectStructure) } },
   { "Map"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_mapStructure) } },
   { "Number"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_numberObjectStructure) } },
   { "Set"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_setStructure) } },
   { "WeakMap"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_weakMapStructure) } },
   { "WeakSet"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_weakSetStructure) } },
   { "WeakRef"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_weakObjectRefStructure) } },
   { "FinalizationRegistry"_s, static_cast<unsigned>(PropertyAttribute::DontEnum|PropertyAttribute::ClassStructure), NoIntrinsic, { HashTableValue::LazyClassStructureType, OBJECT_OFFSETOF(JSGlobalObject, m_finalizationRegistryStructure) } },
};

static constinit const struct HashTable globalObjectTable =
    { 51, 127, false, nullptr, globalObjectTableValues, globalObjectTableIndex };

} // namespace JSC
