//! Gerado por `scripts/gen-bytecode-intrinsics.py` a partir de `bytecode/BytecodeIntrinsicRegistry.h`,
//! `bytecode/LinkTimeConstant.h` e `derived/JavaScriptCore/JSCBuiltins.h`. Não editar à mão.

/// Um `emit_intrinsic_<name>` de `BytecodeIntrinsicNode`: primeiro as funções
/// (`JSC_COMMON_BYTECODE_INTRINSIC_FUNCTIONS_EACH_NAME`), depois as constantes
/// (`..._CONSTANTS_EACH_NAME`, as simples e a `orderedHashTableSentinel`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum BytecodeIntrinsicEmitter {
    Argument = 0,
    ArgumentCount = 1,
    ArrayPush = 2,
    GetByIdDirect = 3,
    GetByIdDirectPrivate = 4,
    GetByValWithThis = 5,
    GetPrototypeOf = 6,
    GetInternalField = 7,
    GetGeneratorInternalField = 8,
    GetIteratorHelperInternalField = 9,
    GetAsyncDisposableStackInternalField = 10,
    GetArrayIteratorInternalField = 11,
    GetProxyInternalField = 12,
    GetWrapForValidIteratorInternalField = 13,
    GetDisposableStackInternalField = 14,
    IdWithProfile = 15,
    IsAsyncDisposableStack = 16,
    IsObject = 17,
    IsCallable = 18,
    IsConstructor = 19,
    IsJSArray = 20,
    IsProxyObject = 21,
    IsDerivedArray = 22,
    IsGenerator = 23,
    IsIteratorHelper = 24,
    IsPromise = 25,
    IsRegExpObject = 26,
    IsMap = 27,
    IsSet = 28,
    IsShadowRealm = 29,
    IsArrayIterator = 30,
    IsUndefinedOrNull = 31,
    IsWrapForValidIterator = 32,
    IsDisposableStack = 33,
    ThrowTypeError = 34,
    ThrowRangeError = 35,
    ThrowOutOfMemoryError = 36,
    PutByIdDirect = 37,
    PutByIdDirectPrivate = 38,
    PutByValDirect = 39,
    PutByValWithThisSloppy = 40,
    PutByValWithThisStrict = 41,
    PutInternalField = 42,
    PutGeneratorInternalField = 43,
    PutAsyncDisposableStackInternalField = 44,
    PutArrayIteratorInternalField = 45,
    PutDisposableStackInternalField = 46,
    SuperSamplerBegin = 47,
    SuperSamplerEnd = 48,
    ToNumber = 49,
    ToString = 50,
    ToPropertyKey = 51,
    ToObject = 52,
    ToThis = 53,
    MustValidateResultOfProxyGetAndSetTraps = 54,
    MustValidateResultOfProxyTrapsExceptGetAndSet = 55,
    NewArrayWithSize = 56,
    NewArrayWithSpecies = 57,
    NewPromise = 58,
    IteratorGenericClose = 59,
    IteratorGenericNext = 60,
    IfAbruptCloseIterator = 61,
    CreatePromise = 62,
    Undefined = 63,
    Infinity = 64,
    IterationKindKey = 65,
    IterationKindValue = 66,
    IterationKindEntries = 67,
    MaxArrayIndex = 68,
    MaxStringLength = 69,
    MaxSafeInteger = 70,
    ModuleFetch = 71,
    ModuleTranslate = 72,
    ModuleInstantiate = 73,
    ModuleSatisfy = 74,
    ModuleLink = 75,
    ModuleReady = 76,
    ProxyFieldTarget = 77,
    ProxyFieldHandler = 78,
    GeneratorFieldState = 79,
    GeneratorFieldNext = 80,
    GeneratorFieldThis = 81,
    GeneratorFieldFrame = 82,
    GeneratorResumeModeNormal = 83,
    GeneratorResumeModeThrow = 84,
    GeneratorResumeModeReturn = 85,
    GeneratorStateCompleted = 86,
    GeneratorStateExecuting = 87,
    GeneratorStateInit = 88,
    IteratorHelperFieldGenerator = 89,
    IteratorHelperFieldUnderlyingIterator = 90,
    ArrayIteratorFieldIndex = 91,
    ArrayIteratorFieldIteratedObject = 92,
    ArrayIteratorFieldKind = 93,
    WrapForValidIteratorFieldIteratedIterator = 94,
    WrapForValidIteratorFieldIteratedNextMethod = 95,
    DisposableStackFieldState = 96,
    DisposableStackFieldCapability = 97,
    DisposableStackStatePending = 98,
    DisposableStackStateDisposed = 99,
    AsyncDisposableStackFieldState = 100,
    AsyncDisposableStackFieldCapability = 101,
    AsyncDisposableStackStatePending = 102,
    AsyncDisposableStackStateDisposed = 103,
    InternalMicrotaskAsyncFromSyncIteratorContinue = 104,
    InternalMicrotaskAsyncFromSyncIteratorDone = 105,
    OrderedHashTableSentinel = 106,
}

/// Nome e emitter de cada intrínseco, na ordem do enum `BytecodeIntrinsicEmitter`.
pub const EMITTER_TABLE: [(&str, BytecodeIntrinsicEmitter); 107] = [
    ("argument", BytecodeIntrinsicEmitter::Argument),
    ("argumentCount", BytecodeIntrinsicEmitter::ArgumentCount),
    ("arrayPush", BytecodeIntrinsicEmitter::ArrayPush),
    ("getByIdDirect", BytecodeIntrinsicEmitter::GetByIdDirect),
    ("getByIdDirectPrivate", BytecodeIntrinsicEmitter::GetByIdDirectPrivate),
    ("getByValWithThis", BytecodeIntrinsicEmitter::GetByValWithThis),
    ("getPrototypeOf", BytecodeIntrinsicEmitter::GetPrototypeOf),
    ("getInternalField", BytecodeIntrinsicEmitter::GetInternalField),
    ("getGeneratorInternalField", BytecodeIntrinsicEmitter::GetGeneratorInternalField),
    ("getIteratorHelperInternalField", BytecodeIntrinsicEmitter::GetIteratorHelperInternalField),
    ("getAsyncDisposableStackInternalField", BytecodeIntrinsicEmitter::GetAsyncDisposableStackInternalField),
    ("getArrayIteratorInternalField", BytecodeIntrinsicEmitter::GetArrayIteratorInternalField),
    ("getProxyInternalField", BytecodeIntrinsicEmitter::GetProxyInternalField),
    ("getWrapForValidIteratorInternalField", BytecodeIntrinsicEmitter::GetWrapForValidIteratorInternalField),
    ("getDisposableStackInternalField", BytecodeIntrinsicEmitter::GetDisposableStackInternalField),
    ("idWithProfile", BytecodeIntrinsicEmitter::IdWithProfile),
    ("isAsyncDisposableStack", BytecodeIntrinsicEmitter::IsAsyncDisposableStack),
    ("isObject", BytecodeIntrinsicEmitter::IsObject),
    ("isCallable", BytecodeIntrinsicEmitter::IsCallable),
    ("isConstructor", BytecodeIntrinsicEmitter::IsConstructor),
    ("isJSArray", BytecodeIntrinsicEmitter::IsJSArray),
    ("isProxyObject", BytecodeIntrinsicEmitter::IsProxyObject),
    ("isDerivedArray", BytecodeIntrinsicEmitter::IsDerivedArray),
    ("isGenerator", BytecodeIntrinsicEmitter::IsGenerator),
    ("isIteratorHelper", BytecodeIntrinsicEmitter::IsIteratorHelper),
    ("isPromise", BytecodeIntrinsicEmitter::IsPromise),
    ("isRegExpObject", BytecodeIntrinsicEmitter::IsRegExpObject),
    ("isMap", BytecodeIntrinsicEmitter::IsMap),
    ("isSet", BytecodeIntrinsicEmitter::IsSet),
    ("isShadowRealm", BytecodeIntrinsicEmitter::IsShadowRealm),
    ("isArrayIterator", BytecodeIntrinsicEmitter::IsArrayIterator),
    ("isUndefinedOrNull", BytecodeIntrinsicEmitter::IsUndefinedOrNull),
    ("isWrapForValidIterator", BytecodeIntrinsicEmitter::IsWrapForValidIterator),
    ("isDisposableStack", BytecodeIntrinsicEmitter::IsDisposableStack),
    ("throwTypeError", BytecodeIntrinsicEmitter::ThrowTypeError),
    ("throwRangeError", BytecodeIntrinsicEmitter::ThrowRangeError),
    ("throwOutOfMemoryError", BytecodeIntrinsicEmitter::ThrowOutOfMemoryError),
    ("putByIdDirect", BytecodeIntrinsicEmitter::PutByIdDirect),
    ("putByIdDirectPrivate", BytecodeIntrinsicEmitter::PutByIdDirectPrivate),
    ("putByValDirect", BytecodeIntrinsicEmitter::PutByValDirect),
    ("putByValWithThisSloppy", BytecodeIntrinsicEmitter::PutByValWithThisSloppy),
    ("putByValWithThisStrict", BytecodeIntrinsicEmitter::PutByValWithThisStrict),
    ("putInternalField", BytecodeIntrinsicEmitter::PutInternalField),
    ("putGeneratorInternalField", BytecodeIntrinsicEmitter::PutGeneratorInternalField),
    ("putAsyncDisposableStackInternalField", BytecodeIntrinsicEmitter::PutAsyncDisposableStackInternalField),
    ("putArrayIteratorInternalField", BytecodeIntrinsicEmitter::PutArrayIteratorInternalField),
    ("putDisposableStackInternalField", BytecodeIntrinsicEmitter::PutDisposableStackInternalField),
    ("superSamplerBegin", BytecodeIntrinsicEmitter::SuperSamplerBegin),
    ("superSamplerEnd", BytecodeIntrinsicEmitter::SuperSamplerEnd),
    ("toNumber", BytecodeIntrinsicEmitter::ToNumber),
    ("toString", BytecodeIntrinsicEmitter::ToString),
    ("toPropertyKey", BytecodeIntrinsicEmitter::ToPropertyKey),
    ("toObject", BytecodeIntrinsicEmitter::ToObject),
    ("toThis", BytecodeIntrinsicEmitter::ToThis),
    ("mustValidateResultOfProxyGetAndSetTraps", BytecodeIntrinsicEmitter::MustValidateResultOfProxyGetAndSetTraps),
    ("mustValidateResultOfProxyTrapsExceptGetAndSet", BytecodeIntrinsicEmitter::MustValidateResultOfProxyTrapsExceptGetAndSet),
    ("newArrayWithSize", BytecodeIntrinsicEmitter::NewArrayWithSize),
    ("newArrayWithSpecies", BytecodeIntrinsicEmitter::NewArrayWithSpecies),
    ("newPromise", BytecodeIntrinsicEmitter::NewPromise),
    ("iteratorGenericClose", BytecodeIntrinsicEmitter::IteratorGenericClose),
    ("iteratorGenericNext", BytecodeIntrinsicEmitter::IteratorGenericNext),
    ("ifAbruptCloseIterator", BytecodeIntrinsicEmitter::IfAbruptCloseIterator),
    ("createPromise", BytecodeIntrinsicEmitter::CreatePromise),
    ("undefined", BytecodeIntrinsicEmitter::Undefined),
    ("Infinity", BytecodeIntrinsicEmitter::Infinity),
    ("iterationKindKey", BytecodeIntrinsicEmitter::IterationKindKey),
    ("iterationKindValue", BytecodeIntrinsicEmitter::IterationKindValue),
    ("iterationKindEntries", BytecodeIntrinsicEmitter::IterationKindEntries),
    ("MAX_ARRAY_INDEX", BytecodeIntrinsicEmitter::MaxArrayIndex),
    ("MAX_STRING_LENGTH", BytecodeIntrinsicEmitter::MaxStringLength),
    ("MAX_SAFE_INTEGER", BytecodeIntrinsicEmitter::MaxSafeInteger),
    ("ModuleFetch", BytecodeIntrinsicEmitter::ModuleFetch),
    ("ModuleTranslate", BytecodeIntrinsicEmitter::ModuleTranslate),
    ("ModuleInstantiate", BytecodeIntrinsicEmitter::ModuleInstantiate),
    ("ModuleSatisfy", BytecodeIntrinsicEmitter::ModuleSatisfy),
    ("ModuleLink", BytecodeIntrinsicEmitter::ModuleLink),
    ("ModuleReady", BytecodeIntrinsicEmitter::ModuleReady),
    ("proxyFieldTarget", BytecodeIntrinsicEmitter::ProxyFieldTarget),
    ("proxyFieldHandler", BytecodeIntrinsicEmitter::ProxyFieldHandler),
    ("generatorFieldState", BytecodeIntrinsicEmitter::GeneratorFieldState),
    ("generatorFieldNext", BytecodeIntrinsicEmitter::GeneratorFieldNext),
    ("generatorFieldThis", BytecodeIntrinsicEmitter::GeneratorFieldThis),
    ("generatorFieldFrame", BytecodeIntrinsicEmitter::GeneratorFieldFrame),
    ("GeneratorResumeModeNormal", BytecodeIntrinsicEmitter::GeneratorResumeModeNormal),
    ("GeneratorResumeModeThrow", BytecodeIntrinsicEmitter::GeneratorResumeModeThrow),
    ("GeneratorResumeModeReturn", BytecodeIntrinsicEmitter::GeneratorResumeModeReturn),
    ("GeneratorStateCompleted", BytecodeIntrinsicEmitter::GeneratorStateCompleted),
    ("GeneratorStateExecuting", BytecodeIntrinsicEmitter::GeneratorStateExecuting),
    ("GeneratorStateInit", BytecodeIntrinsicEmitter::GeneratorStateInit),
    ("iteratorHelperFieldGenerator", BytecodeIntrinsicEmitter::IteratorHelperFieldGenerator),
    ("iteratorHelperFieldUnderlyingIterator", BytecodeIntrinsicEmitter::IteratorHelperFieldUnderlyingIterator),
    ("arrayIteratorFieldIndex", BytecodeIntrinsicEmitter::ArrayIteratorFieldIndex),
    ("arrayIteratorFieldIteratedObject", BytecodeIntrinsicEmitter::ArrayIteratorFieldIteratedObject),
    ("arrayIteratorFieldKind", BytecodeIntrinsicEmitter::ArrayIteratorFieldKind),
    ("wrapForValidIteratorFieldIteratedIterator", BytecodeIntrinsicEmitter::WrapForValidIteratorFieldIteratedIterator),
    ("wrapForValidIteratorFieldIteratedNextMethod", BytecodeIntrinsicEmitter::WrapForValidIteratorFieldIteratedNextMethod),
    ("disposableStackFieldState", BytecodeIntrinsicEmitter::DisposableStackFieldState),
    ("disposableStackFieldCapability", BytecodeIntrinsicEmitter::DisposableStackFieldCapability),
    ("DisposableStackStatePending", BytecodeIntrinsicEmitter::DisposableStackStatePending),
    ("DisposableStackStateDisposed", BytecodeIntrinsicEmitter::DisposableStackStateDisposed),
    ("asyncDisposableStackFieldState", BytecodeIntrinsicEmitter::AsyncDisposableStackFieldState),
    ("asyncDisposableStackFieldCapability", BytecodeIntrinsicEmitter::AsyncDisposableStackFieldCapability),
    ("AsyncDisposableStackStatePending", BytecodeIntrinsicEmitter::AsyncDisposableStackStatePending),
    ("AsyncDisposableStackStateDisposed", BytecodeIntrinsicEmitter::AsyncDisposableStackStateDisposed),
    ("InternalMicrotaskAsyncFromSyncIteratorContinue", BytecodeIntrinsicEmitter::InternalMicrotaskAsyncFromSyncIteratorContinue),
    ("InternalMicrotaskAsyncFromSyncIteratorDone", BytecodeIntrinsicEmitter::InternalMicrotaskAsyncFromSyncIteratorDone),
    ("orderedHashTableSentinel", BytecodeIntrinsicEmitter::OrderedHashTableSentinel),
];

/// Quantas das entradas de `EMITTER_NAMES` são funções (as demais são constantes).
pub const FUNCTION_COUNT: usize = 63;

/// `JSC_COMMON_BYTECODE_INTRINSIC_CONSTANTS_SIMPLE_EACH_NAME`: as constantes que o registro guarda
/// num `Strong<Unknown>` (`m_<name>`).
pub const SIMPLE_CONSTANT_NAMES: [&str; 43] = [
    "undefined",
    "Infinity",
    "iterationKindKey",
    "iterationKindValue",
    "iterationKindEntries",
    "MAX_ARRAY_INDEX",
    "MAX_STRING_LENGTH",
    "MAX_SAFE_INTEGER",
    "ModuleFetch",
    "ModuleTranslate",
    "ModuleInstantiate",
    "ModuleSatisfy",
    "ModuleLink",
    "ModuleReady",
    "proxyFieldTarget",
    "proxyFieldHandler",
    "generatorFieldState",
    "generatorFieldNext",
    "generatorFieldThis",
    "generatorFieldFrame",
    "GeneratorResumeModeNormal",
    "GeneratorResumeModeThrow",
    "GeneratorResumeModeReturn",
    "GeneratorStateCompleted",
    "GeneratorStateExecuting",
    "GeneratorStateInit",
    "iteratorHelperFieldGenerator",
    "iteratorHelperFieldUnderlyingIterator",
    "arrayIteratorFieldIndex",
    "arrayIteratorFieldIteratedObject",
    "arrayIteratorFieldKind",
    "wrapForValidIteratorFieldIteratedIterator",
    "wrapForValidIteratorFieldIteratedNextMethod",
    "disposableStackFieldState",
    "disposableStackFieldCapability",
    "DisposableStackStatePending",
    "DisposableStackStateDisposed",
    "asyncDisposableStackFieldState",
    "asyncDisposableStackFieldCapability",
    "AsyncDisposableStackStatePending",
    "AsyncDisposableStackStateDisposed",
    "InternalMicrotaskAsyncFromSyncIteratorContinue",
    "InternalMicrotaskAsyncFromSyncIteratorDone",
];

/// `enum class LinkTimeConstant : int32_t`, na ordem de `JSC_FOREACH_LINK_TIME_CONSTANTS`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum LinkTimeConstant {
    AddDisposableResource = 0,
    ArrayIteratorNextHelper = 1,
    BuiltinMapIterable = 2,
    BuiltinSetIterable = 3,
    CloseAllIterators = 4,
    CreateArrayWithoutPrototype = 5,
    CreateDisposableResource = 6,
    CreateInspectorInjectedScript = 7,
    CreateObjectWithoutPrototype = 8,
    CrossRealmThrow = 9,
    DefaultAsyncFromAsyncArrayLike = 10,
    DefaultAsyncFromAsyncIterator = 11,
    FlatIntoArray = 12,
    FlatIntoArrayWithCallback = 13,
    GeneratorResume = 14,
    GetAsyncDisposeMethod = 15,
    GetDisposeMethod = 16,
    GetIteratorFlattenable = 17,
    GetIteratorSync = 18,
    GetOptionsObject = 19,
    IteratorCloseAllNormal = 20,
    IteratorZip = 21,
    PerformIteration = 22,
    PerformProxyObjectGet = 23,
    PerformProxyObjectGetByVal = 24,
    PerformProxyObjectHas = 25,
    PerformProxyObjectHasByVal = 26,
    PerformProxyObjectSetByValSloppy = 27,
    PerformProxyObjectSetByValStrict = 28,
    PerformProxyObjectSetSloppy = 29,
    PerformProxyObjectSetStrict = 30,
    RemoveFirstFromList = 31,
    WrapRemoteValue = 32,
    WrappedIterator = 33,
    ThrowTypeErrorFunction = 34,
    ImportModule = 35,
    MapStorage = 36,
    MapIterationNext = 37,
    MapIterationEntry = 38,
    MapIterationEntryKey = 39,
    MapIterationEntryValue = 40,
    SetStorage = 41,
    SetIterationNext = 42,
    SetIterationEntry = 43,
    SetIterationEntryKey = 44,
    SetPrototypeDirect = 45,
    SetPrototypeDirectOrThrow = 46,
    CopyDataProperties = 47,
    CloneObject = 48,
    ResolvePromise = 49,
    RejectPromise = 50,
    FulfillPromise = 51,
    MarkPromiseAsHandled = 52,
    IsPromiseStatePending = 53,
    ResolvePromiseWithFirstResolvingFunctionCallCheck = 54,
    RejectPromiseWithFirstResolvingFunctionCallCheck = 55,
    FulfillPromiseWithFirstResolvingFunctionCallCheck = 56,
    NewResolvedPromise = 57,
    NewRejectedPromise = 58,
    ResolveWithInternalMicrotaskForAsyncAwait = 59,
    AsyncGeneratorPrototypeNext = 60,
    AsyncIteratorPrototypeSymbolAsyncIterator = 61,
    AsyncFunctionDrive = 62,
    NewHandledRejectedPromise = 63,
    PromiseReturnUndefinedOnFulfilled = 64,
    PromiseResolve = 65,
    PromiseReject = 66,
    PromiseResolveWithThen = 67,
    PerformPromiseThen = 68,
    MakeTypeError = 69,
    AggregateError = 70,
    TypedArrayLength = 71,
    ToIntegerOrInfinity = 72,
    ToLength = 73,
    IsTypedArrayView = 74,
    IsSharedTypedArrayView = 75,
    IsResizableOrGrowableSharedTypedArrayView = 76,
    TypedArrayFromFast = 77,
    IsDetached = 78,
    IsTypedArrayOutOfBounds = 79,
    IsFinite = 80,
    InstanceOf = 81,
    BuiltinLog = 82,
    BuiltinDescribe = 83,
    RegExp = 84,
    Iterator = 85,
    Min = 86,
    Promise = 87,
    DefaultPromiseThen = 88,
    RepeatCharacter = 89,
    IsArray = 90,
    Set = 91,
    Map = 92,
    ImportInRealm = 93,
    EvalFunction = 94,
    EvalInRealm = 95,
    MoveFunctionToRealm = 96,
    IsConstructor = 97,
    SameValue = 98,
    RegExpProtoFlagsGetter = 99,
    RegExpProtoGlobalGetter = 100,
    RegExpProtoHasIndicesGetter = 101,
    RegExpProtoIgnoreCaseGetter = 102,
    RegExpProtoMultilineGetter = 103,
    RegExpProtoSourceGetter = 104,
    RegExpProtoStickyGetter = 105,
    RegExpProtoDotAllGetter = 106,
    RegExpProtoUnicodeGetter = 107,
    RegExpProtoUnicodeSetsGetter = 108,
    RegExpBuiltinExec = 109,
    RegExpCreate = 110,
    IsRegExp = 111,
    RegExpSearchFast = 112,
    RegExpPrototypeSymbolMatch = 113,
    RegExpPrototypeSymbolMatchAll = 114,
    RegExpPrototypeSymbolReplace = 115,
    StringIncludesInternal = 116,
    StringIndexOfInternal = 117,
    StringSubstring = 118,
    HandleNegativeProxyHasTrapResult = 119,
    HandlePositiveProxySetTrapResult = 120,
    HandleProxyGetTrapResult = 121,
    Object = 122,
    Array = 123,
    ApplyFunction = 124,
    CallFunction = 125,
    HasOwnPropertyFunction = 126,
    CreatePrivateSymbol = 127,
    EmptyPropertyNameEnumerator = 128,
    SentinelString = 129,
    CreateRemoteFunction = 130,
    IsRemoteFunction = 131,
    ArrayFromFastWithoutMapFn = 132,
    JsonParse = 133,
    JsonStringify = 134,
    String = 135,
    Int8Array = 136,
    Uint8Array = 137,
    Uint8ClampedArray = 138,
    Int16Array = 139,
    Uint16Array = 140,
    Int32Array = 141,
    Uint32Array = 142,
    Float16Array = 143,
    Float32Array = 144,
    Float64Array = 145,
    BigInt64Array = 146,
    BigUint64Array = 147,
    WrapForValidIteratorCreate = 148,
    AsyncFromSyncIteratorCreate = 149,
    RegExpStringIteratorCreate = 150,
    IteratorHelperCreate = 151,
    OwnKeys = 152,
    ReferenceError = 153,
    SuppressedError = 154,
    DisposableStack = 155,
    AsyncDisposableStack = 156,
    EnqueueJob = 157,
}

/// `numberOfLinkTimeConstants`.
pub const NUMBER_OF_LINK_TIME_CONSTANTS: usize = 158;

/// Nome e valor de cada `LinkTimeConstant`, na ordem do enum.
pub const LINK_TIME_CONSTANT_TABLE: [(&str, LinkTimeConstant); 158] = [
    ("addDisposableResource", LinkTimeConstant::AddDisposableResource),
    ("arrayIteratorNextHelper", LinkTimeConstant::ArrayIteratorNextHelper),
    ("builtinMapIterable", LinkTimeConstant::BuiltinMapIterable),
    ("builtinSetIterable", LinkTimeConstant::BuiltinSetIterable),
    ("closeAllIterators", LinkTimeConstant::CloseAllIterators),
    ("createArrayWithoutPrototype", LinkTimeConstant::CreateArrayWithoutPrototype),
    ("createDisposableResource", LinkTimeConstant::CreateDisposableResource),
    ("createInspectorInjectedScript", LinkTimeConstant::CreateInspectorInjectedScript),
    ("createObjectWithoutPrototype", LinkTimeConstant::CreateObjectWithoutPrototype),
    ("crossRealmThrow", LinkTimeConstant::CrossRealmThrow),
    ("defaultAsyncFromAsyncArrayLike", LinkTimeConstant::DefaultAsyncFromAsyncArrayLike),
    ("defaultAsyncFromAsyncIterator", LinkTimeConstant::DefaultAsyncFromAsyncIterator),
    ("flatIntoArray", LinkTimeConstant::FlatIntoArray),
    ("flatIntoArrayWithCallback", LinkTimeConstant::FlatIntoArrayWithCallback),
    ("generatorResume", LinkTimeConstant::GeneratorResume),
    ("getAsyncDisposeMethod", LinkTimeConstant::GetAsyncDisposeMethod),
    ("getDisposeMethod", LinkTimeConstant::GetDisposeMethod),
    ("getIteratorFlattenable", LinkTimeConstant::GetIteratorFlattenable),
    ("getIteratorSync", LinkTimeConstant::GetIteratorSync),
    ("getOptionsObject", LinkTimeConstant::GetOptionsObject),
    ("iteratorCloseAllNormal", LinkTimeConstant::IteratorCloseAllNormal),
    ("iteratorZip", LinkTimeConstant::IteratorZip),
    ("performIteration", LinkTimeConstant::PerformIteration),
    ("performProxyObjectGet", LinkTimeConstant::PerformProxyObjectGet),
    ("performProxyObjectGetByVal", LinkTimeConstant::PerformProxyObjectGetByVal),
    ("performProxyObjectHas", LinkTimeConstant::PerformProxyObjectHas),
    ("performProxyObjectHasByVal", LinkTimeConstant::PerformProxyObjectHasByVal),
    ("performProxyObjectSetByValSloppy", LinkTimeConstant::PerformProxyObjectSetByValSloppy),
    ("performProxyObjectSetByValStrict", LinkTimeConstant::PerformProxyObjectSetByValStrict),
    ("performProxyObjectSetSloppy", LinkTimeConstant::PerformProxyObjectSetSloppy),
    ("performProxyObjectSetStrict", LinkTimeConstant::PerformProxyObjectSetStrict),
    ("removeFirstFromList", LinkTimeConstant::RemoveFirstFromList),
    ("wrapRemoteValue", LinkTimeConstant::WrapRemoteValue),
    ("wrappedIterator", LinkTimeConstant::WrappedIterator),
    ("throwTypeErrorFunction", LinkTimeConstant::ThrowTypeErrorFunction),
    ("importModule", LinkTimeConstant::ImportModule),
    ("mapStorage", LinkTimeConstant::MapStorage),
    ("mapIterationNext", LinkTimeConstant::MapIterationNext),
    ("mapIterationEntry", LinkTimeConstant::MapIterationEntry),
    ("mapIterationEntryKey", LinkTimeConstant::MapIterationEntryKey),
    ("mapIterationEntryValue", LinkTimeConstant::MapIterationEntryValue),
    ("setStorage", LinkTimeConstant::SetStorage),
    ("setIterationNext", LinkTimeConstant::SetIterationNext),
    ("setIterationEntry", LinkTimeConstant::SetIterationEntry),
    ("setIterationEntryKey", LinkTimeConstant::SetIterationEntryKey),
    ("setPrototypeDirect", LinkTimeConstant::SetPrototypeDirect),
    ("setPrototypeDirectOrThrow", LinkTimeConstant::SetPrototypeDirectOrThrow),
    ("copyDataProperties", LinkTimeConstant::CopyDataProperties),
    ("cloneObject", LinkTimeConstant::CloneObject),
    ("resolvePromise", LinkTimeConstant::ResolvePromise),
    ("rejectPromise", LinkTimeConstant::RejectPromise),
    ("fulfillPromise", LinkTimeConstant::FulfillPromise),
    ("markPromiseAsHandled", LinkTimeConstant::MarkPromiseAsHandled),
    ("isPromiseStatePending", LinkTimeConstant::IsPromiseStatePending),
    ("resolvePromiseWithFirstResolvingFunctionCallCheck", LinkTimeConstant::ResolvePromiseWithFirstResolvingFunctionCallCheck),
    ("rejectPromiseWithFirstResolvingFunctionCallCheck", LinkTimeConstant::RejectPromiseWithFirstResolvingFunctionCallCheck),
    ("fulfillPromiseWithFirstResolvingFunctionCallCheck", LinkTimeConstant::FulfillPromiseWithFirstResolvingFunctionCallCheck),
    ("newResolvedPromise", LinkTimeConstant::NewResolvedPromise),
    ("newRejectedPromise", LinkTimeConstant::NewRejectedPromise),
    ("resolveWithInternalMicrotaskForAsyncAwait", LinkTimeConstant::ResolveWithInternalMicrotaskForAsyncAwait),
    ("asyncGeneratorPrototypeNext", LinkTimeConstant::AsyncGeneratorPrototypeNext),
    ("asyncIteratorPrototypeSymbolAsyncIterator", LinkTimeConstant::AsyncIteratorPrototypeSymbolAsyncIterator),
    ("asyncFunctionDrive", LinkTimeConstant::AsyncFunctionDrive),
    ("newHandledRejectedPromise", LinkTimeConstant::NewHandledRejectedPromise),
    ("promiseReturnUndefinedOnFulfilled", LinkTimeConstant::PromiseReturnUndefinedOnFulfilled),
    ("promiseResolve", LinkTimeConstant::PromiseResolve),
    ("promiseReject", LinkTimeConstant::PromiseReject),
    ("promiseResolveWithThen", LinkTimeConstant::PromiseResolveWithThen),
    ("performPromiseThen", LinkTimeConstant::PerformPromiseThen),
    ("makeTypeError", LinkTimeConstant::MakeTypeError),
    ("AggregateError", LinkTimeConstant::AggregateError),
    ("typedArrayLength", LinkTimeConstant::TypedArrayLength),
    ("toIntegerOrInfinity", LinkTimeConstant::ToIntegerOrInfinity),
    ("toLength", LinkTimeConstant::ToLength),
    ("isTypedArrayView", LinkTimeConstant::IsTypedArrayView),
    ("isSharedTypedArrayView", LinkTimeConstant::IsSharedTypedArrayView),
    ("isResizableOrGrowableSharedTypedArrayView", LinkTimeConstant::IsResizableOrGrowableSharedTypedArrayView),
    ("typedArrayFromFast", LinkTimeConstant::TypedArrayFromFast),
    ("isDetached", LinkTimeConstant::IsDetached),
    ("isTypedArrayOutOfBounds", LinkTimeConstant::IsTypedArrayOutOfBounds),
    ("isFinite", LinkTimeConstant::IsFinite),
    ("instanceOf", LinkTimeConstant::InstanceOf),
    ("BuiltinLog", LinkTimeConstant::BuiltinLog),
    ("BuiltinDescribe", LinkTimeConstant::BuiltinDescribe),
    ("RegExp", LinkTimeConstant::RegExp),
    ("Iterator", LinkTimeConstant::Iterator),
    ("min", LinkTimeConstant::Min),
    ("Promise", LinkTimeConstant::Promise),
    ("defaultPromiseThen", LinkTimeConstant::DefaultPromiseThen),
    ("repeatCharacter", LinkTimeConstant::RepeatCharacter),
    ("isArray", LinkTimeConstant::IsArray),
    ("Set", LinkTimeConstant::Set),
    ("Map", LinkTimeConstant::Map),
    ("importInRealm", LinkTimeConstant::ImportInRealm),
    ("evalFunction", LinkTimeConstant::EvalFunction),
    ("evalInRealm", LinkTimeConstant::EvalInRealm),
    ("moveFunctionToRealm", LinkTimeConstant::MoveFunctionToRealm),
    ("isConstructor", LinkTimeConstant::IsConstructor),
    ("sameValue", LinkTimeConstant::SameValue),
    ("regExpProtoFlagsGetter", LinkTimeConstant::RegExpProtoFlagsGetter),
    ("regExpProtoGlobalGetter", LinkTimeConstant::RegExpProtoGlobalGetter),
    ("regExpProtoHasIndicesGetter", LinkTimeConstant::RegExpProtoHasIndicesGetter),
    ("regExpProtoIgnoreCaseGetter", LinkTimeConstant::RegExpProtoIgnoreCaseGetter),
    ("regExpProtoMultilineGetter", LinkTimeConstant::RegExpProtoMultilineGetter),
    ("regExpProtoSourceGetter", LinkTimeConstant::RegExpProtoSourceGetter),
    ("regExpProtoStickyGetter", LinkTimeConstant::RegExpProtoStickyGetter),
    ("regExpProtoDotAllGetter", LinkTimeConstant::RegExpProtoDotAllGetter),
    ("regExpProtoUnicodeGetter", LinkTimeConstant::RegExpProtoUnicodeGetter),
    ("regExpProtoUnicodeSetsGetter", LinkTimeConstant::RegExpProtoUnicodeSetsGetter),
    ("regExpBuiltinExec", LinkTimeConstant::RegExpBuiltinExec),
    ("regExpCreate", LinkTimeConstant::RegExpCreate),
    ("isRegExp", LinkTimeConstant::IsRegExp),
    ("regExpSearchFast", LinkTimeConstant::RegExpSearchFast),
    ("regExpPrototypeSymbolMatch", LinkTimeConstant::RegExpPrototypeSymbolMatch),
    ("regExpPrototypeSymbolMatchAll", LinkTimeConstant::RegExpPrototypeSymbolMatchAll),
    ("regExpPrototypeSymbolReplace", LinkTimeConstant::RegExpPrototypeSymbolReplace),
    ("stringIncludesInternal", LinkTimeConstant::StringIncludesInternal),
    ("stringIndexOfInternal", LinkTimeConstant::StringIndexOfInternal),
    ("stringSubstring", LinkTimeConstant::StringSubstring),
    ("handleNegativeProxyHasTrapResult", LinkTimeConstant::HandleNegativeProxyHasTrapResult),
    ("handlePositiveProxySetTrapResult", LinkTimeConstant::HandlePositiveProxySetTrapResult),
    ("handleProxyGetTrapResult", LinkTimeConstant::HandleProxyGetTrapResult),
    ("Object", LinkTimeConstant::Object),
    ("Array", LinkTimeConstant::Array),
    ("applyFunction", LinkTimeConstant::ApplyFunction),
    ("callFunction", LinkTimeConstant::CallFunction),
    ("hasOwnPropertyFunction", LinkTimeConstant::HasOwnPropertyFunction),
    ("createPrivateSymbol", LinkTimeConstant::CreatePrivateSymbol),
    ("emptyPropertyNameEnumerator", LinkTimeConstant::EmptyPropertyNameEnumerator),
    ("sentinelString", LinkTimeConstant::SentinelString),
    ("createRemoteFunction", LinkTimeConstant::CreateRemoteFunction),
    ("isRemoteFunction", LinkTimeConstant::IsRemoteFunction),
    ("arrayFromFastWithoutMapFn", LinkTimeConstant::ArrayFromFastWithoutMapFn),
    ("jsonParse", LinkTimeConstant::JsonParse),
    ("jsonStringify", LinkTimeConstant::JsonStringify),
    ("String", LinkTimeConstant::String),
    ("Int8Array", LinkTimeConstant::Int8Array),
    ("Uint8Array", LinkTimeConstant::Uint8Array),
    ("Uint8ClampedArray", LinkTimeConstant::Uint8ClampedArray),
    ("Int16Array", LinkTimeConstant::Int16Array),
    ("Uint16Array", LinkTimeConstant::Uint16Array),
    ("Int32Array", LinkTimeConstant::Int32Array),
    ("Uint32Array", LinkTimeConstant::Uint32Array),
    ("Float16Array", LinkTimeConstant::Float16Array),
    ("Float32Array", LinkTimeConstant::Float32Array),
    ("Float64Array", LinkTimeConstant::Float64Array),
    ("BigInt64Array", LinkTimeConstant::BigInt64Array),
    ("BigUint64Array", LinkTimeConstant::BigUint64Array),
    ("wrapForValidIteratorCreate", LinkTimeConstant::WrapForValidIteratorCreate),
    ("asyncFromSyncIteratorCreate", LinkTimeConstant::AsyncFromSyncIteratorCreate),
    ("regExpStringIteratorCreate", LinkTimeConstant::RegExpStringIteratorCreate),
    ("iteratorHelperCreate", LinkTimeConstant::IteratorHelperCreate),
    ("ownKeys", LinkTimeConstant::OwnKeys),
    ("ReferenceError", LinkTimeConstant::ReferenceError),
    ("SuppressedError", LinkTimeConstant::SuppressedError),
    ("DisposableStack", LinkTimeConstant::DisposableStack),
    ("AsyncDisposableStack", LinkTimeConstant::AsyncDisposableStack),
    ("enqueueJob", LinkTimeConstant::EnqueueJob),
];
