//! Gerado por `scripts/gen-opcodes.py` a partir de `derived/JavaScriptCore/Bytecodes.h`.
//! Não editar à mão.

/// `OpcodeID`: o número de cada opcode é a posição dele no `FOR_EACH_BYTECODE_ID`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[repr(u16)]
pub enum OpcodeID {
    op_tail_call_varargs = 0,
    op_call_varargs = 1,
    op_iterator_next = 2,
    op_construct_varargs = 3,
    op_super_construct_varargs = 4,
    op_iterator_open = 5,
    op_async_iterator_open = 6,
    op_instanceof = 7,
    op_set_private_brand = 8,
    op_check_private_brand = 9,
    op_put_by_id = 10,
    op_construct = 11,
    op_super_construct = 12,
    op_tail_call = 13,
    op_call_direct_eval = 14,
    op_create_generator = 15,
    op_create_async_generator = 16,
    op_create_promise = 17,
    op_catch = 18,
    op_new_array_with_size = 19,
    op_new_array_buffer = 20,
    op_get_by_id = 21,
    op_get_length = 22,
    op_profile_type = 23,
    op_profile_control_flow = 24,
    op_new_array_with_species = 25,
    op_call = 26,
    op_call_ignore_result = 27,
    op_async_iterator_next = 28,
    op_resolve_scope = 29,
    op_get_from_scope = 30,
    op_put_to_scope = 31,
    op_create_this = 32,
    op_new_object = 33,
    op_new_array = 34,
    op_put_private_name = 35,
    op_get_private_name = 36,
    op_get_by_val_with_this = 37,
    op_get_by_val = 38,
    op_put_by_val = 39,
    op_put_by_val_direct = 40,
    op_in_by_val = 41,
    op_enumerator_next = 42,
    op_enumerator_in_by_val = 43,
    op_enumerator_has_own_property = 44,
    op_enumerator_put_by_val = 45,
    op_to_this = 46,
    op_enumerator_get_by_val = 47,
    op_get_by_id_direct = 48,
    op_jneq_ptr = 49,
    op_get_argument = 50,
    op_get_from_arguments = 51,
    op_get_prototype_of = 52,
    op_get_internal_field = 53,
    op_get_by_id_with_this = 54,
    op_to_object = 55,
    op_in_by_id = 56,
    op_has_private_name = 57,
    op_has_private_brand = 58,
    op_put_by_id_with_this = 59,
    op_del_by_id = 60,
    op_put_by_val_with_this = 61,
    op_del_by_val = 62,
    op_put_getter_by_id = 63,
    op_put_setter_by_id = 64,
    op_put_getter_setter_by_id = 65,
    op_put_getter_by_val = 66,
    op_put_setter_by_val = 67,
    op_define_data_property = 68,
    op_define_accessor_property = 69,
    op_jmp = 70,
    op_jtrue = 71,
    op_jfalse = 72,
    op_jeq_null = 73,
    op_jneq_null = 74,
    op_jundefined_or_null = 75,
    op_jnundefined_or_null = 76,
    op_jeq_ptr = 77,
    op_jeq = 78,
    op_jstricteq = 79,
    op_jneq = 80,
    op_jnstricteq = 81,
    op_jless = 82,
    op_jlesseq = 83,
    op_jgreater = 84,
    op_jgreatereq = 85,
    op_jnless = 86,
    op_jnlesseq = 87,
    op_jngreater = 88,
    op_jngreatereq = 89,
    op_jbelow = 90,
    op_jbeloweq = 91,
    op_loop_hint = 92,
    op_switch_imm = 93,
    op_switch_char = 94,
    op_switch_string = 95,
    op_new_func = 96,
    op_new_func_exp = 97,
    op_new_generator_func = 98,
    op_new_generator_func_exp = 99,
    op_new_async_func = 100,
    op_new_async_func_exp = 101,
    op_new_async_generator_func = 102,
    op_new_async_generator_func_exp = 103,
    op_set_function_name = 104,
    op_ret = 105,
    op_strcat = 106,
    op_to_primitive = 107,
    op_to_property_key = 108,
    op_to_property_key_or_number = 109,
    op_put_to_arguments = 110,
    op_push_with_scope = 111,
    op_create_lexical_environment = 112,
    op_create_generator_frame_environment = 113,
    op_get_parent_scope = 114,
    op_throw = 115,
    op_throw_static_error = 116,
    op_debug = 117,
    op_get_property_enumerator = 118,
    op_unreachable = 119,
    op_create_rest = 120,
    op_yield = 121,
    op_check_traps = 122,
    op_log_shadow_chicken_prologue = 123,
    op_log_shadow_chicken_tail = 124,
    op_resolve_scope_for_hoisting_func_decl_in_eval = 125,
    op_put_internal_field = 126,
    op_nop = 127,
    op_super_sampler_begin = 128,
    op_wide16 = 129,
    op_super_sampler_end = 130,
    op_wide32 = 131,
    op_enter = 132,
    op_get_scope = 133,
    op_create_direct_arguments = 134,
    op_create_scoped_arguments = 135,
    op_create_cloned_arguments = 136,
    op_new_promise = 137,
    op_new_generator = 138,
    op_new_async_function_generator = 139,
    op_argument_count = 140,
    op_check_tdz = 141,
    op_new_array_with_spread = 142,
    op_spread = 143,
    op_new_reg_exp = 144,
    op_mov = 145,
    op_eq = 146,
    op_neq = 147,
    op_stricteq = 148,
    op_nstricteq = 149,
    op_less = 150,
    op_lesseq = 151,
    op_greater = 152,
    op_greatereq = 153,
    op_below = 154,
    op_beloweq = 155,
    op_mod = 156,
    op_pow = 157,
    op_urshift = 158,
    op_add = 159,
    op_mul = 160,
    op_div = 161,
    op_sub = 162,
    op_bitand = 163,
    op_bitor = 164,
    op_bitxor = 165,
    op_lshift = 166,
    op_rshift = 167,
    op_eq_null = 168,
    op_neq_null = 169,
    op_to_string = 170,
    op_is_empty = 171,
    op_typeof_is_undefined = 172,
    op_typeof_is_object = 173,
    op_typeof_is_function = 174,
    op_is_undefined_or_null = 175,
    op_is_boolean = 176,
    op_is_number = 177,
    op_is_big_int = 178,
    op_is_object = 179,
    op_is_callable = 180,
    op_is_constructor = 181,
    op_inc = 182,
    op_dec = 183,
    op_negate = 184,
    op_not = 185,
    op_identity_with_profile = 186,
    op_typeof = 187,
    op_is_cell_with_type = 188,
    op_has_structure_with_flags = 189,
    op_to_number = 190,
    op_to_numeric = 191,
    op_bitnot = 192,
    op_unsigned = 193,
}

/// `NUMBER_OF_BYTECODE_IDS`.
pub const NUMBER_OF_BYTECODE_IDS: usize = 194;

/// Todo `OpcodeID`, na ordem do número.
pub static OPCODE_IDS: [OpcodeID; NUMBER_OF_BYTECODE_IDS] = [
    OpcodeID::op_tail_call_varargs,
    OpcodeID::op_call_varargs,
    OpcodeID::op_iterator_next,
    OpcodeID::op_construct_varargs,
    OpcodeID::op_super_construct_varargs,
    OpcodeID::op_iterator_open,
    OpcodeID::op_async_iterator_open,
    OpcodeID::op_instanceof,
    OpcodeID::op_set_private_brand,
    OpcodeID::op_check_private_brand,
    OpcodeID::op_put_by_id,
    OpcodeID::op_construct,
    OpcodeID::op_super_construct,
    OpcodeID::op_tail_call,
    OpcodeID::op_call_direct_eval,
    OpcodeID::op_create_generator,
    OpcodeID::op_create_async_generator,
    OpcodeID::op_create_promise,
    OpcodeID::op_catch,
    OpcodeID::op_new_array_with_size,
    OpcodeID::op_new_array_buffer,
    OpcodeID::op_get_by_id,
    OpcodeID::op_get_length,
    OpcodeID::op_profile_type,
    OpcodeID::op_profile_control_flow,
    OpcodeID::op_new_array_with_species,
    OpcodeID::op_call,
    OpcodeID::op_call_ignore_result,
    OpcodeID::op_async_iterator_next,
    OpcodeID::op_resolve_scope,
    OpcodeID::op_get_from_scope,
    OpcodeID::op_put_to_scope,
    OpcodeID::op_create_this,
    OpcodeID::op_new_object,
    OpcodeID::op_new_array,
    OpcodeID::op_put_private_name,
    OpcodeID::op_get_private_name,
    OpcodeID::op_get_by_val_with_this,
    OpcodeID::op_get_by_val,
    OpcodeID::op_put_by_val,
    OpcodeID::op_put_by_val_direct,
    OpcodeID::op_in_by_val,
    OpcodeID::op_enumerator_next,
    OpcodeID::op_enumerator_in_by_val,
    OpcodeID::op_enumerator_has_own_property,
    OpcodeID::op_enumerator_put_by_val,
    OpcodeID::op_to_this,
    OpcodeID::op_enumerator_get_by_val,
    OpcodeID::op_get_by_id_direct,
    OpcodeID::op_jneq_ptr,
    OpcodeID::op_get_argument,
    OpcodeID::op_get_from_arguments,
    OpcodeID::op_get_prototype_of,
    OpcodeID::op_get_internal_field,
    OpcodeID::op_get_by_id_with_this,
    OpcodeID::op_to_object,
    OpcodeID::op_in_by_id,
    OpcodeID::op_has_private_name,
    OpcodeID::op_has_private_brand,
    OpcodeID::op_put_by_id_with_this,
    OpcodeID::op_del_by_id,
    OpcodeID::op_put_by_val_with_this,
    OpcodeID::op_del_by_val,
    OpcodeID::op_put_getter_by_id,
    OpcodeID::op_put_setter_by_id,
    OpcodeID::op_put_getter_setter_by_id,
    OpcodeID::op_put_getter_by_val,
    OpcodeID::op_put_setter_by_val,
    OpcodeID::op_define_data_property,
    OpcodeID::op_define_accessor_property,
    OpcodeID::op_jmp,
    OpcodeID::op_jtrue,
    OpcodeID::op_jfalse,
    OpcodeID::op_jeq_null,
    OpcodeID::op_jneq_null,
    OpcodeID::op_jundefined_or_null,
    OpcodeID::op_jnundefined_or_null,
    OpcodeID::op_jeq_ptr,
    OpcodeID::op_jeq,
    OpcodeID::op_jstricteq,
    OpcodeID::op_jneq,
    OpcodeID::op_jnstricteq,
    OpcodeID::op_jless,
    OpcodeID::op_jlesseq,
    OpcodeID::op_jgreater,
    OpcodeID::op_jgreatereq,
    OpcodeID::op_jnless,
    OpcodeID::op_jnlesseq,
    OpcodeID::op_jngreater,
    OpcodeID::op_jngreatereq,
    OpcodeID::op_jbelow,
    OpcodeID::op_jbeloweq,
    OpcodeID::op_loop_hint,
    OpcodeID::op_switch_imm,
    OpcodeID::op_switch_char,
    OpcodeID::op_switch_string,
    OpcodeID::op_new_func,
    OpcodeID::op_new_func_exp,
    OpcodeID::op_new_generator_func,
    OpcodeID::op_new_generator_func_exp,
    OpcodeID::op_new_async_func,
    OpcodeID::op_new_async_func_exp,
    OpcodeID::op_new_async_generator_func,
    OpcodeID::op_new_async_generator_func_exp,
    OpcodeID::op_set_function_name,
    OpcodeID::op_ret,
    OpcodeID::op_strcat,
    OpcodeID::op_to_primitive,
    OpcodeID::op_to_property_key,
    OpcodeID::op_to_property_key_or_number,
    OpcodeID::op_put_to_arguments,
    OpcodeID::op_push_with_scope,
    OpcodeID::op_create_lexical_environment,
    OpcodeID::op_create_generator_frame_environment,
    OpcodeID::op_get_parent_scope,
    OpcodeID::op_throw,
    OpcodeID::op_throw_static_error,
    OpcodeID::op_debug,
    OpcodeID::op_get_property_enumerator,
    OpcodeID::op_unreachable,
    OpcodeID::op_create_rest,
    OpcodeID::op_yield,
    OpcodeID::op_check_traps,
    OpcodeID::op_log_shadow_chicken_prologue,
    OpcodeID::op_log_shadow_chicken_tail,
    OpcodeID::op_resolve_scope_for_hoisting_func_decl_in_eval,
    OpcodeID::op_put_internal_field,
    OpcodeID::op_nop,
    OpcodeID::op_super_sampler_begin,
    OpcodeID::op_wide16,
    OpcodeID::op_super_sampler_end,
    OpcodeID::op_wide32,
    OpcodeID::op_enter,
    OpcodeID::op_get_scope,
    OpcodeID::op_create_direct_arguments,
    OpcodeID::op_create_scoped_arguments,
    OpcodeID::op_create_cloned_arguments,
    OpcodeID::op_new_promise,
    OpcodeID::op_new_generator,
    OpcodeID::op_new_async_function_generator,
    OpcodeID::op_argument_count,
    OpcodeID::op_check_tdz,
    OpcodeID::op_new_array_with_spread,
    OpcodeID::op_spread,
    OpcodeID::op_new_reg_exp,
    OpcodeID::op_mov,
    OpcodeID::op_eq,
    OpcodeID::op_neq,
    OpcodeID::op_stricteq,
    OpcodeID::op_nstricteq,
    OpcodeID::op_less,
    OpcodeID::op_lesseq,
    OpcodeID::op_greater,
    OpcodeID::op_greatereq,
    OpcodeID::op_below,
    OpcodeID::op_beloweq,
    OpcodeID::op_mod,
    OpcodeID::op_pow,
    OpcodeID::op_urshift,
    OpcodeID::op_add,
    OpcodeID::op_mul,
    OpcodeID::op_div,
    OpcodeID::op_sub,
    OpcodeID::op_bitand,
    OpcodeID::op_bitor,
    OpcodeID::op_bitxor,
    OpcodeID::op_lshift,
    OpcodeID::op_rshift,
    OpcodeID::op_eq_null,
    OpcodeID::op_neq_null,
    OpcodeID::op_to_string,
    OpcodeID::op_is_empty,
    OpcodeID::op_typeof_is_undefined,
    OpcodeID::op_typeof_is_object,
    OpcodeID::op_typeof_is_function,
    OpcodeID::op_is_undefined_or_null,
    OpcodeID::op_is_boolean,
    OpcodeID::op_is_number,
    OpcodeID::op_is_big_int,
    OpcodeID::op_is_object,
    OpcodeID::op_is_callable,
    OpcodeID::op_is_constructor,
    OpcodeID::op_inc,
    OpcodeID::op_dec,
    OpcodeID::op_negate,
    OpcodeID::op_not,
    OpcodeID::op_identity_with_profile,
    OpcodeID::op_typeof,
    OpcodeID::op_is_cell_with_type,
    OpcodeID::op_has_structure_with_flags,
    OpcodeID::op_to_number,
    OpcodeID::op_to_numeric,
    OpcodeID::op_bitnot,
    OpcodeID::op_unsigned,
];

impl OpcodeID {
    /// O `static_cast<OpcodeID>(value)` do C++ (`enum OpcodeID : unsigned`), com o `ASSERT` de faixa.
    pub fn from_u32(value: u32) -> OpcodeID {
        OPCODE_IDS[value as usize]
    }
}

/// Tamanho de cada instrução (opcode mais operandos), na ordem de `OpcodeID`.
pub static OPCODE_LENGTHS: [u8; NUMBER_OF_BYTECODE_IDS] = [7, 8, 10, 8, 8, 9, 9, 7, 3, 3, 5, 6, 6, 5, 9, 3, 3, 3, 3, 3, 4, 5, 4, 6, 2, 5, 6, 4, 8, 6, 8, 7, 4, 3, 5, 5, 5, 6, 5, 5, 5, 4, 6, 7, 7, 8, 4, 8, 5, 4, 3, 4, 3, 4, 5, 4, 3, 3, 3, 5, 4, 5, 4, 4, 4, 5, 4, 4, 4, 5, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 1, 3, 2, 2, 2, 3, 3, 4, 4, 2, 1, 2, 2, 2, 0, 2, 2, 0, 1, 2, 3, 3, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2, 4, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 3, 2, 3, 3, 3, 3, 3, 3];

/// Nome de cada opcode, na ordem de `OpcodeID` (o `opcodeNames` do C++).
pub static OPCODE_NAMES: [&str; NUMBER_OF_BYTECODE_IDS] = [
    "op_tail_call_varargs",
    "op_call_varargs",
    "op_iterator_next",
    "op_construct_varargs",
    "op_super_construct_varargs",
    "op_iterator_open",
    "op_async_iterator_open",
    "op_instanceof",
    "op_set_private_brand",
    "op_check_private_brand",
    "op_put_by_id",
    "op_construct",
    "op_super_construct",
    "op_tail_call",
    "op_call_direct_eval",
    "op_create_generator",
    "op_create_async_generator",
    "op_create_promise",
    "op_catch",
    "op_new_array_with_size",
    "op_new_array_buffer",
    "op_get_by_id",
    "op_get_length",
    "op_profile_type",
    "op_profile_control_flow",
    "op_new_array_with_species",
    "op_call",
    "op_call_ignore_result",
    "op_async_iterator_next",
    "op_resolve_scope",
    "op_get_from_scope",
    "op_put_to_scope",
    "op_create_this",
    "op_new_object",
    "op_new_array",
    "op_put_private_name",
    "op_get_private_name",
    "op_get_by_val_with_this",
    "op_get_by_val",
    "op_put_by_val",
    "op_put_by_val_direct",
    "op_in_by_val",
    "op_enumerator_next",
    "op_enumerator_in_by_val",
    "op_enumerator_has_own_property",
    "op_enumerator_put_by_val",
    "op_to_this",
    "op_enumerator_get_by_val",
    "op_get_by_id_direct",
    "op_jneq_ptr",
    "op_get_argument",
    "op_get_from_arguments",
    "op_get_prototype_of",
    "op_get_internal_field",
    "op_get_by_id_with_this",
    "op_to_object",
    "op_in_by_id",
    "op_has_private_name",
    "op_has_private_brand",
    "op_put_by_id_with_this",
    "op_del_by_id",
    "op_put_by_val_with_this",
    "op_del_by_val",
    "op_put_getter_by_id",
    "op_put_setter_by_id",
    "op_put_getter_setter_by_id",
    "op_put_getter_by_val",
    "op_put_setter_by_val",
    "op_define_data_property",
    "op_define_accessor_property",
    "op_jmp",
    "op_jtrue",
    "op_jfalse",
    "op_jeq_null",
    "op_jneq_null",
    "op_jundefined_or_null",
    "op_jnundefined_or_null",
    "op_jeq_ptr",
    "op_jeq",
    "op_jstricteq",
    "op_jneq",
    "op_jnstricteq",
    "op_jless",
    "op_jlesseq",
    "op_jgreater",
    "op_jgreatereq",
    "op_jnless",
    "op_jnlesseq",
    "op_jngreater",
    "op_jngreatereq",
    "op_jbelow",
    "op_jbeloweq",
    "op_loop_hint",
    "op_switch_imm",
    "op_switch_char",
    "op_switch_string",
    "op_new_func",
    "op_new_func_exp",
    "op_new_generator_func",
    "op_new_generator_func_exp",
    "op_new_async_func",
    "op_new_async_func_exp",
    "op_new_async_generator_func",
    "op_new_async_generator_func_exp",
    "op_set_function_name",
    "op_ret",
    "op_strcat",
    "op_to_primitive",
    "op_to_property_key",
    "op_to_property_key_or_number",
    "op_put_to_arguments",
    "op_push_with_scope",
    "op_create_lexical_environment",
    "op_create_generator_frame_environment",
    "op_get_parent_scope",
    "op_throw",
    "op_throw_static_error",
    "op_debug",
    "op_get_property_enumerator",
    "op_unreachable",
    "op_create_rest",
    "op_yield",
    "op_check_traps",
    "op_log_shadow_chicken_prologue",
    "op_log_shadow_chicken_tail",
    "op_resolve_scope_for_hoisting_func_decl_in_eval",
    "op_put_internal_field",
    "op_nop",
    "op_super_sampler_begin",
    "op_wide16",
    "op_super_sampler_end",
    "op_wide32",
    "op_enter",
    "op_get_scope",
    "op_create_direct_arguments",
    "op_create_scoped_arguments",
    "op_create_cloned_arguments",
    "op_new_promise",
    "op_new_generator",
    "op_new_async_function_generator",
    "op_argument_count",
    "op_check_tdz",
    "op_new_array_with_spread",
    "op_spread",
    "op_new_reg_exp",
    "op_mov",
    "op_eq",
    "op_neq",
    "op_stricteq",
    "op_nstricteq",
    "op_less",
    "op_lesseq",
    "op_greater",
    "op_greatereq",
    "op_below",
    "op_beloweq",
    "op_mod",
    "op_pow",
    "op_urshift",
    "op_add",
    "op_mul",
    "op_div",
    "op_sub",
    "op_bitand",
    "op_bitor",
    "op_bitxor",
    "op_lshift",
    "op_rshift",
    "op_eq_null",
    "op_neq_null",
    "op_to_string",
    "op_is_empty",
    "op_typeof_is_undefined",
    "op_typeof_is_object",
    "op_typeof_is_function",
    "op_is_undefined_or_null",
    "op_is_boolean",
    "op_is_number",
    "op_is_big_int",
    "op_is_object",
    "op_is_callable",
    "op_is_constructor",
    "op_inc",
    "op_dec",
    "op_negate",
    "op_not",
    "op_identity_with_profile",
    "op_typeof",
    "op_is_cell_with_type",
    "op_has_structure_with_flags",
    "op_to_number",
    "op_to_numeric",
    "op_bitnot",
    "op_unsigned",
];
