// GERADO por gen_caps.py a partir de include/Caps do ncurses 6.5-20250216. Não edite à mão.

use super::{Cap, Kind};

pub static BOOLS: [Cap; 44] = [
    Cap { var: "auto_left_margin", info: "bw", tc: "bw", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "auto_right_margin", info: "am", tc: "am", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "no_esc_ctlc", info: "xsb", tc: "xb", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "ceol_standout_glitch", info: "xhp", tc: "xs", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "eat_newline_glitch", info: "xenl", tc: "xn", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "erase_overstrike", info: "eo", tc: "eo", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "generic_type", info: "gn", tc: "gn", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "hard_copy", info: "hc", tc: "hc", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "has_meta_key", info: "km", tc: "km", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "has_status_line", info: "hs", tc: "hs", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "insert_null_glitch", info: "in", tc: "in", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "memory_above", info: "da", tc: "da", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "memory_below", info: "db", tc: "db", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "move_insert_mode", info: "mir", tc: "mi", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "move_standout_mode", info: "msgr", tc: "ms", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "over_strike", info: "os", tc: "os", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "status_line_esc_ok", info: "eslok", tc: "es", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "dest_tabs_magic_smso", info: "xt", tc: "xt", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "tilde_glitch", info: "hz", tc: "hz", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "transparent_underline", info: "ul", tc: "ul", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "xon_xoff", info: "xon", tc: "xo", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "needs_xon_xoff", info: "nxon", tc: "nx", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "prtr_silent", info: "mc5i", tc: "5i", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "hard_cursor", info: "chts", tc: "HC", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "non_rev_rmcup", info: "nrrmc", tc: "NR", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "no_pad_char", info: "npc", tc: "NP", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "non_dest_scroll_region", info: "ndscr", tc: "ND", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "can_change", info: "ccc", tc: "cc", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "back_color_erase", info: "bce", tc: "ut", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "hue_lightness_saturation", info: "hls", tc: "hl", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "col_addr_glitch", info: "xhpa", tc: "YA", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "cr_cancels_micro_mode", info: "crxm", tc: "YB", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "has_print_wheel", info: "daisy", tc: "YC", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "row_addr_glitch", info: "xvpa", tc: "YD", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "semi_auto_right_margin", info: "sam", tc: "YE", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "cpi_changes_res", info: "cpix", tc: "YF", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "lpi_changes_res", info: "lpix", tc: "YG", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "backspaces_with_bs", info: "OTbs", tc: "bs", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "crt_no_scrolling", info: "OTns", tc: "ns", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "no_correctly_working_cr", info: "OTnc", tc: "nc", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "gnu_has_meta_key", info: "OTMT", tc: "MT", kind: Kind::Bool, from_tc: false, param: 0 },
    Cap { var: "linefeed_is_newline", info: "OTNL", tc: "NL", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "has_hardware_tabs", info: "OTpt", tc: "pt", kind: Kind::Bool, from_tc: true, param: 0 },
    Cap { var: "return_does_clr_eol", info: "OTxr", tc: "xr", kind: Kind::Bool, from_tc: true, param: 0 },
];

pub static NUMS: [Cap; 39] = [
    Cap { var: "columns", info: "cols", tc: "co", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "init_tabs", info: "it", tc: "it", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "lines", info: "lines", tc: "li", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "lines_of_memory", info: "lm", tc: "lm", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "magic_cookie_glitch", info: "xmc", tc: "sg", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "padding_baud_rate", info: "pb", tc: "pb", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "virtual_terminal", info: "vt", tc: "vt", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "width_status_line", info: "wsl", tc: "ws", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "num_labels", info: "nlab", tc: "Nl", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "label_height", info: "lh", tc: "lh", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "label_width", info: "lw", tc: "lw", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "max_attributes", info: "ma", tc: "ma", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "maximum_windows", info: "wnum", tc: "MW", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "max_colors", info: "colors", tc: "Co", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "max_pairs", info: "pairs", tc: "pa", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "no_color_video", info: "ncv", tc: "NC", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "buffer_capacity", info: "bufsz", tc: "Ya", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "dot_vert_spacing", info: "spinv", tc: "Yb", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "dot_horz_spacing", info: "spinh", tc: "Yc", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "max_micro_address", info: "maddr", tc: "Yd", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "max_micro_jump", info: "mjump", tc: "Ye", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "micro_col_size", info: "mcs", tc: "Yf", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "micro_line_size", info: "mls", tc: "Yg", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "number_of_pins", info: "npins", tc: "Yh", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "output_res_char", info: "orc", tc: "Yi", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "output_res_line", info: "orl", tc: "Yj", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "output_res_horz_inch", info: "orhi", tc: "Yk", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "output_res_vert_inch", info: "orvi", tc: "Yl", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "print_rate", info: "cps", tc: "Ym", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "wide_char_size", info: "widcs", tc: "Yn", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "buttons", info: "btns", tc: "BT", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "bit_image_entwining", info: "bitwin", tc: "Yo", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "bit_image_type", info: "bitype", tc: "Yp", kind: Kind::Num, from_tc: false, param: 0 },
    Cap { var: "magic_cookie_glitch_ul", info: "OTug", tc: "ug", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "carriage_return_delay", info: "OTdC", tc: "dC", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "new_line_delay", info: "OTdN", tc: "dN", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "backspace_delay", info: "OTdB", tc: "dB", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "horizontal_tab_delay", info: "OTdT", tc: "dT", kind: Kind::Num, from_tc: true, param: 0 },
    Cap { var: "number_of_function_keys", info: "OTkn", tc: "kn", kind: Kind::Num, from_tc: false, param: 0 },
];

pub static STRS: [Cap; 414] = [
    Cap { var: "back_tab", info: "cbt", tc: "bt", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "bell", info: "bel", tc: "bl", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "carriage_return", info: "cr", tc: "cr", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "change_scroll_region", info: "csr", tc: "cs", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "clear_all_tabs", info: "tbc", tc: "ct", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "clear_screen", info: "clear", tc: "cl", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "clr_eol", info: "el", tc: "ce", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "clr_eos", info: "ed", tc: "cd", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "column_address", info: "hpa", tc: "ch", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "command_character", info: "cmdch", tc: "CC", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "cursor_address", info: "cup", tc: "cm", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "cursor_down", info: "cud1", tc: "do", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "cursor_home", info: "home", tc: "ho", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "cursor_invisible", info: "civis", tc: "vi", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "cursor_left", info: "cub1", tc: "le", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "cursor_mem_address", info: "mrcup", tc: "CM", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "cursor_normal", info: "cnorm", tc: "ve", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "cursor_right", info: "cuf1", tc: "nd", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "cursor_to_ll", info: "ll", tc: "ll", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "cursor_up", info: "cuu1", tc: "up", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "cursor_visible", info: "cvvis", tc: "vs", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "delete_character", info: "dch1", tc: "dc", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "delete_line", info: "dl1", tc: "dl", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "dis_status_line", info: "dsl", tc: "ds", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "down_half_line", info: "hd", tc: "hd", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "enter_alt_charset_mode", info: "smacs", tc: "as", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "enter_blink_mode", info: "blink", tc: "mb", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "enter_bold_mode", info: "bold", tc: "md", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "enter_ca_mode", info: "smcup", tc: "ti", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "enter_delete_mode", info: "smdc", tc: "dm", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "enter_dim_mode", info: "dim", tc: "mh", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "enter_insert_mode", info: "smir", tc: "im", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "enter_secure_mode", info: "invis", tc: "mk", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_protected_mode", info: "prot", tc: "mp", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_reverse_mode", info: "rev", tc: "mr", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "enter_standout_mode", info: "smso", tc: "so", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "enter_underline_mode", info: "smul", tc: "us", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "erase_chars", info: "ech", tc: "ec", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "exit_alt_charset_mode", info: "rmacs", tc: "ae", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "exit_attribute_mode", info: "sgr0", tc: "me", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "exit_ca_mode", info: "rmcup", tc: "te", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "exit_delete_mode", info: "rmdc", tc: "ed", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "exit_insert_mode", info: "rmir", tc: "ei", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "exit_standout_mode", info: "rmso", tc: "se", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "exit_underline_mode", info: "rmul", tc: "ue", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "flash_screen", info: "flash", tc: "vb", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "form_feed", info: "ff", tc: "ff", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "from_status_line", info: "fsl", tc: "fs", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "init_1string", info: "is1", tc: "i1", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "init_2string", info: "is2", tc: "is", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "init_3string", info: "is3", tc: "i3", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "init_file", info: "if", tc: "if", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "insert_character", info: "ich1", tc: "ic", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "insert_line", info: "il1", tc: "al", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "insert_padding", info: "ip", tc: "ip", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_backspace", info: "kbs", tc: "kb", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_catab", info: "ktbc", tc: "ka", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_clear", info: "kclr", tc: "kC", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_ctab", info: "kctab", tc: "kt", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_dc", info: "kdch1", tc: "kD", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_dl", info: "kdl1", tc: "kL", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_down", info: "kcud1", tc: "kd", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_eic", info: "krmir", tc: "kM", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_eol", info: "kel", tc: "kE", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_eos", info: "ked", tc: "kS", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f0", info: "kf0", tc: "k0", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_f1", info: "kf1", tc: "k1", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_f10", info: "kf10", tc: "k;", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f2", info: "kf2", tc: "k2", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_f3", info: "kf3", tc: "k3", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_f4", info: "kf4", tc: "k4", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_f5", info: "kf5", tc: "k5", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_f6", info: "kf6", tc: "k6", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_f7", info: "kf7", tc: "k7", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_f8", info: "kf8", tc: "k8", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_f9", info: "kf9", tc: "k9", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_home", info: "khome", tc: "kh", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_ic", info: "kich1", tc: "kI", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_il", info: "kil1", tc: "kA", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_left", info: "kcub1", tc: "kl", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_ll", info: "kll", tc: "kH", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_npage", info: "knp", tc: "kN", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_ppage", info: "kpp", tc: "kP", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_right", info: "kcuf1", tc: "kr", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_sf", info: "kind", tc: "kF", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sr", info: "kri", tc: "kR", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_stab", info: "khts", tc: "kT", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_up", info: "kcuu1", tc: "ku", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "keypad_local", info: "rmkx", tc: "ke", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "keypad_xmit", info: "smkx", tc: "ks", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "lab_f0", info: "lf0", tc: "l0", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "lab_f1", info: "lf1", tc: "l1", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "lab_f10", info: "lf10", tc: "la", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "lab_f2", info: "lf2", tc: "l2", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "lab_f3", info: "lf3", tc: "l3", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "lab_f4", info: "lf4", tc: "l4", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "lab_f5", info: "lf5", tc: "l5", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "lab_f6", info: "lf6", tc: "l6", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "lab_f7", info: "lf7", tc: "l7", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "lab_f8", info: "lf8", tc: "l8", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "lab_f9", info: "lf9", tc: "l9", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "meta_off", info: "rmm", tc: "mo", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "meta_on", info: "smm", tc: "mm", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "newline", info: "nel", tc: "nw", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "pad_char", info: "pad", tc: "pc", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "parm_dch", info: "dch", tc: "DC", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "parm_delete_line", info: "dl", tc: "DL", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "parm_down_cursor", info: "cud", tc: "DO", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "parm_ich", info: "ich", tc: "IC", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "parm_index", info: "indn", tc: "SF", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "parm_insert_line", info: "il", tc: "AL", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "parm_left_cursor", info: "cub", tc: "LE", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "parm_right_cursor", info: "cuf", tc: "RI", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "parm_rindex", info: "rin", tc: "SR", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "parm_up_cursor", info: "cuu", tc: "UP", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "pkey_key", info: "pfkey", tc: "pk", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "pkey_local", info: "pfloc", tc: "pl", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "pkey_xmit", info: "pfx", tc: "px", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "print_screen", info: "mc0", tc: "ps", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "prtr_off", info: "mc4", tc: "pf", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "prtr_on", info: "mc5", tc: "po", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "repeat_char", info: "rep", tc: "rp", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "reset_1string", info: "rs1", tc: "r1", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "reset_2string", info: "rs2", tc: "r2", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "reset_3string", info: "rs3", tc: "r3", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "reset_file", info: "rf", tc: "rf", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "restore_cursor", info: "rc", tc: "rc", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "row_address", info: "vpa", tc: "cv", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "save_cursor", info: "sc", tc: "sc", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "scroll_forward", info: "ind", tc: "sf", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "scroll_reverse", info: "ri", tc: "sr", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "set_attributes", info: "sgr", tc: "sa", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "set_tab", info: "hts", tc: "st", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "set_window", info: "wind", tc: "wi", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "tab", info: "ht", tc: "ta", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "to_status_line", info: "tsl", tc: "ts", kind: Kind::Str, from_tc: true, param: 1 },
    Cap { var: "underline_char", info: "uc", tc: "uc", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "up_half_line", info: "hu", tc: "hu", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "init_prog", info: "iprog", tc: "iP", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_a1", info: "ka1", tc: "K1", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_a3", info: "ka3", tc: "K3", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_b2", info: "kb2", tc: "K2", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_c1", info: "kc1", tc: "K4", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "key_c3", info: "kc3", tc: "K5", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "prtr_non", info: "mc5p", tc: "pO", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "char_padding", info: "rmp", tc: "rP", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "acs_chars", info: "acsc", tc: "ac", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "plab_norm", info: "pln", tc: "pn", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "key_btab", info: "kcbt", tc: "kB", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_xon_mode", info: "smxon", tc: "SX", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_xon_mode", info: "rmxon", tc: "RX", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_am_mode", info: "smam", tc: "SA", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_am_mode", info: "rmam", tc: "RA", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "xon_character", info: "xonc", tc: "XN", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "xoff_character", info: "xoffc", tc: "XF", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "ena_acs", info: "enacs", tc: "eA", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "label_on", info: "smln", tc: "LO", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "label_off", info: "rmln", tc: "LF", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_beg", info: "kbeg", tc: "@1", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_cancel", info: "kcan", tc: "@2", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_close", info: "kclo", tc: "@3", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_command", info: "kcmd", tc: "@4", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_copy", info: "kcpy", tc: "@5", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_create", info: "kcrt", tc: "@6", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_end", info: "kend", tc: "@7", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_enter", info: "kent", tc: "@8", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_exit", info: "kext", tc: "@9", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_find", info: "kfnd", tc: "@0", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_help", info: "khlp", tc: "%1", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_mark", info: "kmrk", tc: "%2", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_message", info: "kmsg", tc: "%3", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_move", info: "kmov", tc: "%4", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_next", info: "knxt", tc: "%5", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_open", info: "kopn", tc: "%6", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_options", info: "kopt", tc: "%7", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_previous", info: "kprv", tc: "%8", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_print", info: "kprt", tc: "%9", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_redo", info: "krdo", tc: "%0", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_reference", info: "kref", tc: "&1", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_refresh", info: "krfr", tc: "&2", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_replace", info: "krpl", tc: "&3", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_restart", info: "krst", tc: "&4", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_resume", info: "kres", tc: "&5", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_save", info: "ksav", tc: "&6", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_suspend", info: "kspd", tc: "&7", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_undo", info: "kund", tc: "&8", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sbeg", info: "kBEG", tc: "&9", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_scancel", info: "kCAN", tc: "&0", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_scommand", info: "kCMD", tc: "*1", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_scopy", info: "kCPY", tc: "*2", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_screate", info: "kCRT", tc: "*3", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sdc", info: "kDC", tc: "*4", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sdl", info: "kDL", tc: "*5", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_select", info: "kslt", tc: "*6", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_send", info: "kEND", tc: "*7", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_seol", info: "kEOL", tc: "*8", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sexit", info: "kEXT", tc: "*9", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sfind", info: "kFND", tc: "*0", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_shelp", info: "kHLP", tc: "#1", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "key_shome", info: "kHOM", tc: "#2", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "key_sic", info: "kIC", tc: "#3", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "key_sleft", info: "kLFT", tc: "#4", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "key_smessage", info: "kMSG", tc: "%a", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_smove", info: "kMOV", tc: "%b", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_snext", info: "kNXT", tc: "%c", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_soptions", info: "kOPT", tc: "%d", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sprevious", info: "kPRV", tc: "%e", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sprint", info: "kPRT", tc: "%f", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sredo", info: "kRDO", tc: "%g", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sreplace", info: "kRPL", tc: "%h", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sright", info: "kRIT", tc: "%i", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_srsume", info: "kRES", tc: "%j", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_ssave", info: "kSAV", tc: "!1", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_ssuspend", info: "kSPD", tc: "!2", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_sundo", info: "kUND", tc: "!3", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "req_for_input", info: "rfi", tc: "RF", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f11", info: "kf11", tc: "F1", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f12", info: "kf12", tc: "F2", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f13", info: "kf13", tc: "F3", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f14", info: "kf14", tc: "F4", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f15", info: "kf15", tc: "F5", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f16", info: "kf16", tc: "F6", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f17", info: "kf17", tc: "F7", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f18", info: "kf18", tc: "F8", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f19", info: "kf19", tc: "F9", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f20", info: "kf20", tc: "FA", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f21", info: "kf21", tc: "FB", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f22", info: "kf22", tc: "FC", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f23", info: "kf23", tc: "FD", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f24", info: "kf24", tc: "FE", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f25", info: "kf25", tc: "FF", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f26", info: "kf26", tc: "FG", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f27", info: "kf27", tc: "FH", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f28", info: "kf28", tc: "FI", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f29", info: "kf29", tc: "FJ", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f30", info: "kf30", tc: "FK", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f31", info: "kf31", tc: "FL", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f32", info: "kf32", tc: "FM", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f33", info: "kf33", tc: "FN", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f34", info: "kf34", tc: "FO", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f35", info: "kf35", tc: "FP", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f36", info: "kf36", tc: "FQ", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f37", info: "kf37", tc: "FR", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f38", info: "kf38", tc: "FS", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f39", info: "kf39", tc: "FT", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f40", info: "kf40", tc: "FU", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f41", info: "kf41", tc: "FV", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f42", info: "kf42", tc: "FW", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f43", info: "kf43", tc: "FX", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f44", info: "kf44", tc: "FY", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f45", info: "kf45", tc: "FZ", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f46", info: "kf46", tc: "Fa", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f47", info: "kf47", tc: "Fb", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f48", info: "kf48", tc: "Fc", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f49", info: "kf49", tc: "Fd", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f50", info: "kf50", tc: "Fe", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f51", info: "kf51", tc: "Ff", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f52", info: "kf52", tc: "Fg", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f53", info: "kf53", tc: "Fh", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f54", info: "kf54", tc: "Fi", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f55", info: "kf55", tc: "Fj", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f56", info: "kf56", tc: "Fk", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f57", info: "kf57", tc: "Fl", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f58", info: "kf58", tc: "Fm", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f59", info: "kf59", tc: "Fn", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f60", info: "kf60", tc: "Fo", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f61", info: "kf61", tc: "Fp", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f62", info: "kf62", tc: "Fq", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "key_f63", info: "kf63", tc: "Fr", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "clr_bol", info: "el1", tc: "cb", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "clear_margins", info: "mgc", tc: "MC", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set_left_margin", info: "smgl", tc: "ML", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set_right_margin", info: "smgr", tc: "MR", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "label_format", info: "fln", tc: "Lf", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "set_clock", info: "sclk", tc: "SC", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "display_clock", info: "dclk", tc: "DK", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "remove_clock", info: "rmclk", tc: "RC", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "create_window", info: "cwin", tc: "CW", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "goto_window", info: "wingo", tc: "WG", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "hangup", info: "hup", tc: "HU", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "dial_phone", info: "dial", tc: "DI", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "quick_dial", info: "qdial", tc: "QD", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "tone", info: "tone", tc: "TO", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "pulse", info: "pulse", tc: "PU", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "flash_hook", info: "hook", tc: "fh", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "fixed_pause", info: "pause", tc: "PA", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "wait_tone", info: "wait", tc: "WA", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "user0", info: "u0", tc: "u0", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "user1", info: "u1", tc: "u1", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "user2", info: "u2", tc: "u2", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "user3", info: "u3", tc: "u3", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "user4", info: "u4", tc: "u4", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "user5", info: "u5", tc: "u5", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "user6", info: "u6", tc: "u6", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "user7", info: "u7", tc: "u7", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "user8", info: "u8", tc: "u8", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "user9", info: "u9", tc: "u9", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "orig_pair", info: "op", tc: "op", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "orig_colors", info: "oc", tc: "oc", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "initialize_color", info: "initc", tc: "Ic", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "initialize_pair", info: "initp", tc: "Ip", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_color_pair", info: "scp", tc: "sp", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_foreground", info: "setf", tc: "Sf", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_background", info: "setb", tc: "Sb", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "change_char_pitch", info: "cpi", tc: "ZA", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "change_line_pitch", info: "lpi", tc: "ZB", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "change_res_horz", info: "chr", tc: "ZC", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "change_res_vert", info: "cvr", tc: "ZD", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "define_char", info: "defc", tc: "ZE", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "enter_doublewide_mode", info: "swidm", tc: "ZF", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_draft_quality", info: "sdrfq", tc: "ZG", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_italics_mode", info: "sitm", tc: "ZH", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_leftward_mode", info: "slm", tc: "ZI", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_micro_mode", info: "smicm", tc: "ZJ", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_near_letter_quality", info: "snlq", tc: "ZK", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_normal_quality", info: "snrmq", tc: "ZL", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_shadow_mode", info: "sshm", tc: "ZM", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_subscript_mode", info: "ssubm", tc: "ZN", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_superscript_mode", info: "ssupm", tc: "ZO", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_upward_mode", info: "sum", tc: "ZP", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_doublewide_mode", info: "rwidm", tc: "ZQ", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_italics_mode", info: "ritm", tc: "ZR", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_leftward_mode", info: "rlm", tc: "ZS", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_micro_mode", info: "rmicm", tc: "ZT", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_shadow_mode", info: "rshm", tc: "ZU", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_subscript_mode", info: "rsubm", tc: "ZV", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_superscript_mode", info: "rsupm", tc: "ZW", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_upward_mode", info: "rum", tc: "ZX", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "micro_column_address", info: "mhpa", tc: "ZY", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "micro_down", info: "mcud1", tc: "ZZ", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "micro_left", info: "mcub1", tc: "Za", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "micro_right", info: "mcuf1", tc: "Zb", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "micro_row_address", info: "mvpa", tc: "Zc", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "micro_up", info: "mcuu1", tc: "Zd", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "order_of_pins", info: "porder", tc: "Ze", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "parm_down_micro", info: "mcud", tc: "Zf", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "parm_left_micro", info: "mcub", tc: "Zg", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "parm_right_micro", info: "mcuf", tc: "Zh", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "parm_up_micro", info: "mcuu", tc: "Zi", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "select_char_set", info: "scs", tc: "Zj", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_bottom_margin", info: "smgb", tc: "Zk", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set_bottom_margin_parm", info: "smgbp", tc: "Zl", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_left_margin_parm", info: "smglp", tc: "Zm", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_right_margin_parm", info: "smgrp", tc: "Zn", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_top_margin", info: "smgt", tc: "Zo", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set_top_margin_parm", info: "smgtp", tc: "Zp", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "start_bit_image", info: "sbim", tc: "Zq", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "start_char_set_def", info: "scsd", tc: "Zr", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "stop_bit_image", info: "rbim", tc: "Zs", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "stop_char_set_def", info: "rcsd", tc: "Zt", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "subscript_characters", info: "subcs", tc: "Zu", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "superscript_characters", info: "supcs", tc: "Zv", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "these_cause_cr", info: "docr", tc: "Zw", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "zero_motion", info: "zerom", tc: "Zx", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "char_set_names", info: "csnm", tc: "Zy", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "key_mouse", info: "kmous", tc: "Km", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "mouse_info", info: "minfo", tc: "Mi", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "req_mouse_pos", info: "reqmp", tc: "RQ", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "get_mouse", info: "getm", tc: "Gm", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_a_foreground", info: "setaf", tc: "AF", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_a_background", info: "setab", tc: "AB", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "pkey_plab", info: "pfxl", tc: "xl", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "device_type", info: "devt", tc: "dv", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "code_set_init", info: "csin", tc: "ci", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set0_des_seq", info: "s0ds", tc: "s0", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set1_des_seq", info: "s1ds", tc: "s1", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set2_des_seq", info: "s2ds", tc: "s2", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set3_des_seq", info: "s3ds", tc: "s3", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set_lr_margin", info: "smglr", tc: "ML", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_tb_margin", info: "smgtb", tc: "MT", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "bit_image_repeat", info: "birep", tc: "Xy", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "bit_image_newline", info: "binel", tc: "Zz", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "bit_image_carriage_return", info: "bicr", tc: "Yv", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "color_names", info: "colornm", tc: "Yw", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "define_bit_image_region", info: "defbi", tc: "Yx", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "end_bit_image_region", info: "endbi", tc: "Yy", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set_color_band", info: "setcolor", tc: "Yz", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_page_length", info: "slines", tc: "YZ", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "display_pc_char", info: "dispc", tc: "S1", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "enter_pc_charset_mode", info: "smpch", tc: "S2", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_pc_charset_mode", info: "rmpch", tc: "S3", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_scancode_mode", info: "smsc", tc: "S4", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "exit_scancode_mode", info: "rmsc", tc: "S5", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "pc_term_options", info: "pctrm", tc: "S6", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "scancode_escape", info: "scesc", tc: "S7", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "alt_scancode_esc", info: "scesa", tc: "S8", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_horizontal_hl_mode", info: "ehhlm", tc: "Xh", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_left_hl_mode", info: "elhlm", tc: "Xl", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_low_hl_mode", info: "elohlm", tc: "Xo", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_right_hl_mode", info: "erhlm", tc: "Xr", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_top_hl_mode", info: "ethlm", tc: "Xt", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "enter_vertical_hl_mode", info: "evhlm", tc: "Xv", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "set_a_attributes", info: "sgr1", tc: "sA", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "set_pglen_inch", info: "slength", tc: "YI", kind: Kind::Str, from_tc: false, param: 1 },
    Cap { var: "termcap_init2", info: "OTi2", tc: "i2", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "termcap_reset", info: "OTrs", tc: "rs", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "linefeed_if_not_lf", info: "OTnl", tc: "nl", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "backspace_if_not_bs", info: "OTbc", tc: "bc", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "other_non_function_keys", info: "OTko", tc: "ko", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "arrow_key_map", info: "OTma", tc: "ma", kind: Kind::Str, from_tc: true, param: 0 },
    Cap { var: "acs_ulcorner", info: "OTG2", tc: "G2", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "acs_llcorner", info: "OTG3", tc: "G3", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "acs_urcorner", info: "OTG1", tc: "G1", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "acs_lrcorner", info: "OTG4", tc: "G4", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "acs_ltee", info: "OTGR", tc: "GR", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "acs_rtee", info: "OTGL", tc: "GL", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "acs_btee", info: "OTGU", tc: "GU", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "acs_ttee", info: "OTGD", tc: "GD", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "acs_hline", info: "OTGH", tc: "GH", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "acs_vline", info: "OTGV", tc: "GV", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "acs_plus", info: "OTGC", tc: "GC", kind: Kind::Str, from_tc: false, param: -1 },
    Cap { var: "memory_lock", info: "meml", tc: "ml", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "memory_unlock", info: "memu", tc: "mu", kind: Kind::Str, from_tc: false, param: 0 },
    Cap { var: "box_chars_1", info: "box1", tc: "bx", kind: Kind::Str, from_tc: false, param: 0 },
];

pub static BOOL_TERMINFO_SORT: [u16; 44] = [
    40, 41, 37, 39, 38, 42, 43, 1, 28, 0, 27, 23, 35, 31, 11, 32,
    12, 5, 16, 6, 7, 29, 9, 18, 10, 8, 36, 22, 13, 14, 26, 25,
    24, 21, 15, 34, 19, 4, 3, 30, 20, 2, 17, 33,
];

pub static BOOL_VARIABLE_SORT: [u16; 44] = [
    0, 1, 28, 37, 27, 3, 30, 35, 31, 38, 17, 4, 5, 6, 40, 7,
    23, 42, 8, 32, 9, 29, 10, 41, 36, 11, 12, 13, 14, 21, 39, 2,
    25, 26, 24, 15, 22, 43, 33, 34, 16, 18, 19, 20,
];

pub static BOOL_TERMCAP_SORT: [u16; 44] = [
    22, 23, 40, 26, 41, 25, 24, 30, 31, 32, 33, 34, 35, 36, 1, 37,
    0, 27, 11, 12, 5, 16, 6, 7, 29, 9, 18, 10, 8, 13, 14, 39,
    38, 21, 15, 42, 19, 28, 2, 4, 20, 43, 3, 17,
];

pub static NUM_TERMINFO_SORT: [u16; 39] = [
    36, 34, 35, 37, 38, 33, 31, 32, 30, 16, 13, 0, 28, 1, 9, 2,
    3, 10, 11, 19, 21, 20, 22, 15, 8, 23, 24, 26, 25, 27, 14, 5,
    18, 17, 6, 29, 12, 7, 4,
];

pub static NUM_VARIABLE_SORT: [u16; 39] = [
    36, 31, 32, 16, 30, 34, 0, 18, 17, 37, 1, 9, 10, 2, 3, 4,
    33, 11, 13, 19, 20, 14, 12, 21, 22, 35, 15, 8, 38, 23, 24, 26,
    25, 27, 5, 28, 6, 29, 7,
];

pub static NUM_TERMCAP_SORT: [u16; 39] = [
    30, 13, 12, 15, 8, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
    27, 28, 29, 31, 32, 0, 36, 34, 35, 37, 1, 38, 9, 2, 3, 10,
    11, 14, 5, 4, 33, 6, 7,
];

pub static STR_TERMINFO_SORT: [u16; 414] = [
    402, 400, 401, 403, 410, 407, 408, 405, 404, 406, 409, 397, 394, 398, 399, 396,
    395, 146, 1, 372, 371, 370, 26, 27, 413, 0, 306, 13, 5, 9, 16, 373,
    304, 2, 363, 354, 3, 111, 14, 107, 11, 112, 17, 10, 114, 19, 307, 20,
    277, 105, 21, 275, 374, 308, 362, 280, 30, 378, 106, 22, 352, 23, 37, 7,
    386, 6, 269, 387, 388, 155, 375, 389, 390, 391, 46, 45, 273, 47, 358, 24,
    12, 284, 8, 134, 132, 137, 279, 108, 52, 51, 110, 53, 129, 109, 299, 300,
    32, 54, 138, 48, 49, 50, 186, 187, 188, 189, 190, 191, 192, 194, 195, 196,
    197, 198, 199, 200, 201, 203, 202, 204, 205, 207, 206, 208, 211, 210, 209, 212,
    213, 214, 139, 140, 141, 158, 55, 142, 143, 159, 148, 160, 57, 161, 162, 163,
    58, 79, 61, 83, 87, 59, 60, 64, 63, 164, 165, 166, 65, 66, 67, 216,
    217, 218, 219, 220, 221, 222, 223, 224, 68, 225, 226, 227, 228, 229, 230, 231,
    232, 233, 234, 69, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 70, 245,
    246, 247, 248, 249, 250, 251, 252, 253, 254, 71, 255, 256, 257, 258, 259, 260,
    261, 262, 263, 264, 72, 265, 266, 267, 268, 73, 74, 75, 167, 168, 76, 86,
    77, 78, 84, 80, 355, 171, 169, 170, 81, 172, 173, 174, 82, 176, 175, 177,
    178, 182, 179, 85, 62, 180, 181, 183, 193, 184, 56, 185, 90, 91, 92, 93,
    94, 95, 96, 97, 98, 99, 100, 18, 305, 118, 119, 120, 144, 336, 330, 335,
    329, 337, 331, 338, 333, 411, 412, 270, 328, 356, 15, 332, 103, 298, 297, 104,
    285, 383, 115, 116, 117, 361, 147, 334, 33, 283, 281, 348, 126, 349, 121, 357,
    34, 125, 215, 130, 113, 321, 322, 38, 152, 276, 40, 41, 323, 42, 88, 157,
    101, 145, 380, 382, 43, 44, 150, 122, 123, 124, 324, 325, 326, 327, 320, 364,
    365, 366, 367, 346, 128, 385, 384, 274, 301, 339, 347, 310, 360, 359, 303, 376,
    302, 131, 39, 392, 311, 393, 377, 312, 25, 151, 28, 29, 340, 341, 271, 342,
    368, 272, 343, 344, 369, 345, 313, 31, 89, 156, 102, 379, 381, 35, 36, 149,
    314, 315, 316, 317, 318, 350, 319, 351, 309, 4, 282, 135, 287, 288, 289, 290,
    291, 292, 293, 294, 295, 296, 136, 127, 286, 133, 278, 154, 153, 353,
];

pub static STR_VARIABLE_SORT: [u16; 414] = [
    406, 146, 408, 401, 403, 404, 410, 405, 407, 400, 402, 409, 385, 399, 0, 397,
    1, 372, 371, 370, 413, 2, 304, 305, 306, 307, 3, 145, 354, 4, 270, 5,
    269, 6, 7, 363, 373, 8, 9, 277, 10, 11, 12, 13, 14, 15, 16, 17,
    18, 19, 20, 374, 308, 21, 22, 362, 280, 23, 275, 378, 24, 155, 375, 25,
    151, 26, 27, 28, 29, 30, 309, 310, 386, 31, 311, 387, 312, 388, 313, 314,
    315, 379, 33, 34, 389, 381, 32, 316, 35, 317, 318, 390, 36, 319, 391, 149,
    37, 38, 152, 39, 40, 41, 320, 42, 321, 322, 323, 380, 382, 324, 43, 325,
    326, 44, 327, 150, 285, 284, 45, 46, 47, 358, 278, 279, 48, 49, 50, 51,
    138, 299, 300, 52, 53, 54, 139, 140, 141, 55, 158, 148, 142, 143, 159, 56,
    57, 160, 161, 162, 163, 58, 59, 60, 61, 62, 164, 165, 63, 64, 166, 65,
    66, 67, 216, 217, 218, 219, 220, 221, 222, 223, 224, 68, 225, 226, 227, 228,
    229, 230, 231, 232, 233, 234, 69, 235, 236, 237, 238, 239, 240, 241, 242, 243,
    244, 70, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 71, 255, 256, 257,
    258, 259, 260, 261, 262, 263, 264, 72, 265, 266, 267, 268, 73, 74, 75, 167,
    168, 76, 77, 78, 79, 80, 169, 170, 355, 171, 172, 81, 173, 174, 82, 175,
    176, 177, 178, 179, 180, 181, 182, 83, 183, 186, 187, 188, 189, 190, 191, 192,
    193, 194, 195, 196, 84, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
    85, 208, 209, 210, 211, 212, 213, 86, 214, 184, 185, 87, 88, 89, 90, 91,
    92, 93, 94, 95, 96, 97, 98, 99, 100, 273, 157, 156, 396, 411, 412, 101,
    102, 328, 329, 330, 331, 332, 333, 356, 103, 334, 298, 297, 398, 104, 105, 106,
    107, 335, 108, 109, 110, 111, 336, 112, 337, 113, 114, 338, 383, 115, 116, 361,
    117, 147, 118, 144, 119, 120, 283, 281, 276, 121, 215, 357, 122, 123, 124, 125,
    126, 127, 128, 384, 129, 130, 339, 364, 365, 366, 367, 392, 360, 359, 131, 303,
    340, 341, 274, 376, 301, 302, 271, 342, 368, 377, 393, 272, 343, 132, 369, 344,
    345, 133, 346, 347, 348, 349, 350, 351, 134, 394, 395, 352, 135, 282, 136, 137,
    287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 286, 154, 153, 353,
];

pub static STR_TERMCAP_SORT: [u16; 414] = [
    212, 213, 214, 198, 199, 200, 201, 177, 168, 169, 170, 171, 172, 173, 174, 175,
    176, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 187, 178, 179, 180, 181,
    182, 183, 184, 185, 186, 197, 188, 189, 190, 191, 192, 193, 194, 195, 196, 167,
    158, 159, 160, 161, 162, 163, 164, 165, 166, 360, 359, 110, 9, 15, 277, 105,
    280, 275, 106, 107, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
    228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243,
    244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
    260, 261, 262, 263, 264, 265, 266, 267, 268, 402, 400, 401, 403, 410, 407, 408,
    405, 404, 406, 409, 358, 279, 108, 299, 300, 139, 141, 140, 142, 143, 355, 111,
    157, 156, 273, 270, 271, 368, 272, 369, 356, 285, 283, 281, 152, 276, 215, 112,
    357, 150, 378, 379, 380, 381, 382, 383, 384, 385, 151, 274, 109, 113, 149, 303,
    302, 282, 114, 286, 278, 154, 153, 386, 387, 388, 389, 390, 391, 370, 393, 377,
    372, 373, 374, 375, 376, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314,
    315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330,
    331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346,
    347, 348, 349, 350, 351, 352, 353, 354, 371, 146, 38, 53, 25, 397, 1, 0,
    413, 269, 7, 6, 8, 363, 5, 10, 2, 3, 4, 127, 21, 22, 29, 11,
    23, 362, 155, 37, 41, 42, 46, 284, 47, 24, 12, 137, 48, 394, 50, 138,
    52, 51, 31, 54, 49, 65, 66, 68, 69, 70, 71, 72, 73, 74, 75, 67,
    78, 148, 57, 59, 63, 84, 80, 77, 60, 62, 81, 82, 85, 64, 86, 56,
    55, 61, 88, 76, 79, 398, 83, 89, 58, 87, 90, 91, 93, 94, 95, 96,
    97, 98, 99, 100, 92, 14, 18, 399, 26, 27, 39, 30, 32, 411, 102, 101,
    33, 34, 412, 17, 396, 103, 298, 297, 144, 104, 119, 115, 116, 147, 120, 118,
    117, 122, 123, 124, 145, 126, 125, 121, 395, 364, 365, 366, 367, 392, 131, 128,
    43, 129, 35, 301, 130, 132, 134, 40, 28, 135, 287, 288, 289, 290, 291, 292,
    293, 294, 295, 296, 136, 44, 19, 36, 45, 16, 13, 20, 133, 361,
];
