# Os nomes públicos do `select`; a implementação mora no `_select`.
from _select import (
    EPOLLERR, EPOLLEXCLUSIVE, EPOLLET, EPOLLHUP, EPOLLIN, EPOLLMSG, EPOLLONESHOT, EPOLLOUT, EPOLLPRI,
    EPOLLRDBAND, EPOLLRDHUP, EPOLLRDNORM, EPOLLWRBAND, EPOLLWRNORM, EPOLL_CLOEXEC, PIPE_BUF, POLLERR, POLLHUP,
    POLLIN, POLLMSG, POLLNVAL, POLLOUT, POLLPRI, POLLRDBAND, POLLRDHUP, POLLRDNORM, POLLWRBAND, POLLWRNORM,
    epoll, error, poll, select)
